### ISSUE TITLE
Question: Execute computed only then two promises have filled two observables

### ISSUE THREAD

**Issue by jwamsterdam** [mobxjs/mobx#1058]
Hi,

I have two observables which get their data by an ComponentWillMount function that makes two API fetch requests.

The thing is that if call a is processed before call b, the computed function will run as expected.
But when call b is processed before call a, I get errors (e.g. sort not working etc).

How can I make a change so that my computed function only gets executed if the two promiss fetch calls have been processed?
Ideally, I do not want to chain my promiss calls, since that has direct impact om my initial page load performance.

**Comment by jamiewinder** [comment]
If you access a `computed`, it'll get evaluated. You can't prevent this, and even if you could, what you want to happen when something tries to access it? You need to have your `computed` properly handle the situation where either 'a' or 'b' isn't available. Something like:
```
@computed get combinedItems() {
    // 'a' and/or 'b' may be null if they haven't loaded yet
    if (this.a == null || this.b == null) {
        return null;
    }
    return [].concat(a, b);
}
```
For the above, `combinedItems` will evaluated to `null` if either a or b haven't loaded (i.e. are null), otherwise they'll evaluate to the combination arrays.

**Comment by eugene-daragan-codex** [comment]
I think you should use Bluebird's (or others) `Promise.all` function implementation to wait for both promises fulfilled and then write values to observables in a [transaction](https://mobx.js.org/refguide/transaction.html), i.e.:
```
var a = observable(0);
var b = observable(0);
var c = computed(() => a.get() + b.get());

Promise.all([
    fetch('some resource'),
    fetch('some other resource')
]).then(([responseA, responseB]) => {
    transaction(() => {
        a.set(responseA);
        b.set(responseB);
    })
})

```
In this case, your `c` computed will be notified about updated `a` and `b` values when both are fetched and written to the observables.
