### ISSUE TITLE
Composing mobx instances together?

### ISSUE THREAD

**Issue by mispy** [mobxjs/mobx#1061]
Mobx is lovely and optimizes well for many scenarios. But I'm not super sure how to use it best in this kind of scenario:

```
class UsefulComponent() {
    @observable a
    @observable b

    @computed get aplus() {
        return this.a+1
    }

    @computed get sum() {
        return a+b
    }

    constructor({a, b}) {
        this.a = a
        this.b = b
    }
}

class State() {
    @observable a
    @observable b

    @computed get component() {
        return new UsefulComponent({ a: this.a, b: this.b })
    }

    doStuff() {
        return this.component.sum
    }

    constructor({a, b}) {
        this.a = a
        this.b = b
    }
}
```

I often find I want to make little models like UsefulComponent that basically just run cached computation on some data. But I am not sure how to compose them into larger models correctly. For example in this case, `aplus` is not dependent on the value of `b`, but it will be recomputed anyway because the whole class gets reinstantiated by `State`.

So I end up wanting to do something like this:

```
get component() {
    const props = { a: this.a, b: this.b }

    if (this._component) { this.component.a = props.a; this.component.b = props.b }    
    else this._component = new UsefulComponent(props)

    return this._component
}
```

But this doesn't feel like the right way to do it either. I get the feeling mobx has a paradigm that more correctly handles this case, but I'm not super sure what it is...

**Comment by urugator** [comment]
I think the problem here is a state duplication. You hold the same state (`a` and `b`) at 2 different places (`State` and `UsefulComponent`) as seperate things. The duplication occurs when a, b are passed by value.
The cached computations are computed from different state than originaly intended.
In general once you pass something as value, you lost original observable state, because value alone can't be observed. 
It doesn't mean that the pattern you're using is completely wrong, it just doesn't go well with this usage ("just run cached computation on some data." - which data? the data owned by `UsefulComponent` or data owned by `State`? they're not the same in this case)
If you really need to have the state duplicated (for whatever reason), you will need a `reaction` to keep these states sync.

**Comment by mispy** [comment]
Thanks, that makes sense! I've ended up using this (slightly hacky) pattern of passing getters around to keep the data in a single canonical location when I can't just pass the data structure:

```
    @computed get legend() {
        const _this = this
        return new ColorLegend({
            maxWidth: 300,
            get items() { return _this.localData }
        })
    }
```
