### ISSUE TITLE
Any example for using flowtype with mobx store?

### ISSUE THREAD

**Issue by geohuz** [mobxjs/mobx#1068]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

I'm new to flow type and starting to apply it to my project. But I don't find any information in the documentation on general practical guide for doing this. I hope somebody can give me a suggestion?

**Comment by hawkins** [comment]
So, I've only been using flow for about a month now, but getting flow up and running with MobX should be pretty simple, so I'll outline the setup tasks here:

MobX stores should be isolated and in their own files, right? At least, that's how I've always done it - so you should be able to...

- add `// @flow` to the top of the file to enable flow
- then, I believe you can add MobX flow types with `flow-typed install mobx@x.x.x` or whatever your version is, since we have [flow type definitions included](https://github.com/mobxjs/mobx/blob/master/flow-typed/mobx.js)
- at this point I think you're done and you can write your types however's helpful for you. 

---

So I'm guessing the issue you're having here is less setup and more general usage of flow, is that right? Do you have any specific questions, or do you think a basic TODO app example with types is all you need?

**Comment by mweststrate** [comment]
@geohuz  Is something missing in the docs and should it be added? Feel free to open a PR, otherwise please close the question if the question is answered

**Comment by geohuz** [comment]
@hawkins , yeah an example app would be great! BTW, I found a github link: https://github.com/karlem/mobx-flow-example not sure if it's a good start
