### ISSUE TITLE
confused: @computed auto caching 

### ISSUE THREAD

**Issue by rasdaniil** [mobxjs/mobx#1093]
Hi 

Who could explain, why in this fiddle https://jsfiddle.net/w7s6rd4n/2/ every type I press "test computed" the computed value actually gets evaluated? I remember reading somewhere that computed values don't rerun if underlying values haven't changed...

Is there a workaround or should I keep computed's last state separately in private var and compare each time? 

(That becomes a hit on resources once we have complicated computed values...)

Thanks!

**Comment by rasdaniil** [comment]
Got it... "computed values are cached when they are observed"

**Comment by urugator** [comment]
Also check [keepAlive](https://github.com/mobxjs/mobx-utils#keepalive), but you should not be need it most of the time. It may seem counter intuitive at first, but the way to consume your app is to get interested about the state first (create observers) and then perform some actions. It's similar to attaching listeners before the events are fired. The difference is that computed works even if these "listeners" are not attached. In that case it presumes that you're interested about it's value only for this current invocation, so why to keep the value in memory ... someone would have to manually delete this value later ... and that's exactly what happens when you dispose the observers ...)

**Comment by IAIAE** [comment]
so, the computed value will not cached, isn't it??

**Comment by urugator** [comment]
@IAIAE 

```javascript
const a = observable(1);
const b = observable(2);

const sum = computed(() => {
  console.log("computing");
  return a.get() + b.get();
});

sum.get() // outputs "computing", returns result
sum.get() // outputs "computing", returns result
sum.get() // outputs "computing", returns result

// create an observer (reaction/autorun/render)
const disposeObserver = autorun(() => sum.get()) // outputs "computing", result is cached

sum.get() // outputs nothing, cached value returned
sum.get() // outputs nothing, cached value returned
sum.get() // outputs nothing, cached value returned

// dispose observer
disposeObserver()

sum.get() // outputs "computing", returns result
sum.get() // outputs "computing", returns result
sum.get() // outputs "computing", returns result
```

**Comment by IAIAE** [comment]
@urugator thx a lot!!!!

**Comment by codemilli** [comment]
@urugator so it's once read by reactive context it caches values, is it right?
