### ISSUE TITLE
Mobx not getting imported and bundled by Rollup

### ISSUE THREAD

**Issue by rbiggs** [mobxjs/mobx#1109]
I'm trying to use Mobx in an existing project using Rollup, Babel, Uglify to bundle and transpile.  I import like this:
```javascript
import {observable, autorun} from 'mobx'
```
Normally that will get included in the resulting bundle. Yet nothing gets included and in the browser I get the error that Mobx is undefined. When building, there is no error about not finding the imports. They simply never get included by Rollup in the final bundle. 

I'm using Rollup with Gulp as a gulp plugin: gulp-better-rollup: 1.1.1

I have Mobx version 3.2.1 installed from NPM.

**Comment by jamiewinder** [comment]
By default, I believe Rollup excludes libraries from the bundle (which is detects as non-absolute paths; i.e. 'abc' is assumed to be external, './abc' is not). Have you done anything to explicitly tell Rollup to include it?

**Comment by rbiggs** [comment]
Yup. My bad. You need to install rollup-plugin-node-resolve plugin:
```sh
nom i -D rollup-plugin-node-resolve
```
Next, import the plugin into the rollup config:
```javascript
var resolve = require("rollup-plugin-node-resolve")
```
Then add it to Rollup's plugins config:
```javascript 
plugins: [
  babel({
    exclude: 'node_modules/**'
  }),
  resolve({ jsnext: true }),
  uglify({
    compress: {
      collapse_vars: true
    }
  })
]
```
This results in Mobx being included in the bundle. Yay! 
However, this resulted in a new error when loaded in the browser: ReferenceError: Can't find variable: global, which points to:
```javascript
function getNextId() {
    return ++globalState.mobxGuid
}
```
This is in my bundle, so not sure why Mobx can't find it.

**Comment by tylerxo** [comment]
@rbiggs I also ran into this issue with my Rollup bundle flow. If you downgrad to version `3.1.11`, mobx will work as expected. The worst part of this problem is that the `ReferenceError : Can't find variable: global` is a runtime error, while the bundle appears to have compiled successfully.

The handful of releases before/around `3.1.14` introduced this issue, and has not been addressed since. `3.1.11` is the latest safe version to use with a production Rollup bundle.

**Comment by mweststrate** [comment]
cc: @rossipedia

**Comment by rossipedia** [comment]
argh... will investigate

**Comment by rossipedia** [comment]
got a handle on it. there's a [function](https://github.com/mobxjs/mobx/blob/master/src/utils/utils.ts#L4-L7) in mobx that assumes the presence of `global`. In the webpack build this was fine, because the browser `window` and node's `global` were normalized and passed into the UMD as a parameter with the name `global`. However, rollup doesn't do this. 

I'll have a fix incoming as soon as I verify that tests pass

**Comment by rbiggs** [comment]
Thanks a ton. That solved my problem.
