### ISSUE TITLE
Computed value not working as expected

### ISSUE THREAD

**Issue by codytooker** [mobxjs/mobx#1156]
I have a simple admin route that in componentDidMount() I check my authStore to see if a user is authenticated.  Below is the code for that.

```@inject('store') @observer
class Admin extends Component {

  componentWillMount() {
    const { isAuthenticated } = this.props.store.auth;
    console.log(this.props.store.auth);
    console.log(this.props.store.auth.isAuthenticated);
    if (!isAuthenticated) {
      console.log('is not authenticated');
      this.props.history.push('/login');
    }
  }

  render() {
    return (
      <div>
      </div>
    );
  }
}

export default Admin;
```

Relevant authStore looks like this

```class AuthStore {
  @observable id;
  @observable email;

  @computed get isAuthenticated() {
    return !!this.id;
  }
}

export default AuthStore;
```

isAuthenticated is just a simple quick check to see if an id exists.  This seems to work well except for in my componentDidMount function there are a couple weird things happening.

`console.log(this.props.store.auth);` produces an object in which isAuthenticated is correct and displays true.  However `console.log(this.props.store.auth.isAuthenticated);` by itself logs as false.

How can this possibly be happening?

**Comment by krnaveen14** [comment]
`console.log(this.props.store.auth);` - You're printing the object reference here. So it also displays the future property changes in that reference. Like, `id` value is changed after printing which triggers the `computed` property to `true` which is what displayed when navigating the object in console.

`console.log(this.props.store.auth.isAuthenticated);` - You printing the exact property value present at that time which is false.

I'm guessing you're expecting your component's `componentDidMount` to (re)execute when your computed property changes. But that's not gonna happen, because you've to destroy (aka unmount) your component and mount it again to make `componentDidMount` execute. 

You should be accessing the `observable` or `computed` properties during the `render()` call to tell mobx that these value changes should trigger the `render()` again.

**Comment by mweststrate** [comment]
@codytooker in your specific situation you should be problably doing something like:

```
disposer;
componentWillMount() {
    this.disposer = when(
       // as soon as this predicate becomes true
       () => this.props.store.auth.isAuthenticated, 
       // do that:
       () => this.props.history.push('/login');
}

componentWillUnmount() {
   // maybe it never happened... Let's make sure it doesn't happen when the condition becomes true in some the future, and cancel the 'when'
   this.disposer()
}
```
