### ISSUE TITLE
Is it possible to get all observable values from global state?

### ISSUE THREAD

**Issue by Raathigesh** [mobxjs/mobx#1200]
Hey guys,

I'm building a tool similar to [reactotron](https://github.com/infinitered/reactotron) but for Mobx. I'm wondering if there is a possibility of getting all the observable values mobx is tracking through some sort of internal global state of mobx. Tried a few APIs such as `getGlobalState` but did not find anything helpful.

Currently, the user would specify what observable object they want to inspect through the tool by doing the following.

```
import {initialize, inspect} from 'mobx-tracker-thingy-i'm-building';
import {observable} from 'mobx';

const store = observable({
  todos: []
});

// initializes the inspector
initialize();

// starts tracking store
inspect(store);
```

I'm wondering if there is a possibility to track all the observables mobx is managing application wide without the `inspect(store);` call through some internal API.

P.S. What do you think about a tool like that? I'm building it because I really want a tool like that and would be open sourcing soon.

**Comment by nighca** [comment]
We use [`spy`](https://mobx.js.org/refguide/spy.html) to track events(actions) across the whole application. That works but with some problems:

1. Most applications using MobX have more than stores, which makes it difficult to know which part of the application state changed.
2. Not all stores have a name. Stores defined in class-style have names, while plain stores defined with `observable(obj)` do not have a name. That makes it even harder to know which store is the target of current action.

That may be simpler when targeting apps using [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree/) instead of MobX.

**Comment by Raathigesh** [comment]
The tool targets both mobx and mobx-state-tree and I agree things are lot simpler in MST due to it's opinionated nature. 

If you are familiar with MST, could you help[ with this clarification](https://github.com/mobxjs/mobx-state-tree/issues/451)?

Thank you for your input 😄

**Comment by nighca** [comment]
Sorry for that, not so familiar with MST either.
