### ISSUE TITLE
why the m for mobx? how about obx?

### ISSUE THREAD

**Issue by williamle8300** [mobxjs/mobx#125]
the name is weird because there's an "m"? what's it for?

what about just using the name "obx"? object-exchangeable?

**Comment by bySabi** [comment]
`obx` name is taken:  https://www.npmjs.com/package/obx

**Comment by luisherranz** [comment]
I think it's in honour of the creator, Michel :)

**Comment by mweststrate** [comment]
Hi @williamle8300 Thanks for the suggestion and thinking along! But no thanks, I've just gone through a name change (see #115) and still recovering from it ;-). (updating old blogs, finding broken links, fighting with github pages, etc etc.).

Mobservable really started as a research expirement so I made the name up in five minutes. The idea was to improve the performance of React without loosing referential integrity. So it just came from observable and put an `m` in front of it, so it become `mob`, a mob of observers, many of them, serving you. In earlier blogs you will therefor see the name as `MOBservable` And yes it also refers nicely to `michel` and `mendix` (my employer). By reducing it to MobX I hope to make clear that the lib is actually about reactivity and not about observability (which is only a prerequisite). Also it is suitable for a new logo (which is in preparation) based on 'the Mob'. So that we can make a decent amount of jokes about it :)

**Comment by williamle8300** [comment]
though I get your point about the "mob of observers" it seems like you're stretching a bit to get there. technically, a react app may only have one observer. also don't really jive with the "vanity" aspect of putting in the "m." but anyway... i've been told i'm a very pedantic, and obsessed person before so take my ranting with a grain of salt. I just enjoy sharing my thoughts.

**Comment by williamle8300** [comment]
@mweststrate wait. forgot... thanks for your work on mobx! i'm really looking forward to giving it a test-drive sometime soon!

**Comment by mweststrate** [comment]
@williamle8300 no problem and thanks :) Test-drive should be fun! Let me know if it is something different. :)
