### ISSUE TITLE
Computed not updating if also unobserved fields are used?

### ISSUE THREAD

**Issue by hardcodet** [mobxjs/mobx#1277]
Not sure this is a bug, but wanted to report it anyway:

I have a component using a computed field (`fileUri`) in another class. Note that in that class that declares that computed field, the `downloadStatus` field is not observed, while `cacheFile` is. This seems to play into how MobX determines changes. My code first updates the `downloadStatus` field and then the `cacheFile` field.

This is the **working** variant:

    //name of the file in the cache, if there is one
    @observable cacheFile: string = undefined;

    //don't make this observable - fetching shouldn't rerender anything
    downloadStatus: DownloadStatus = DownloadStatus.None;

    //gets an uri to the actual file
    @computed get fileUri(): { uri: string } {
        const uri = this.cacheFile;
        if(this.downloadStatus === DownloadStatus.Fetched) {
            return {uri: uri};
        }

        //return dummy URI
        return {uri: "https://avatars2.githubusercontent.com/u/873009?s=88&v=4"};
    }

Now, if I move the `uri` const into the `if` clause, my component isn't updating anymore:

    //gets an uri to the actual file
    @computed get fileUri(): { uri: string } {
        if(this.downloadStatus === DownloadStatus.Fetched) {
            const uri = this.cacheFile; //the only thing I changed is the access of cacheFile down here
            return {uri: uri};
        }

        //return dummy URI
        return {uri: "https://avatars2.githubusercontent.com/u/873009?s=88&v=4"};
    }

Not sure whether this is erroneous behavior or not. (Btw, I deliberately didn't make the `downloadStatus` field observable, because it also has intermediary status flags that are of no interest to the component and shouldn't trigger rendering.)

**Comment by mweststrate** [comment]
This behavior is correct and `downloadStatus` should be observable as the output value of `fileUri` depends on it. 

Because as far as Mobx can tell, the output of your computed depends only on `downloadStatus`, so as long as that doesn't change it doesn't need to recompute. An it will never change because it is non observable in the current code.

If there are interesting and uninteresting values about downloadStatus, it sounds to me like you need two statues for downloads, where one is computed from the other and used by the components.

```
@observable status  = 1 // number between one and 100

// use this one in your components, it will update less often
@computed renderableStatus() {
   return Math.floor(this.states / 10)
}
```

**Comment by mweststrate** [comment]
Also see https://mobx.js.org/refguide/computed-decorator.html 3th and 4th paragraph

**Comment by EyalIsr** [comment]
I've encountered something quite similar, which seems to me a bug:
`@observable additionalRecords: number = 0;

@computed
get availableRecords: boolean {    
   // an if statement which is not observable-dependent
   ....
    return additionalRecords > 0;
  }
`
when `additionalRecords` changes to an "error indication value" (i.e. -1 for indicating data is still getting retrieved) which *is not bigger then 0* (like -1), this computed field is not being called.  
Only if change the computed field to this:  
`@computed
get availableRecords: boolean {    
   const localAdditionalRecords = this.additionalRecords;
   // an if statement which is not observable-dependent
   ....
    return localAdditionalRecords > 0;
  }`
the desired behaviour works - i.e. the function get called, and UI can "get notified" and act accordingly.  
I strongly feel that this scenario is different from the above, because IT IS using an `observable` field.
