### ISSUE TITLE
Question about action, transaction but not exactly 

### ISSUE THREAD

**Issue by askucher** [mobxjs/mobx#1304]
Hi 

I know you have action and transaction but I need something like 

```Livescript

runInTransaction (onSuccess) ->
    someFunctionCall (err)->
        somAnotherFunctionCall (err)->
            .....
            onSuccess "REFRESH VIEW NOW"
```
So I want to have `refresh function` as simple `function`. Not a `promise` not a `something` else 
what should I use?
and sometimes I want just do not invoke `onSuccess` because nothing actually happened but I want to change the model

**Comment by askucher** [comment]
Is anybody here? Project dead?

**Comment by jamiewinder** [comment]
Certainly not dead, but I'm not clear what you're trying to do.

An action doesn't end with views being refreshed (i.e. side effects running) unless something the side effect is looking at something that changed within the action. This for example:
```javascript
import { action, observable, reaction } from 'mobx';

const a = observable.box(0);
reaction(
  () => a.get(),
  (value) => console.log("reaction ran! value is " + value)
);
const update = action((next) => {
  if (next % 2 === 0) {
    a.set(next);
  }
});
update(1);
update(2);
update(3);
update(4);
update(4);
```
Would `console.log` once for 2 and once for 4. The odd numbers don't change anything that the reaction watches (so it doesn't run), and the duplicate `update(4)` doesn't actually change the value (so it doesn't run).

**Comment by askucher** [comment]
i would like to commit changes in where I do not know how many callbacks I have

**Comment by urugator** [comment]
There is no commit or rollback, transactions simply "delay" the scheduled reactions (render) at the end of outermost transaction.
Maybe check `createViewModel` from `mobx-utils`.  

However you can basically "commit" transaction by deferring the next call (because deffered call won't run as part of a current transaction):
```javascript
runInTransaction(() => {
  this.state = 5;
  // commit and run next action
  setTimeout(anotherTransaction, 0);
  // or perhaps
  Promise.resolve()
    .then(anotherTransaction)        
})
```

For a generic way to compose n functions take a look at:
Generators (eg. asyncActions in mobx-utils)
Monads (eg. Promise in JS)
FP (eg. pipe in ramda)
Connect like middlewares (eg. compose in koa)

**Comment by mweststrate** [comment]
Closing as question seems sufficiently answered
