### ISSUE TITLE
Confusing (but correct) behavior with @computed - Not always executing on changes

### ISSUE THREAD

**Issue by vitalybe** [mobxjs/mobx#1342]
Consider the following code:

```
@observer
class Stuff extends Component {
  @computed get currentList() {
    console.log("I am only called once!")
    return {items: this.props.appState.todos};
  }

  render() {
    return (
      <div>
        <div>{JSON.stringify(this.currentList)}</div>
        <button onClick={() => this.props.appState.todos.push({title: "Uhhh", done: false})}>Modify stuff</button>
      </div>
    );
  }
}

class State {
  @observable
  todos = [
    {
      title: "Create MobX intro video",
      done: false,
    },
    {
      title: "Take a nap",
      done: true,
    },
  ];
}

class App extends Component {
  constructor() {
    super();
    this.appState = new State();
  }

  render() {
    return <Stuff appState={this.appState} />;
  }
}
```

Everytime I press the button, the HTML is correctly re-rendered with the new `todos` item. However, the getter that's returning it `this.currentList` is only called once.

How does it work? How does it know to return the same object correctly without re-executing the getter function? I know that if I do something truly dynamic like:

```
  @computed get currentList() {
    console.log("I am only called once!")
    return {items: this.props.appState.todos.concat({title: "Dynamic item!"})};
  }
```

Then the getter function is called on every button press. 

But how does mobx know the difference between the first and the second versions?

**Comment by urugator** [comment]
If the computed is used by some reaction (`reaction/autorun/@observer`) it switches to "reactive mode"- it recomputes only when one of the computed's dependencies (observables used inside `computed`) is modified, otherwise it just returns previously cached result.
When you dispose the reaction (component is unmounted), the computed switches back to "passive mode" to prevent memory leaks.
Additionally when computed is recomputed, it checks whether the new value actually differs from the cached one (you can provide own `equals` function as an option). So it notifies depending `reactions` only when the result really changed.

Mobx knows whath depends on what by maintaining a dependency graph. The actual logic is hidden in getters/setters etc, eg: `appState.todos` invokes a getter, which adds `todos` to dependencies of `currentList`

**Comment by urugator** [comment]
In your case the difference between first and second `computed` is that:

The first `computed` is subscribed for a change of `appState.todos` property (for operations like `appState.todos = newPropertyValue`), because only the property was accessed inside computed, the content of the array wasn't accessed, therefore it has no influence on actual result of computation.

While the second `computed` is additionally subscribed for the change of array itself, because you have accessed the content of the array via `.concat`

**Comment by vitalybe** [comment]
Thank you for the detailed explanation.
