### ISSUE TITLE
[Question] Would mobx be suitable for storing high-throughput, structured JSON sensor data?

### ISSUE THREAD

**Issue by frantic0** [mobxjs/mobx#1353]
Hi 

I have use case for an application for an IoT device where data consists in high-throughput, structured JSON frames coming from websockets at 100Hz-200Hz. 100hz is a very fast rate and I know it doesn't make the case for rendering, however I do need to collect some integral chunks of data at that rate,  keep it in memory, and possible render these in real time.

Can I keep this data in mobx store? Would mobx provide a suitable state container for this? Any performance issues that would I be facing with it? Any recommendations whatsoever? 

Thanks
FØ

**Comment by mweststrate** [comment]
That should work fine, but do make sure you don't use autoconversion when
storing intensive amounts of data changes. E.g. `observable` will make all
objects recursively observable. But when working with data points from a
sensor that is probably not interesting, and you should be using methods
like `observable.shallowArray` to create a collection that is observable,
but won't convert it's contents into observables as well.

Op di 20 feb. 2018 om 03:40 schreef Francisco Bernardo <
notifications@github.com>:

**Comment by urugator** [comment]
You won't find out until you try ... if the rendering logic is complex (deep tree, lot of expensive renders) it may be faster to apply modifications to deep observable instead of replacing single shallow observable ... but it's a quesswork until you actually try.    
Keep in mind that react, mobx and others mainly focus on handling application complexity, not performance.
For example Mobx mainly tackles subscriptions ... it trades some performance for automatically resolving what depends on what.
React trades some performance for updating your UI automatically in a consistent way, etc...

**Comment by mweststrate** [comment]
A recommended read about the subject:
https://blog.lavrton.com/how-to-optimise-rendering-of-a-set-of-elements-in-react-ad01f5b161ae.
TL,DR: MobX is usually faster than handcrafted code, because the the
subscription mechanism is much more fine grained and hence more efficient
than subscription mechanisms you would be handcrafting.

Op di 20 feb. 2018 om 13:48 schreef urugator <notifications@github.com>:

**Comment by frantic0** [comment]
Thank you @mweststrate and @urugator for recommendations and resource. I'm going to give mobx a try and do a spike.

**Comment by mweststrate** [comment]
Cool! Next time, please close issues after they have been answered :)
