### ISSUE TITLE
[3.6.0] "TypeError: Invalid calling object" error in IE11

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx#1358]
This error happens when reactions have `{ compareStructural: true }` option. It started happening in `mobx@3.6.0` and originates on this line: https://github.com/mobxjs/mobx/blob/8f7f4a3e24e47b001c7e3073c69576086619c575/src/utils/eq.ts#L32

The reason is that `toString` is called as a global function. IE11 throws `TypeError: Invalid calling object` when it happens. `Object.prototype.toString` doesn't result in this error.

**Comment by le0nik** [comment]
Sure, the only thing stopping me is that i'm not quite sure how to test it here and whether it needs to be tested.

**Comment by mweststrate** [comment]
If you leave a comment on the fixed line, and you test it locally (`yarn
run small-build` in the mobx repo) and then `npm install <path to your mobx
repo>` in your test project, you should be able to verify the changes

Op wo 28 feb. 2018 om 12:24 schreef Leonid Nikiforenko <
notifications@github.com>:

**Comment by le0nik** [comment]
Ah, no i meant whether i can actually write a test for this case as i don't see saucelabs integration or karma config in the project.

**Comment by le0nik** [comment]
https://github.com/mobxjs/mobx/pull/1359

**Comment by mweststrate** [comment]
Correct, the project used tape-run in the past, but that project kinda
died, and since it never caught an actual bug (by far most browser bugs
where safari, which I cant run locally), I didn't bother migrating to
something else. If someone has experience with setting up running unit
tests on different browser stacks, a PR that runs the suite on different
browsers in the travis CI is welcome :)

Op wo 28 feb. 2018 om 12:35 schreef Leonid Nikiforenko <
notifications@github.com>:

**Comment by mweststrate** [comment]
Released as 3.6.1. Thanks!
