### ISSUE TITLE
Confusing `5 min intro` sample

### ISSUE THREAD

**Issue by deathmood** [mobxjs/mobx#136]
Hi! I've just heard about `mobx` and wanted to give it a try. I found this [5 min introduction ](https://mobxjs.github.io/mobx/getting-started.html) and read it. But there I saw some confusing (at least to me) thing: 

You pass down from parent `<TodoList>` component to child `<TodoView>` component not entire `store` via `props`, but only part of the `store` (concrete `todo` item of the `store's` array), and that is absolutely normal, but then, in the child you **_mutate_** (!!!) this `prop` --- and changes are reflected in `store`!!

The question is - is it normal to do this in real apps - I mean to directly mutate `state` passed **_partly_**  via `props`?

**Comment by mweststrate** [comment]
Good questions :).

MobX is unlike many other state management libs not a state container. It just helps you creating state containers. But in fact it totally doesn't matter where you get your data from. Some store, props, context, closure, global variables. It really doesn't matter, MobX will just track them because you have used them.

As such, it is technically perfectly fine to mutate objects you receive directly. From an architectural point of view you might rightfully prefer explicit methods that are exposed via the store (or by using classes). But that is a liberty you as a developer have. MobX is unopinionated about such things. To demonstrate this, and for brevity, the five minute introduction demonstrates both possibilities.

Does that help? And is the 5 minute introduction a good intro into MobX? In that case I will emphasize it a bit more :)

**Comment by deathmood** [comment]
Thanks much for your answer!! 

Maybe it's nice that `mobx` is not opinionated about the way we change `state`, but does not it harm data safety? You know, `state` feels just like a **_regular global object_**  ----  and any component that has access to it can do just **_anything_** to it. JavaScript (not TypeScript) does not private/public class variables --- so anyone can just give up on methods/actions and get direct access to data inside the state.

When you compare this situation to e.g `redux` (I am just comparing) --- while it also has `global state`, but it is **_only one_** and can be changed only in **_strictly defined way_** and you do not have direct access to data.


As for the `5 min intro` --- it is very nice for beginner to get in the idea of `mobx`. But for me it was strange to see component `props` mutations, moreover --- that mutations directly changed `state`!!
I'm not very experienced `react` developer but I've never seen/imagined `props` mutations))))
