### ISSUE TITLE
What does the observable decorator on a class property actually do?

### ISSUE THREAD

**Issue by dualscyther** [mobxjs/mobx#1364]
I have a:

1. [x] Question: Feel free to just state your question.

I'm just a little bit confused. I've been using the `@observable` decorator on my ES6 class properties for a while now, but I realised that I don't actually know what it does for things like primitives. Does it box the primitives? How does mobx track when a primitive class property is changed? Does it do this by making every class instance an observable?

Similarly, how does it know to recursively apply `observable` to any *existing* properties which are replaced in the future? For example if I have
```js
@observable foo = ['bar']
...
this.foo = ['bar2']
```

inside an ES6 class, how does it know to make the new `foo` an observable when it gets written to?

**Comment by urugator** [comment]
Mobx replaces props by getters/setter which performs subscription/notification. Actual values and metadata are stored on hidden prop on each instance (something like `instance.$mobx`).
Because decorators doesn't have an access to `this`, mobx actually has to define setters/getters on prototype, which lazily defines getters/setter on actual instance upon the first getter/setter invocation. (So props are sometimes not immediately visible on instace until you actually use them - which invokes the appropriate getter/setter on prototype...)

> how does it know to recursively apply observable
 
We (I) refer to this as "autoconversion". Mobx associates `enhancer` with each prop, which is used inside setter to convert object into observable. You can control the conversion "depth" (`enhancer` type) via `ref/deep/shallow` modifiers, defaulting to `deep`

**Comment by dualscyther** [comment]
Ahh cheers, this makes sense.
