### ISSUE TITLE
Customized decorator after `@observable` cause the bug about inheritance.

### ISSUE THREAD

**Issue by imcuttle** [mobxjs/mobx#1382]
```js
function customizeDecorator(target, property, descriptor) {
    // the crucial reason is here
    if (typeof target[property] === 'function') {
        throw new Error('some Error')
    }
    return descriptor
}

class P {
    @observable a = 'x'
    @observable v = 'pv'
}
class S extends P {
    @customizeDecorator
    @observable a = 's'
    @observable v = 'sv'
}

console.error(toJS(new S().v)) // expect to be 'sv', but 'pv'
```

**Comment by mweststrate** [comment]
Currently, until decorators are standardized, we do not support chaining decorators. (sometimes it does work properly though, like in serializr). But the reason for your decorator not working could be plenty, like the fact that the decorator is first applied to the prototype, but once the mobx decorator is done, it redeclares the fields on the instances, which might cause your decorator on the prototype to be shadowed.

That being said, re-declaring fields is a bad idea anyway (some languages don't even allow it). Instead, if you just want to change the initial value, use your constructor in `S` for that, rather than declaring the field a second time in the inheritance chain.
