### ISSUE TITLE
Support @computed methods

### ISSUE THREAD

**Issue by LandonSchropp** [mobxjs/mobx#1388]
I'd love to see methods supporte for `@computed`.

## What problem will this solve?

In my application, I have a `ColorStore` class that allows me to access and mutate color attributes.

``` js
class ColorStore {
  @observable hue;
  @observable saturation;
  @observable value;
  @observable alpha;

  toString() {
    ...
  }
}
```

The `toString` method works great! It allows me to pass a `ColorStore` directly in a `style` property.

``` jsx
<div style={ { backgroundColor: colorStore } } />
```

It also works great with template strings:

``` js
`The color is: ${ colorStore }`
```

Unfortunately, MobX will not let me make `toString` a computed method. When I try, I get this error:

```
[mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'
```

## Do I think others would benefit from this?

Yep! `toString` is part of `Object.prototype`, so I can't be the only one taking advantage of it.

## Should it be in core?

It seems like it to me.

## Would I be willing to contribute a PR?

This feels like it might be a big first change for someone new to this project. However, if you feel like it's relatively simple I'd be happy to give it a try.

**Comment by urugator** [comment]
I won't commment on whether it should be possible to decorate methods with `@computed`, I will just point out, in case you're not aware of that already, that the `@computed` is not necessary for the component to track the observables accessed inside `toString`. The only difference is that `@computed` would cache `toString` result. Currently you can achieve the same like:  
```javascript
@computed
get cssValue() {
  // ...
}

toString() {
  return cssValue;
}
```

**Comment by LandonSchropp** [comment]
@urugator That's a cool trick! Thanks for sharing. I'll do that to work around my current issue.

However, I still think this would be a great addition to MobX.

**Comment by mweststrate** [comment]
Note that you could do. 

```javascript
toString() {
   return computed(() => this.cssValue).get()
}
```

This pattern is generically applicable, even when there multiple arguments. But it is not generally memoizable (that is, ideally you want to to return the same `computed` instance for the same set of arguments), because that could very easily introduce memory leaks. Hence we din't introduce a standardized approach to it yet.

Also not, that functions that are not marked `@computed` can still be used in a reactive context! Mobx will track through entire call stacks, not just `@computed` marked things. The only exception to that are actions, they will never be tracked.

**Comment by mweststrate** [comment]
To elaborate a bit more on the above; for methods with arguments for which you want the returned `computed` to be cached, one can simply do the following:

```typescript
// Parameterized computed views:
// Create computed's and store them in a cache
import { observable, computed } from "mobx"

class Todos {
  @observable todos = []
  
  private todosByUserCache = new Map()

  getAllTodosByUser(userId) {
    if (this.todosByUser.has(userId))
      return this.todosByUser.get(userId).get()
      
    const computedFilter = computed(() => {
      return this.todos.filter(todo => todo.user === userId)
    })
    this.todosByUserCache.set(userId, computedFilter)
    return res.get()
  }
}
```

The reason this is not built in, is that MobX cannot reason about when items should be removed from the cache; that is domain specific knowledge. In many applications it probably won't even matter that the cache isn't reset. But doing that as a default behavior would be irresponsible as it would create memory-leaks-by-default.

**Comment by mweststrate** [comment]
N.B. it could be possible to use the `onBecomeObserved` hook on the `computed` 's returned in the above example to automatically remove entries from the cache in the above pattern. The question is, would this be a good default strategy, as it might lead to a lot of cache misses.

**Comment by urugator** [comment]
@mweststrate last line: `return todosByUserCache.get()` => `computedFilter.get()`

> when items should be removed from the cache; that is domain specific knowledge

Most likely user will end up with something like
```javascript
// called as a result of some event/user interaction
@action removeUser(userId) {
  invalidateUserTodoCache(userId)
}
```

And once you have to be explicit about the user deletation (invalidation of the cache), I think it's better to do the same for user creation and get rid of the cache.
```javascript
// eg called from componentDidUpdate when `props.userId !== prevProps.userId` 
@action addUser(userId) {
  // ...  
  userTodos.set(userId, computation) 
}

@action removeUser(userId) {
  // ...
  userTodos.delete(userId, computation)  
}
```
At which point I would susggest to normalize the state and replace the computation with a quick id lookup
``` 
getAllTodosByUser(userId) {
  return user.todos.map(id => todos[id]);
}
```

>  The question is, would this be a good default strategy

I think it would be excellent strategy, because the computed is acually useless when not observed and so is the `todosByUserCache` (because it doesn't hold anything stateful at that point). But perhaps I am missing something...

**Comment by mweststrate** [comment]
Added the above to the docs, discussion can be continued in https://github.com/mobxjs/mobx-utils/issues/184

@urugator I agree for the example it might be overkill, it was just a trivial example and your way of solving it is probably better, but neat thing about the proposed solution it works for n-ary functions, unlike for example `createTransformer`. (and managing n-ary maps will become cumbersome quickly when done manually)

**Comment by mweststrate** [comment]
Solved!

Mobx-util's `computedFn` now supports creating computeds for functions with arguments: https://github.com/mobxjs/mobx-utils#computedfn

**Comment by LandonSchropp** [comment]
This is great! Thank you.
