### ISSUE TITLE
How to have a store depending of another store.

### ISSUE THREAD

**Issue by oximer** [mobxjs/mobx#1401]
```
import { observable, computed, action } from 'mobx';

export default class PermissionStore {
  @observable permissions = ['A', 'B', 'C'];

  @action
  includePermission() {
    console.log('includePermission', this.permissions);
    this.permissions.push('D');
  }
}
```

```
import { observable, computed, action } from 'mobx';
import PermissionStore from './PermissionStore';

export default class WorkAreaStore {
  @observable workItens = [];
  @observable permissions = new PermissionStore().permissions;

  async getWorkItens() {
    console.log('getWorkItens');
    this.workItens = [{ name: 'Work1', permission: ['A'] }, { name: 'Work2', permission: ['B'] }, { name: 'Work3', permission: ['D'] }];
  }

  @computed
  get availableWorkItens() {
    console.log('Calculating availableWorkItens', this.workItens, this.permission);
    return this.workItens.filter(item => {
      return this.permissions.includes(item.permission[0]);
    });
  }
}
```

```
import React from 'react';
import { Text, View, Button } from 'react-native';
import { observer, inject } from 'mobx-react';

@inject('workAreaStore')
@inject('permissionStore')
@observer
export default class Home extends React.Component {
  getWorkItens() {
    this.props.workAreaStore.getWorkItens();
  }

  updatePermission() {
    this.props.permissionStore.includePermission();
  }

  render() {
    console.log('this.props.workAreaStore.availableWorkItens', this.props.workAreaStore.availableWorkItens);
    return (
      <View style={{ flex: 1, backgroundColor: 'gray' }}>
        {this.props.workAreaStore.availableWorkItens.map(item => {
          console.log('item', item);
          return <Text key={item.name}>{item.name}</Text>;
        })}

        <Button title="WorkItens" onPress={() => this.getWorkItens()} />
        <Button title="Update Permissions" onPress={() => this.updatePermission()} />
      </View>
    );
  }
}
```
What is wrong with it? How should I structure it, so if I change the permission set, I will have  availableWorkItens executed?

**Comment by jamiewinder** [comment]
It looks broadly right. I notice your collection property in PermissionStore is 'permissions', but your WorkAreaStore accesses 'permission'. However I'd have thought this would throw an obvious exception since you'd be calling `.includes` on `undefined`.

**Comment by oximer** [comment]
I probably mistype it while writing it here, but this is not the issue

**Comment by jamiewinder** [comment]
Another thing that sticks out in your code samepl, is that your `WorkAreaStore` creates its own `PermissionsStore` just to pull out the `permissions` property. However, if you do this you're not going to have the instance in order to call `includePermission` on it. Is your component using the same `PermissionStore` instance as `WorkAreaStore`?

**Comment by caesarsol** [comment]
Hi @oximer, 
I agree with @jamiewinder on the source of the problem.

I found useful to create different sub-states in a single wrapper state, for multiple benefits:
- inject a single state in every React component, and have all the sub-states you need
- access every sub-state from every other sub-state

To do so, simply instantiate every sub-state in a single globalState, and pass itself as constructor argument.

Example:
```
class GlobalState {
  permissionsState = new PermissionState(this)
  workAreaState = new WorkAreaState(this)
}
```

(I use State instead of Store, sorry!)

**Comment by mweststrate** [comment]
Closing as question seems answered
