### ISSUE TITLE
Action originalFn has been removed

### ISSUE THREAD

**Issue by danielduwaer** [mobxjs/mobx#1434]
Hello,

I have an issue regarding a recent change in the Mobx source code. To give some background, I am developing a number of utility libraries that work on Mobx. Among them is a generalized and deeply transactional version of the createViewModel (in mobx-utils). However, it has come to my attention that some metadata was removed from Mobx that would allow this, namely the original function (originalFn) which was previously stored in the action.

I need this because I need to 'copy' an existing action from an existing object A onto another object B. For this, I need the original function (which was stored under 'originalFn') of the action in A and bind it to the other object B (via originalFn.bind(B)).

@mweststrate I saw you made the change (05-03-2018), and I was wondering if you have any other way of achieving this or whether we could restore this metadata?

I am willing to submit a PR if necessary.

**Comment by mweststrate** [comment]
@danielduwaer for clarification, why can't you just rebind the action?

**Comment by Deathspike** [comment]
I am attempting to get the original function prior to `mobx.action`. I want to look at the function body, parse it, and run some code depending on what I'm seeing in the body. Doing a `.toString()` on an action-bound just returns the wrapper function from `mobx`, which is entirely useless to my purposes. I was recommended to use `originalFn`, and that's how I got here. It's gone. I have no way to access the source code of the original function now. Or is there an alternative? If not, I'd really like to see `originalFn` make its return.

**Comment by Deathspike** [comment]
I thought it might be a good idea to illustrate this a little further. I'm using TypeScript for this. Since my previous comment, I have reverted back to 3.6.2. I then wrote a function that (naively) analyzes an action function to detect cases in a switch adhering to a `Message` suffix. This is what I wrote that is dependent on `originalFn`:

```
bind(source: {receiveMessage: (message: eio.MessageType) => void}) {
  let receiveMessage = source.receiveMessage as any;
  let functionText = String(receiveMessage.isMobxAction ? receiveMessage.originalFn : receiveMessage);
  let expression = /case '([a-zA-Z]+Message)':/g;
  let match: RegExpMatchArray | null;
  while (match = expression.exec(functionText)) {
    this.on(source.receiveMessage.bind(source), match[1] as any);
  }
}
```

The specifics of the code are probably irrelevant, but the way the `receiveMessage` is declared might be interesting. I have a class that contains a class method named `receiveMessage`. In the constructor of that class, I call the earlier illustrated `bind` function. This class starts like this:

```
export class CharacterManager {
  constructor(messageQueue: eio.MessageQueue) {
    messageQueue.bind(this);
  }

  @mobx.action
  receiveMessage(message: eio.MessageType) {
    switch (message.type) {
      case 'CharacterBeginMoveMessage':
```

So the constructor call I'm doing here already has had its `receiveMessage` replaced by the `mobx` wrapper function. I tried various ways to pass the original `receiveMessage` into the `messageQueue.bind` function, but to no avail. Now, if there is a way to get the original function without splitting the `receiveMessage` into a `receiveMessageImpl` and `receiveMessageAction`, I can imagine that `originalFn` has no use. Otherwise, I see no way around it other than splitting the code into two functions here... but `mobx` is making life easier, and shouldn't make it harder.

**Comment by mweststrate** [comment]
@Deathspike parsing source code at runtime to determine behavior is something you should *really* avoid, it will be super fragile. Code minification, refactorings like extract to utility methods, nesting switch cases etc will all completely break your code. 

Instead, make the contract between MessageQueue and CharacterManager explicit by exposing a method that exposes the supported character types. And if you don't feel for repeating the names, uses constants, arrays or objects to specify them at a single place. 

But really; don't parse source code at runtime, this will totally confuse future yourself and others working on this code, breaking it at the most unexpected moments.

**Comment by Deathspike** [comment]
I don't agree with that @mweststrate. Of course, the example I illustrated above is naive, and can break down. Using an appropriate lexer (such as Esprima) avoids any such pitfalls. It will not be resillient against improper refactoring, of course, but really... what is? An improper refactor will always break an application. It's not a reason to duplicate contracts for no reason other than someone potentially breaking the code in the future. There are far more ways to do that.

That said, this isn't the only application of wanting to access the original function. Any kind of addition to the function prior to being bound may be lost as well. Nevertheless, I assume you don't want to restore the metadata for any purpose. That's a shame, really. I guess anyone that wants access to the original function will have to go for a more roundabout method then.

Out of interest, what is the reasoning behind not wanting to reintroduce this relatively mild addition?

**Comment by mweststrate** [comment]
@Deathspike there are good reasons why things like `eval` are no-go's in the javascript world, and why you shouldn't access private members even when you can technically do so. What you are doing here is worse than both of them combined; you access the implementation of a function and thereby create a contract between two classes in your application nobody will be aware of. In the future somebody will comment out one of the cases, just to discover that the app still behaves the same, and will spend a few hours debugging to figure out why his app seemingly doesn't pick up source code modifications. After that he will most certainly put that code on https://thedailywtf.com/. Solving that problem by introducing a javascript parser in your code is like using a database to prevent creating a local variable. There is a fundamental difference between breaking stuff by refactoring because you broke an existing contract, and breaking it because a contract is broken that nobody expected to be there. So really, don't do weird stuff like these when you can solve the problem by a simple lookup table or array... That all being said, it is entirely up to you. I don't really care less as long as you are not in one of my teams :). 

----

 The question why or why not to introduce things is a valid one, and the reasoning is roughly as this:

1. Will a new thing introduce a clear benefit for the majority of all users? In this case a clear No. 
2. Or does it have a benefit for a small group of users which cannot be addressed without changing Mobx? And in that case, is there a good use case that can not be solved differently. The answer to both of these questions is here again No. There is both a clear work around, and imho a really bad use case.

The argument "but it is a simple change" never holds for libraries that are used as frequently as MobX. it's api, so it requires documentation and testing. More documentation (features) adds a little overhead to any other person using the lib. It's not about whether the implementation that is simple, it is about not increasing the api surface more then needed. 

Added to that, implementation this feature is not as simple as it appears at first sight; because it doesn't incorporate flows at the moment. However, for `flow`s (which are actions as well) this problem is actually unsolvable, because the code will already wrapped by the compiler to transpile the generator function, and the source code is really not accessible.
