### ISSUE TITLE
5.x supported browser strategy

### ISSUE THREAD

**Issue by ianschmitz** [mobxjs/mobx#1436]
I'm hoping to get your take on what the future support for 4.x will look like as 5.x will drop support for IE entirely (due to the use of proxies). I figure it's best to begin thinking about this early on as I suspect a good chunk of us are stuck needing to support IE browsers (in my case IE11 is what I generally need to support as MSFT is still giving it life support unfortunately).

- Will there be a LTS schedule for those of us that need to support IE11?
- Can we expect future improvements that don't rely on proxies to be brought down to 4.x for those of us that are stuck?

Cheers!

**Comment by urugator** [comment]
My hopes are that after 5 is finished, there will be an effort to identify and move common parts into seperate package (mobx-core), so that improvements in core can be shared regardless of proxy support.
Ideally I would like to see types (object/array/map/...) and factories/decorators moved to individual packages as well, so that it's possible to assemble own API based on specific needs.    
Other improvements will most likely depend on user needs, or rather their willingness to contribute :) I wouldn't expect something like granted LTS support, but I may be wrong...

**Comment by mweststrate** [comment]
@ianschmitz yes, we plan to support 4.x for the long term, backporting bugfixes. And features (at least upon request) as well. Probably MobX 5 will be actually released as version 15, to allow future breaking changes for the ES5 supporting version of MobX.
