### ISSUE TITLE
isComputingDerivation is exported as `_isComputingDerivation`

### ISSUE THREAD

**Issue by IjzerenHein** [mobxjs/mobx#1437]
In the MobX 3->4 migration guide, it mentions that `extras.isComputingDerivation` was renamed to `isComputingDerivation`. However, this export does not exist, and instead `_isComputingDerivation` is exported.

Is `_isComputingDerivation` the correct one and should the migration guide be fixed?

**Comment by mweststrate** [comment]
@IjzerenHein `_isComputingDerivation` is correct indeed, and is used as such by mobx-react. The `_` denotes it is undocumented api, because we ideally would have a neater abstraction for that. Which makes me wonder, where does Firestorter use it for?

Will fix the migration guide

**Comment by IjzerenHein** [comment]
@mweststrate Awesome!

I didn't know it was considered an undocumented API, otherwise I would have looked for alternatives. Firestorter uses it to extend an observable with life-cycle methods, in order to detect whether the observable is being observed or not. It's a small piece of code that you can [find here](https://github.com/IjzerenHein/firestorter/blob/master/src/enhancedObservable.js).
Perhaps there is a better way to do this, but I don't know how.

**Comment by mweststrate** [comment]
@IjzerenHein sorry, forgot to respond! In MobX 4 there are two interesting changes in this regard: 

1. There are now the `onBecomeObserved` and `onBecomeUnobserved` hooks (see the release blog post as well), so that you can be notified when *any* observable is (no longer) being observed
2. `reportObserved()` actually returns a `boolean` if called to indicate whether it was used from a reactive context. So you could actually just inspect that `res` field you have there :)

**Comment by IjzerenHein** [comment]
@mweststrate Alright awesome, thanks so much for the explanation! Will take a look at the blog post to see how I can do it better. Cheers!
