### ISSUE TITLE
What different thing happened with @observable decorator between the version of 4.x and 3.x?

### ISSUE THREAD

**Issue by acrazing** [mobxjs/mobx#1493]
I found it(version 4.1.1) changed something about the property's descriptor, and some library could not working correctly. See the case: https://github.com/acrazing/mobx-sync/blob/master/src/ignore.spec.ts.

A simplified example:

```typescript
import { observable } from 'mobx'

export function nonenumerable(p: any, key: string, desc?: PropertyDescriptor): any {
  desc = desc || Object.getOwnPropertyDescriptor(p, key)
  let pValue: any
  if (desc) {
    desc.enumerable = false
    const { get, set } = desc
    pValue = desc.value
    desc.set = function (value) {
      set && set.call(this, value)
      if (this === p) {
        pValue = value
        return
      }
      const instDesc = Object.getOwnPropertyDescriptor(this, key)
      if (instDesc) {
        instDesc.enumerable = false
        Object.defineProperty(this, key, instDesc)
      } else {
        Object.defineProperty(this, key, {
          configurable: true,
          enumerable: false,
          writable: true,
          value: value,
        })
      }
    }
    desc.get = function () {
      return get ? get.call(this) : pValue
    }
    return desc
  }
  return {
    enumerable: false,
    configurable: true,
    set(value: any) {
      if (this === p) {
        pValue = value
        return
      }
      Object.defineProperty(this, key, {
        enumerable: false,
        configurable: true,
        writable: true,
        value: value,
      })
    },
    get() {
      return pValue
    },
  }
}

class N1 {
	@nonenumerable @observable ignored = 'ignored'
	@observable normal = 'normal'
}

class N2 {
	@observable normal = 'normal'
	@nonenumerable @observable ignored = 'ignored'
}

const n1 = new N1
const n2 = new N2

console.log('n1.ignored', Object.getOwnPropertyDescriptor(n1, 'ignored'))
console.log('n2.ignored', Object.getOwnPropertyDescriptor(n2, 'ignored'))
```

The run result is:

```text
n1.ignored { get: [Function: get],
  set: [Function: set],
  enumerable: false,
  configurable: true }
n2.ignored { get: [Function: get],
  set: [Function: set],
  enumerable: true,
  configurable: true }
```

You can see the js playground at: https://runkit.com/acrazing/mobx-observable-updated-property-descriptor

**Comment by acrazing** [comment]
The difference between `N1` and `N2` is just changed the order of the two properties, and the result of the instances' property `ignore`s descriptor is different: the `enumerable` is `true` on `n2` and `false` on `n1`.

**Comment by acrazing** [comment]
The expected result is both of the two classes' property `ignored` should be `nonenumerable`.

**Comment by mweststrate** [comment]
@acrazing the problem is that decorators like these are currently not composable (they don't compose neatly because like your decorator, `@observable` also puts itself on the prototype and then copies itself on the instance on the first read. As you can imagine, if that happens twice it because highly suspecticable to bugs. After all, since these properties rewrite themselves, causing the original descriptor to become 'invisible' for the instance. 

This problem is currently not consistently solvable until the new decorators proposal (that it worked before was basically a bug in itself, that manifested itself in different scenerios which now have been addressed). 

As work around you could try to redefine the same property in the constructor, after reading it once (so that it has put itself on the instance)

**Comment by acrazing** [comment]
Well, I found it's caused by this function: <https://github.com/mobxjs/mobx/blob/4b44c324b9947c042391e5c7c1060fda14866d9a/src/utils/decorators2.ts#L52-L62>. It's called for all the properties decorated by `@observable`, and initializes those properties with internal property descriptor, which lead to the real descriptor to be `invisible`.
But, why do we need to do this (initialize all the properties when initialize the first property which is `@observable`)?

**Comment by mweststrate** [comment]
@acrazing `@observable` decorators the class (the prototype), but not the instance itself. So upon first access (read or write), this code actually takes care of creating a new property descriptor on the _instance_. Otherwise the instance doesn't own the property, which leads to unexpected behavior like properties not showing up in `for .. in` loops etc.

```
class X {
  @observable title // defined on the prootype
}

const x = new X()

x.title //upon first read write, the property `title` is introduced on `x` (not `X`!). 
```

The reason we can not do that earlier, like, in the constructor, is due to limitations in the current babel implementation of decorators. Once they support the stage 2 implementation of the proposal, we can fix this problem
