### ISSUE TITLE
Observable passed as prop not always causes re-render

### ISSUE THREAD

**Issue by dahel** [mobxjs/mobx#1505]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

2. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

MobX version: 3.3.1

I encountered inconsistent behaviour related to triggering re-render after observable change.
I have login form and separated action button which triggers submit action.
When submit action is triggered, `inProgress` observable property is set to true - this property is used by ActionButton to disable it (passed as prop).
After form submission success (with ajax) `inProgress` is set to true, and ActionButton should not by disabled anymore, but it not re-renders after `inProgress` set to true:
```
// Login.js
export class Login extends Component {
    render() {
        return (
            <Formik
                initialValues={{
                    email: '',
                    password: ''
                }}
                onSubmit={this.handleSubmit}
                render={props => {
                    return (
                        <div>
                            <ActionButton onClick={props.submitForm} disabled={this.props.store.inProgress}>
                                    Save
                            </ActionButton>
                            <LoginForm {...props} />
                        </div>
                    )
                }}
            />
        );
    }

    handleSubmit(credentials) {
        this.props.store.login(credentials)
    }
}

export default inject('store')(observer(Login));
```

```
// store.js

import {
    observable,
    action,
    decorate
} from 'mobx';

import api from '../api/auth';


class Store {
    inProgress = false;

    login(credentials) {
        this.setProgressState(true);

        return api
            .login(credentials)
            .finally(() => this.setProgressState(false));
    }

    setProgressState(state) {
        this.inProgress = state;
    }
}

decorate(Store, {
    inProgress: observable,
    login: action,
    setProgressState: action
});

export default new Store();
```

What's interesting, when I extract variables from store in the top of render method, it works (ActionButton is re-rendered)
```
export class Login extends Component {
    render() {
		const { inProgress } = this.props.store // this line causes re-render of ActionButton

        return (
            <Formik
                initialValues={{
                    email: '',
                    password: ''
                }}
                onSubmit={this.handleSubmit}
                render={props => {
                    return (
                        <div>
                            <ActionButton onClick={props.submitForm} disabled={inProgress}>
                                    Save
                            </ActionButton>
                            <LoginForm {...props} />
                        </div>
                    )
                }}
            />
        );
    }

    handleSubmit(credentials) {
        this.props.store.login(credentials)
    }
}

export default inject('store')(observer(Login));
```

Can someone demystify what actually is happening here?

**Comment by mweststrate** [comment]
The behavior you see is correct. Remember that observables should always be rendered by observers? 

In your first example you are not using the data in your Login component, you just create a closure that will reference it _in the future_ and pass it on to the formik component. but that rendering is part of the Formik component, not part of the Login component. Since the Formik component is not an observer, it will not be tracking changes of stuff you use in the provided render callback. The render callback seems _syntactically_ to be part of your Login component, but for all practical reasons, like rendering, lifecycle events etc, it is part of the Formik component.

In the second example the render of `Login` depends on the `inProgress` attribute. So if it changes, `Login` will rerender, create a _new_ closure for the render callback of Formik, and that way cause the Formik component to render as well.

There are 3 ways to address this

1. Like you did, dereference the observables in the `Login` component
2. Extract the render callback into a separate component and mark it with `observer`
3. Wrap the render callback in an `<Observer>` section: `render={props => <Observer>{() => (<div>...</div>)}</Observer>}`

**Comment by dahel** [comment]
Thank You, now it's totally clear to me :smiley: 
I think i will stick to third solution.
