### ISSUE TITLE
Don't throw when using the object api on non observable objects

### ISSUE THREAD

**Issue by daedalus28** [mobxjs/mobx#1549]
I have a few cases of components that optionally support observable objects to enable reactivity, but can be plain objects if the dev knows they're going to be static. The new object api has allowed me to support properties that might be added or become observable later, which is great - but using that API means I have to explicitly check if it's an observable first. I've created a utility to do this locally which I was going to propose for mobx-utils, but it seems like it would be much simpler if mobx itself supported it. Here's what I have locally:

```js
import _ from 'lodash'
import { isObservable, get as mGet, has as mHas } from 'mobx'

export let get = (obj, path) => (isObservable(obj) ? mGet : _.get)(obj, path)
export let has = (obj, path) => (isObservable(obj) ? mHas : _.has)(obj, path)
```

The exception is already disabled if node env is production: https://github.com/mobxjs/mobx/blob/master/src/api/object-api.ts#L143

In my unit tests, that's not the case so my component works but the unit tests fail. This seems like it could be solved by either removing the check completely, adding a param to opt out of the error message, or something similar to mobx's "strict" setting for the object API that could work for all of the methods.

**Comment by mweststrate** [comment]
I see why this would benefit your use case. On the other hand, this will also in cases cause to more lately detect that there assumptions are incorrect, when they assume something to be an observable when it isn't. 

Since mobx is not a general purpose object manipulation library, I'd rather keep the behavior as is. Even though observable objects have the same api as non-observable ones; they are fundamentally different things and I rather have that reflected in the api.

So I recommend to just keep the work around you have now, which is clear in all cases.

**Comment by mweststrate** [comment]
No I think that will be confusing, the object-api itself might end up in
utils once Object.entries and such are widely available

Op di 29 mei 2018 om 18:12 schreef Samuel Greene <notifications@github.com>:
