### ISSUE TITLE
10k TodoMVC example

### ISSUE THREAD

**Issue by Freak613** [mobxjs/mobx#1570]
Hi, remember there was 10k TodoMVC example that has been posted 2yrs ago?
https://github.com/mweststrate/mobx-todomvc

I've tried to update it to React@16 and MobX@4 to see how it works now.
https://github.com/Freak613/mobx-todomvc

However, the problem is that app crashes with OutOfMemory.
As I understand example is pretty simple and doesn't conflicts with latest MobX updates(app updated from MobX@2 to MobX@4)

I was able to test it with 1000 todo items. And it shows to consume significant amount of memory (700MB on my machine)
So I think the main problem is that it tries to recursively reactivate whole state, containing tricky 'other' field that is reference to previous item.
If I remove 'other' field app starts okay. But it broke required functionality(displaying 'Yes' on next item)

Am I doing something wrong?
Or it's not possible anymore with MobX@4?

**Comment by urugator** [comment]
The example is incompatible with Mobx > 3. Mobx 2 made objects observable in place (maintained object references), while MobX > 3 creates copy first ... so as you suggests each `other` contains own deep observable copy, instead of a referecne to patched item.
Mobx 2 behavior was inconsitent (it patched object, but cloned arrays/map) and there were some other problems related to patching existing objects.

**Comment by Freak613** [comment]
:(
