### ISSUE TITLE
In future releases, mobx can support hot reload of asynchronous routes ? 

### ISSUE THREAD

**Issue by simmons8616** [mobxjs/mobx#1618]
In future releases, mobx can support hot reload of asynchronous routes ? chunks cannot be updated after changes with react-hot-loader, react-loadable.

**Comment by mweststrate** [comment]
As long as you guarantee MobX is loaded only once, things should keep
working in general, but since 'hot reload', and 'chunks' are quite general
concepts which can mean many different things in practice, can't say
anything useful about this. Of course if it turns out something can be done
on the MobX side of things after investigation, PRs are always welcome

Op vr 29 jun. 2018 om 13:27 schreef simmons8616 <notifications@github.com>:
