### ISSUE TITLE
Computed getters do not remain enumerable

### ISSUE THREAD

**Issue by BrendanAnnable** [mobxjs/mobx#1643]
It seems object properties become `enumerable: false` after being auto-computed.

e.g.

```ts
const o1 = { get foo() { return 'bar' } };
const o2 = mobx.observable(o1);
{...o1} // { foo: 'bar' }
{...o2} // {}
```

I would expect the last two lines to output identically.

MobX 5.0.3 on Chrome 67 OSX.

I would be willing to attempt a PR if confirmed as a bug. I do suspect someone more familiar with the code could fix it quicker than I.

Searched keywords: enumerable, spread, computed missing properties

**Comment by urugator** [comment]
AFAIK it's intentional and mainly it's useful for simple serialization (not sure if that's the reason though). I mentioned this in #1334. 
If the getter in original object doesn't represent *derivation*, but a *value* you could do `mobx.observable({...o1})`. Also you can still define normal (non-computed) getter.

@mweststrate I have noticed that 
```javascript
const o = observable({
  get a() {
    return "a";
  }
}, {
  a: observable.ref,
})
```
defines observable prop `a`, but keeps it's value `undefined`, shoudn't it "fetch" the value or throw?

**Comment by mweststrate** [comment]
@BrendanAnnable computed properties are always non-enumerable by design indeed. If you search a bit I'm pretty sure you can find pro's and con's of either approach. As long as there is no really compelling that outweights the cons I see no reason to change it :)

@urugator yep I tink that is a bug, it should throw, consider filing that separately?
