### ISSUE TITLE
How to force autorun skip some value change?

### ISSUE THREAD

**Issue by DuckMingBrother** [mobxjs/mobx#1657]
I have two observable variable "foo" and "bar" in React Component props,
either variable change will trigger Component re-render, work fine.
But I also have a autorun, for example:
`autorun(() => if (foo) { console.log(foo + bar) });` 

Can autorun only trigger when foo's value change?
Or I should use ComponentWillReceiveProps instead of autorun?
Thanks.

**Comment by DuckMingBrother** [comment]
ps. foo is an object, I can't keep old value and compare with new value...

**Comment by DuckMingBrother** [comment]
Thank you!!! That what I want.
But I'm confused why https://mobx.js.org/ can't find untracked method...

**Comment by jamiewinder** [comment]
It is likely an oversight. It is arguably a bit of a weird bodge too (though I do still use it on occasion).

An alternative is to use [`reaction`](https://mobx.js.org/refguide/reaction.html) which makes it a bit more explicit about what observables you're interested in (because you collect them in the first function argument) and which you're not (because you use them in the second function argument).

**Comment by DuckMingBrother** [comment]
Thanks again!
I will close this issue.
