### ISSUE TITLE
[mobx 5] RangeError: Maximum call stack size exceeded - Chartjs2 data array

### ISSUE THREAD

**Issue by Ryner01** [mobxjs/mobx#1673]
Hello,

I am using mobx 5 together with `react` and `chartjs` but there seems to be issue with passing mobx 5 proxy array into chartjs library. I get `RangeError: Maximum call stack size exceeded` error.

To be more precise it only crashes after **second** render. (You can remove last line in example to see for yourself)

Bellow is the replicated example with error in question. I am sure that my code is at fault but I am not sure where is the problem. Since mobx is already using proxies I thought that array passing is a solved problem.

Thanks for the help! :)

I have a:

2. [x] Issue:
  * [] **Provide error messages including stacktrace**
     I can provide if needed but stack trace will probably be very similar to one bellow in example. Since the error is the same.

  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
     Here it is: https://codesandbox.io/s/lrpojjmn9z
    * [x] **Elaborate on your issue. What behavior did you expect?**

     I expected chartjs to render data from mobx array properly.

  * [x] **State the versions of MobX and relevant libraries. Which browser / node / ... version?**
 
* [x] **Did you check this issue wasn't filed before?**
- mobx5
- All other dependencies are in the example above (which also does not work)

Also this maybe a bit offtopic but if I do `appState.prediction.to_date.push(// new data)` it does not work. Maybe I just don't understand how mobx 5 arrays work? ¯\_(ツ)_/¯

**Comment by urugator** [comment]
Not sure what the actual problem is, but passing non-observable copy instead of actual observable array seems to do the trick:
https://codesandbox.io/s/k3pqn73zm5
At this point `appState.prediction.to_date.push(// new data)` should also work, because the content of array was accessed (via `slice`) inside `@observer`

**Comment by domehead100** [comment]
I've had a problem with forEach on observable arrays where in the loop the item never increments so the loop runs until the stack overflows, or it could be a case of library code using something like Array.prototype.forEach(<observable array>).  Never really dug in since .slice() took care of the issue.

Just reinforces that using .slice() is seriously a best practice when passing observable arrays to third party library code.

**Comment by Ryner01** [comment]
Ok thanks guys.

I will follow the docs then and use slice everywhere :) 

Closing the issue since it's resolved.
