### ISSUE TITLE
Cyclic references

### ISSUE THREAD

**Issue by reinaldoarrosi** [mobxjs/mobx#1675]
I was using mobx 2.*, where cyclic reference were properly converted to observables, and now that I upgraded to 4.* this is no the case anymore.

I'm aware of #1032, but what I'm looking for is "guidance" (or a hint of where to look) so that I can patch mobx during runtime, so that it correctly handles cyclic references.

I'm also aware that patching things is very brittle, but right now is the only way I can solve my problems after migrating to 4.*

Is this even possible?

Thanks!

**Comment by mweststrate** [comment]
This sounds like you deeply convert a data structure after creating cyclic references, in other words, quite late. Is there a reason why you can't make the data observable before introducing the cycles? Can you elaborate your use case? usually this is a sign something else is set up wrong, for example that modifiers should have been used.

**Comment by mweststrate** [comment]
In that case the same utility should suffice? https://github.com/mobxjs/mobx/issues/1032#issuecomment-307321446

**Comment by mweststrate** [comment]
Sorry for late follow up, but since you are receiving the data from a rest endpoint, there should be never cycles in the first place? Or are you resolving references automatically? In that case, isn't the problem avoid by _first_ turning the data into observables and _then_ replacing any primitives with a reference to the relevant observable data?

* I think you could create a decorator, that uses the `intercept` api, to run your `cyclicObservable` code. 
* Alternatively, but that would probably be a little trickier, you could update the `enhancer` of your properties. The `enhancer` is the function that takes care of the value conversion. It lives here: `yourObject[$mobx].values["thePropertyName"].enhancer`
* Maybe, to simplify that process, we could actually expose [`createDecoratorForEnhancer`](https://github.com/mobxjs/mobx/blob/857621c6bfbdc01f18db318897d2e070a3ddfaab/src/api/observabledecorator.ts#L15), so that you can easily expose your own decorator with custom conversion. See https://github.com/mobxjs/mobx/blob/857621c6bfbdc01f18db318897d2e070a3ddfaab/src/api/observable.ts#L58-L61 and

**Comment by mweststrate** [comment]
Closing for now, as some work-arounds are know
