### ISSUE TITLE
Can not observe object of type

### ISSUE THREAD

**Issue by tnguyen-lh** [mobxjs/mobx#1700]
In my store I have
`@observable data = {itemCount: 0};`
If I change from the component page, it is reflect the store value ok, however if I change it to the Order type 
`@observable data = new Order({itemCount: 0});
`
IT IS NOT WORKING ANYMORE

```
export class Order extends Entity{
	itemCount: number = 0;
}
```

**Comment by mweststrate** [comment]
It is because `@observable` will automatically recurse into _plain_ data
structures and make them observable, but it won't recurse into class
instances, so there you should declare itemCount as `@observable itemCount`
to make it observable

Op ma 27 aug. 2018 om 14:56 schreef Tom Nguyen <notifications@github.com>:

**Comment by tnguyen-lh** [comment]
Thanks,  it is working fine with 
```
export class Order extends Entity{
	@observable itemCount: number = 0;
}
```
