### ISSUE TITLE
Question: Is there a way to detect misuse of objects MobX has cloned?

### ISSUE THREAD

**Issue by smikula** [mobxjs/mobx#1744]
The scenario I'm talking about is this:

```typescript
let myMap = new ObservableMap();
let myObject = { foo: 1, bar: 2 };
myMap.add('key', myObject);
myObject.foo = 3;
```

Because MobX creates a clone of `myObject`, the instance I'm updating is not the instance that is stored in the map.  If there were reactions observing the contents of the map, they would not react to my setting of `foo`.

For some context: I work on a very large codebase (100+ developers) that uses MobX v2 extensively for state management.  In 2.x the above code works fine because MobX patches the object in-place.  I'm finally biting the bullet and trying to update to a more current version of MobX, and I'm finding that the above problem happens pretty frequently—and in much subtler ways than my example above.  But my real fear is all the places I *don't* find, because this doesn't necessarily manifest as an error, just as some possibly obscure piece of functionality that doesn't work as expected.  And even if I can fix all the current instances, what is to stop a naive developer from introducing this problem again?

So my question is, is there any guidance or tooling to help detect or avoid this problem?

One possibility I've considered is, when creating an observable clone of an object, doing the below to the original non-observable instance.  (I've actually hacked this into MobX and it's helped me root out a lot of issues so far.

```typescript
Object.keys(originalObject).forEach(function(key) {
    Object.defineProperty(originalObject, key, {
        enumerable: true,
        get: function() { throw new Error("Don't use this object!"); },
        set: function() { throw new Error("Don't use this object!"); },
    });
});
```

Are there any other recommendations?  Would it make sense to have some sort of dev-mode option to do what I'm suggesting here?

**Comment by mweststrate** [comment]
Short on time, so a bit short answer:

* The best practice is to not keep references around to things you are going to assign to the state (e.g.; data coming in from a service, just assign it to your state but don't pass it anywhere else
* For migration: just avoid using `@observable` in it's generic form anywhere might help; always specify the modifier, by default use `@observable.ref`, then if you discover that the contents had to be made observable (for example because it wasn't already) as well use `@observable.shallow` or `@observable.deep`

**Comment by smikula** [comment]
What you're suggesting as best practices make sense, and if you've followed them from the start then I'm sure this upgrade is pretty painless.  After working through this upgrade for several weeks now, though, I can say that my codebase has some very different patterns.  (We use [SatchelJs](https://github.com/microsoft/satcheljs) and depend extensively on the "magic" of objects being converted to observables automatically when being assigned into the state tree, so you won't find `@observable` in our code at all.)  To clean up all our code would take literally months.

MobX is presented as very unopinionated about how users should create and update state, but it seems like this mechanism for cloning objects actually *does* impose some particular assumptions ex post facto.  I'm pretty late to the party, but I'll just offer it as a bit of feedback in retrospect that this is a painful change for at least one consumer.

How feasible would it be to offer some sort of compatibility mode?  E.g. I've been playing around with monkey-patching `observable.object` to patch up the old, stale object to act as a proxy to the newly cloned observable object.  It's hacky, but it has gotten my app up and running.  Is that something you might consider officially supporting?

**Comment by mweststrate** [comment]
@smikula the reason it changed is because the old behavior was completely inconsistent; arrays and maps were always cloned, objects never, and proxies in the future would be referentially non equal as well. 

Unopioninated simply means: we tried to avoid affecting every design decision in your code base, it doesn't mean "we won't ever change the semantics of anything". In that case development should have simply stopped two years ago.

I think your original solution is pretty neat, because it emphasizes the problem; handing out references to your objects left and right, before they are actually part of the state. As said that approach would fail for arrays and maps in mobx 2 as well, just seems that you didn't bump into it.

The solution that you have could be slightly improved I guess by having the getter printing a warning, but returning the value from the new object, rather than throwing, so that you can find the cases without breaking stuff.
---

That all being said, the `observable(.deep|.shallow)`  etch behavior is defined through enhancers. 

The default one can be found [here](https://github.com/mobxjs/mobx/blob/f944b5413f2f4b9de89e00e7de1ddde2a178e19d/src/types/modifiers.ts#L17), so you could create your own custom enhancer to either achieve the MobX 2 behavior, or to automatically perform the original object patching, and set up forwards and warnings (or monitoring alerts or whatever). 

To achieve the old behavior, your enhancer should look like: 

```javascript
export function classicEnhancer(v, _, name) {
    // it is an observable already, done
    if (isObservable(v)) return v
    if (Array.isArray(v)) return observable.array(v, { name, defaultDecorator: classicDecorator })
    if (isPlainObject(v)) {
       // old behavior
       extendObservable(v, v, {}, { name, defaultDecorator: classicDecorator })
       return v
       // OR, new behavior with forwards: 
       const r = observable.object(v, undefined, { name, defaultDecorator: classicDecorator })
       setupForwards(v, r)
       return r
    }
    if (isES6Map(v)) return observable.map(v, { name, defaultDecorator: classicDecorator })
    return v
}

const classicDecorator = createDecoratorForEnhancer(classicEnhancer)

// usage:
@classicDecorator mystuf = x
```

I think the only thing that would break with the above is that `createDecoratorForEnhancer` is probably not publicly exposed, but if you want to expose it through a PR that is fine to me

**Comment by smikula** [comment]
Thanks, @mweststrate, that's really helpful.  I'll try that out and hopefully have a PR for you in a few days.  Despite the hiccups in this upgrade, MobX has been great for my project — I really appreciate all the work you've put into it!
