### ISSUE TITLE
Cannot find module 'babel-preset-react-native'

### ISSUE THREAD

**Issue by arhmnsh** [mobxjs/mobx#1782]
I have followed [this tutorial](https://medium.com/react-native-training/react-native-with-mobx-getting-started-ba7e18d8ff44) to implement MobX in my React Native (v"0.57.1") project.

I am getting this error when I run my app

`Cannot find module 'babel-preset-react-native'`

As suggested in that article, I have installed `@babel/plugin-proposal-decorators` and set up the .babelrc file accordingly.

Here is the screenshot of the error and my config.

<img width="1347" alt="screen shot 2018-10-22 at 6 40 37 am" src="https://user-images.githubusercontent.com/1363724/47277191-3426d080-d5c6-11e8-9d1a-26fcc627ebef.png">

**Comment by mweststrate** [comment]
The issue seems unrelated to MobX, but you might try the example configuration shown here: https://github.com/oblador/react-native-vector-icons/issues/801#issuecomment-409268915, or ask the blog author to update his blog post?

The clue is that the `@babel/plugin-proposal-decorator` plugin should be installed, as first plugin and in `legacy` mode, and beyond that the standard React Native setup / process work. So I think you can just generate a vanilla RN project, and then apply the instructions shown here: https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset

N.B., for setup simplicity I recommend to use `mobx@4` and not latest if you want to target Android

**Comment by mweststrate** [comment]
Closing for lack of further information, and issue sems to be unrelated to mobx
