### ISSUE TITLE
React shouldComponentUpdate usage

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx#1787]
This is a question.  Would you agree that React/MobX applications should never override the shouldComponentUpdate method?

Also, the just introduced React.memo HOC should not be used as well?

https://reactjs.org/docs/react-api.html#reactmemo

**Comment by ItamarShDev** [comment]
Are you asking for the MobX owners own idea, or the library's implementation?

**Comment by mweststrate** [comment]
@AjaxSolutions I would personally agree with both statements yes, for the first, because it kinda defeats the point of observer components. If you need `sCU` (for non mobx stuff), you should probably break up your component into smaller components or use `Observer` sections rather than `observer` sections.

For memo, no need either, as `observer` already has similar behavior.
