### ISSUE TITLE
Is there a way to not use actions?

### ISSUE THREAD

**Issue by Dairnon** [mobxjs/mobx#1806]
1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

To start off I apologize for this question being so long, I really don't know any better way to ask this, so I ask that you please forgive me for my questions length.

I'm using mobx for creating a dynamic in game map editor. The ability for UI to observe object changes was a no brainer for me. I'm also having maps and map instances observe changes to their data, and updated off that, and this all works really well. 

My question comes in with the requirement of actions. (at least the recommendation of it, as well as its restriction in some extensions like mst) 

Some of my objects like npc's or the player directly modify the data for input or responses to events. (The player can walk around through the map while your editing in realtime, as can npc's follow move routes on their own.) The easy solution would probably be bind action to all of these objects movement.

However I only wanted to use mobx for the editor side. Since I only need any of this observable stuff while working on the actual maps and instances in edit mode. I didn't want mobx running at all while not in edit mode. I was going to achieve this by converting plane json versions of all my data into observable objects when edit mode is turned on, manipulate them, and then save that data out to plane stuff again once exiting edit mode. Also I didn't want to ship my game with the editor (so the game isn't dependent on mobx/react) 

I guess my real question is... is mobx even right for my case? Of creating an observable realtime editor for UI and assets to react to, as well as for using undo/redo? 

Considering the starting problem of a observable player character moving around within this realtime editor. If that character is taking in direct input by the player, that'll go against whats recommended with using actions (especially with mst). Using actions however would go against me not wanting mobx outside the editor tho. 

I'd appreciate some advice as to how to tackle this and thank you for reading my question.

**Comment by urugator** [comment]
You can introduce your own actions/dispatcher, so that you can later intercept any call with whatever logic you want (like mobx action). Just to get the idea:
```javascript
function dispatch(fn) {
  if (isEditMode) {
    Mobx.runInAction(fn);
  } else {
    fn();
  }
}

function onKeyUp() {
  dispatch(moveUp);
}
```

I think you could also use own observable/action etc, which would simply be a noop outside edit mode. 

> I guess my real question is... is mobx even right for my case?

Mobx is about dependency tracking. If the resolution of what should be updated isn't complicated, you won't benefit from mobx that much.
For example calling `updateUI()` at the end of each state update can be totally sufficient (and if you use immutability, you can bail out certain updates based on equality).

**Comment by Dairnon** [comment]
Thank you so much for your response!

I use mobx for updating UI, but also for having objects in the map listen to changes they have. If I select a in map object and change its color, then the UI , and the object selected will update.

It seems like just doing something like updateUI may be better from the sounds of it. I use react so using mobx for triggering a reaction seemed really easy, I wasn't sure of a better way to trigger a reaction beyond that. I needed a way to force my UI to update based on info passed in from the editor.

> (and if you use immutability, you can bail out certain updates based on equality).

I don't quite understand what you mean by this.

**Comment by urugator** [comment]
> I don't quite understand what you mean by this.

It's described here: 
https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data
and here:
https://redux.js.org/faq/immutabledata#why-is-immutability-required-by-redux
the principle is same.

**Comment by Dairnon** [comment]
Oh okay that's interesting. I think my problem is that using stuff like spread destroys my references to objects. So I guess I do need some mutable properties. (I have stuff like selecting an array of objects, which I can then manipulate with a react properties window)

I can't find a way update my react data beyond setting my state to the store I use, or using mobx. 

I could maybe try having an observable designed just for updating (and make different ones for each specific part of the store) or (do the same thing but for state instead passed down)

That way I don't need to have all my data be mobx data.

I guess my last question is just, what do you suggest? Does my use case really seem like its worth while sticking entirely with mobx? Should I use my mobx work around? Or just drop mobx and set my store to react state.

I really loved mobx for how easy it helped me update react UI data, but I'm worried it's gonna cause me trouble considering how often I switch out data and my need for it to only exist for the editor.

Again thank you for your advice.

**Comment by urugator** [comment]
> I think my problem is that using stuff like spread destroys my references to objects.

Yes it requires to model state in a particular way. However it's quite hard to support unde/redo/save/load with a state encapsulated in "normal" objects of an arbitrary complexity.     
So the idea is to make state a first class citizen and keep it very dumb (so serialize/replace/testing becomes trivial), at the cost of making updates a bit more complicated.
However there may be some technical or performance concerns (some of them possibly solvable with libs like immutablejs).

Nevertheless the idea is also applicable to observables ... if you keep state simple and not part of your "rich models", your game doesn't have to know it's actually observable:
```javascript
let gameState = {};

init() {
  if (isEditorAvailable) {
    gameState = observable(gameState);
  }
}
function moveUp(gameState) {
  gameState.player.position.y += 1; // state is mutable
}
onKeyUp() {
  dispatch(moveUp);
}
serialize() {
  return mobx.toJSON(gameState);
}
createSnapshot() {
  snapshots.push(serialize());
}
```

> what do you suggest?

It's hard to make any conclusions without knowing how complex the UI is, how rapid UI updates can be, how the game itselfs is designed (realtime/turn based..?), how the game is rendered (html/canvas)... and ultimately you still won't know until you put it to test.
You may not even need react or it may be inappropriate.
I would suggest to try to keep it as simple as possible. It may not be the case, but it seems like you want to use a tool just because you're familiar with it, which may be a proper motivation sometimes (as it can save a lot of money), but it also smells if you're anticipating troubles from the get-go.

**Comment by Dairnon** [comment]
I chose react mainly for the modular components. Being able to break my UI down into smaller sections helped a lot. I chose mobx because I have a manager that handles all the editors actions. my mobx store is used to allow for multiple react editor windows (or elements) monitor changes. I make changes a lot, as I select many different objects, translate, re-color, re-size, delete, ect...

I wasn't sure of an easier way to handle UI beyond react, and since react was so easy its why I chose it as a direction to go. 

I also chose mobx over feeding all my store data into the state store because I didn't wanna have to send my data into each children for every UI component (I have many.) 

I'd like to think that my decision to use mobx made sense, however I did end up finding some issues with it as a direction to go.

**Comment by urugator** [comment]
> the want for an undo/redo

Not sure how Mobx will help you with that.

> Is it okay to not set actions to strict mode and not use them all the time?

Without action, each mutation (like assigment) will immediately trigger relevant reactions - potentially re-render all relevant components.
If you don't use reactions, but `observer` exclusively, you could achieve similar behavior by wrapping the logic in `ReactDOM.unstable_batchedUpdates` instead of `action` (quess not very helpful due to a reactdom dependency).
However If you want to use mobx, I think the easiest way is to really just export own `action/runInAction`, which runs the code conditionally in action if mobx is available. The same can be done for `observable/extendObservable`.
Or you could use babel to strip all `@action/@observable` for a build without editor (there is already a [plugin](https://github.com/elierotenberg/babel-plugin-strip-decorator) for that).

> Does it still make sense for me to use mobx and react?

React is fine if it's fast enough for your use case. Eg running DOM diff over hundreds/thousands of DOM nodes representing map entities won't perform very well I suppose. It also isn't suitable for realtime apps where everything is updating all the time.

**Comment by Dairnon** [comment]
> Eg running DOM diff over hundreds/thousands of DOM nodes representing map entities

Well I don't actually use react for the game itself, only UI for the editor. All rendering is handled by the PIXIJS library. 

I just want mobx/react for the editor only to make things easier to handle.

>  I think the easiest way is to really just export own action/runInAction

Do you mean just import and use that part of mobx?

**Comment by urugator** [comment]
> Do you mean just import and use that part of mobx?

```javascript
let Mobx;
try {
  Mobx = require('mobx'); 
} catch {} 
  
module.exports = function action(fn) {  
  if (Mobx) {
    return Mobx.action(fn);
  } else {
    return fn;
  }
}
// For decorator/name/bound support check:
// https://github.com/mobxjs/mobx/blob/master/src/api/action.ts#L52
```

**Comment by Dairnon** [comment]
Thank you, and I appreciate your amazing help!
