### ISSUE TITLE
Reduce bloated decorator code

### ISSUE THREAD

**Issue by marialovesbeans** [mobxjs/mobx#1821]
Hi guys, i would like to reduce the boilerplate code to minimum when using a mobx store. 

In ESNext, i can mark fields as `@observable`, `@computed`, and `@action`. But when there are a large amount of fields in a class, I have to repeat `@decorator` keyword for **each of the field**, which looks **over-bloated**.

In ES5, I can use `decorate(SomeClass, { field1: observable, field2: computed, field3: action, ...etc });` Then again, if I have a lot of a lot fields in a class, I have to write all these properties again in `decorate()` function, which is a lot of boilerplate code.

So, I'm trying to come up with a solution to NOT write, or **write minimum code,** to attach the correct `mobx decorator` to fields. Something like:

```js
// userstore.js
class UserStore {
    a = 1;
    get b(){ return this.a + 1; }
    c(){
        a += 1;
    }
}
// Now, instead of doing....
decorate(UserStore, { a: observable, b: computed, c: action });

// I have a function that automagically applies the proper decorator
// on each field, something like...
// - if getter, use @computed
// - if function, use @action
// - else, use @observable
magicDecorate(UserStore);

export default UserStore;
```
Is there any way to achieve this? Or can I implement some kind of parent class that this `mobx store` can inherit on, i.e., `class UserStore extends MagicBaseStore`, that automagically does this binding for me? 

Thank you so much!

**Comment by marialovesbeans** [comment]
Hi @urugator , thanks for the response. I checked out [mobx-decorators](https://github.com/farwayer/mobx-decorators), their @allObservable seem to work. However, it fails when I have a constructor within a class.

For example:

```javascript
import { observable, computed, action, decorate, autorun, extendObservable, reaction } from "mobx";
import { allObservable } from "mobx-decorators";

// define the class
class User {
  // [PROBLEM] code inside the constructor is NEVER called
  constructor() {
    reaction(() => this.a, a => console.log("this.a is changed"));
  }
  // observable
  a = 1;
  // computed
  get b() { return this.a + 1; }  
  // action
  c = () => {
    this.a += 10;
    return this.a;
  };
}

// make the store observable
User = allObservable(User);
// create an observable object
const user = new User();

// [PROBLEM] b's change is printed correctly, but code inside constructor is not printed
autorun(() => console.log(user.b));

// trigger the change
setInterval(() => user.c(), 1000);
```

Here, the `reaction` code snippet inside constructor is never called. However, it works if I pull that function out of class definition. What would be a way to monkey-patch the [@allObservable](https://github.com/farwayer/mobx-decorators/blob/master/src/decorators/all-observable.js) function to also invoke the constructor correctly? Thanks!

**Comment by urugator** [comment]
Well the problem is that props arent's defined on prototype (class), but introduced to "instance" during the constructor invocation.
In order to find out which props should be made observable, you have to run constructor first. But when constructor runs the props aren't observable yet, therefore invisible for `reaction`.
So what you would have to do is to somehow inject (or explicitely call) a piece of code at the beggining of the constructor - like `autoExtendObservable(this)` (obviously won't work for any other props introduced in constructor later).
However you can't patch prototype inside constructor, therefore you still need class level decorator/function for action/computed, unless you want them defined on instance as well (as opposed of having them on prototype).
I would personally suggest to stick with "bloated" explicit code or using a custom factory function instead of class syntax.
