### ISSUE TITLE
enforceActions: 'observe' and performance

### ISSUE THREAD

**Issue by Tsury** [mobxjs/mobx#1824]
I just converted all of my project into `actions`/`runInActions`/`flows` and set `enforceActions: 'observe`, in order to make sure all of my state changes happen inside transactions, to prevent unneeded renders, etc.

Currently I don't feel any performance increase, and even wonder if adding all of these actions and shredding the code may have deceased performance. As for the code itself, I'm not sure if adding all of this syntax and restrictions contributes enough to justify its existence.

Can anyone shed some light on their experience with moving to strict mode? Should it, on average, increase performance? maintainability? Any other advantages? I need to decide whether to commit these changes or just go back to non-strict mode.

Thanks.

**Comment by urugator** [comment]
> Currently I don't feel any performance increase

You won't see much of a performance increase when state mutations occur from within react dom event listener. Missing `action` can cause multiple `forceUpdate` calls, however react will batch them into a single update, resulting in single re-render.
So missing `action` should be mainly noticible when mutations occur from unbatchable context (ajax response/setTimeout etc) or when using `reaction/autorun`.

The overhead caused by actions should be negligible - there are additionally few global var checks/switches, nesting counter and an array of deferred reactions (normally immediately invoked).

**Comment by mweststrate** [comment]
Main goal is maintainability and predictability. it also clearly communicates the intend of the function; actions update state, derivations compute from, etc. See also: https://mobx.js.org/intro/concepts.html#3-actions
