### ISSUE TITLE
@computed is optional for properties?

### ISSUE THREAD

**Issue by JedimEmO** [mobxjs/mobx#1861]
I'm not quite sure what's going on here, but I thought properties had to be decorated with computed in order to be observable. But this seems to work well:

```typescript
import {observable, reaction} from "mobx";

class Foo {
    @observable public test: number = 42;

    public get t() { return this.test; }
}

const f = new Foo();

reaction(() => f.t, (v) => console.log(`This should not react?: ${v}`));

f.test = 666;

```

output from execution: 
```
xxx@xxx:~/tmp/mobxtest$ node test.js
This should not react?: 666
xxx@xxx:~/tmp/mobxtest$ npm ls mobx
tmp@1.0.0 /home/xxx/tmp/mobxtest
└── mobx@5.8.0 

```

Is this expected behaviour? Am I missing something obvious?

**Comment by spion** [comment]
If you inline the getter in the reaction function, it should become clear why it happens.

**Comment by mweststrate** [comment]
Tracking happens because `@observables` are used. The level of indirection
(functions, getters, etc doesn't influence that process). The only
difference that @computed makes it that it provides a caching point. That
is; it doesn't need to re-evaluate as long as test doesn't change. While in
your example it needs to re-evaluate every time the reaction is running.
(Which is in your example is exactly same amount, as test is the only thing
causing your reaction to run, but if your reaction uses many different
(computed) observables, that will make a difference).

Op vr 4 jan. 2019 om 11:36 schreef Gorgi Kosev <notifications@github.com>:

**Comment by JedimEmO** [comment]
Ah, thanks. Yeah, I get the idea in this simple example, but I found it in a slightly more complex setting. Anyhow, that explains it a bit to me, thank you for your time :)
