### ISSUE TITLE
enumerable action decorators

### ISSUE THREAD

**Issue by yoni-wibbitz** [mobxjs/mobx#1920]
Hi,
I have a an app using mobx 5.1.0 (not mst) & react. now im adding an Undo/Redo feature. I observe a store and on each change, I save snapshot with lodash cloneDeep function. the only issue I have now is it's not cloning the methods who uses the action decorator(@action).

after several hours I realized its because they are not enumerable unlike the ES5 way:

        @action
	moveScene = (fromIndex, toIndex) => {
		let movedItem = this.scenes.splice(fromIndex, 1);
		this.scenes.splice(toIndex, 0, movedItem[0]);
	};

VS

	moveScene = action((fromIndex, toIndex) => {
		let movedItem = this.scenes.splice(fromIndex, 1);
		this.scenes.splice(toIndex, 0, movedItem[0]);
	});

Question 1: why using the decorator make it enum, and there is a way to change it(options)?

Question 2: I was trying to create a fix for it by using another "decorator":
```
const inAction = func => {
	console.log('inAction');
	return action(func);
}; 
export default inAction;
```
and the use:
```
 @inAction
	moveScene = (fromIndex, toIndex) => {
		let movedItem = this.scenes.splice(fromIndex, 1);
		this.scenes.splice(toIndex, 0, movedItem[0]);
	};
```
but i lost much of mobx performance, it didnt recognize I'm using splice twice on the same action, so i can see the app is re-rendering.

Why is it happening? 

* I am aware(not sure on how to resolve) that after a userAction many reactions may change my state and I wont know how to undo to the correct snapshot version,

Thanks!!

**Comment by mweststrate** [comment]
Not an answer to your question: but if you are deep cloning with actions,
your undo / redo will probably be broken; because the actions are bound to
this, that means when cloning, they are still bound to their *original*
this, not to the clone.

Some tips in general: 1) you might not want to use deep clone for undo /
redo, that will get very expensive very quickly 2) copying data as way of
redo / undo only works if you are really sure the current user is the only
actor that iteracts with the data (so no updates from server etc).
Generally speaking undo / redo is better implemented by recording the
actions. (you might want to check my blog, I've written some articles on
this)

That all, which might be totally irrelevant to your problem, being said:
The default behavior of MobX is to only have the stateful members as
enumerable, not the derived ones, nor the actions. That without `@action`
your action was enumerable is more a sad side effect for the need of
binding your methods through field initializers; normal class methods
aren't enumerable either.

To get the correct behavior the methods are best kept at the prototype, so
that only your data is cloned, not the (incorrectly) bound methods, without
losing them. Are you sure your methods need to be bound? If so, you could
move `action` inside your methods by using `runInAction` in your function
body and use an utility like @autobind that (afaik) does work correctly
across clones.
