### ISSUE TITLE
Can mobx be used to fix React hooks usability?

### ISSUE THREAD

**Issue by zxti** [mobxjs/mobx#1923]
By far one of the biggest usability issues with React hooks is [stale callbacks](https://mobile.twitter.com/dan_abramov/status/1098898584626495488) by under- or over-specifying your dependencies.

MobX shines at being able to automatically track dependencies and invalidating dependents. Could MobX somehow be used toward this purpose of invalidating React hooks?

E.g. you could imagine a parallel set of hooks, such as mobx.useMemo()/mobx.useEffect()/mobx.useCallback, which automatically regenerates the closure and doesn't need the second `keys` argument at all. E.g., useCallback is just a useMemo, useMemo is just a useRef(computed(...)), useEffect is...an autorun that updates a ref that is conditionally triggered by a native useEffect?

I haven't thought deeply about this but perhaps other mobx/hooks experts could chime in.

**Comment by urugator** [comment]
There is already [`useComputed`](https://github.com/mobxjs/mobx-react-lite#usecomputedfunc---t-inputs-readonlyarrayany---t) as observable analogy to `useMemo`. 
`useReaction` is possible, but can't replace `use(Layout)Effect` as it's disconnected from rendering process (so it can't be safely used for DOM manipulation etc).
`useCallback` is simply `useComputed(() => () => {})` 

However the problem is more general:
- closures can depend on anything from outer scope - therefore you can't be sure that only observables are used, same way as you can't be sure that only values from hook's second arg are used. 
- even observables must be passed via non-observable references: `useComputed(() => store.a + store.b, [store])`

**Comment by mweststrate** [comment]
I think theoretically we could, but I doubt we should. Properly understanding the hook model is better than working around it. It indeed relates to understand and dealing with closures as urugator explained. If the model is problematic, just stick to class based components + observer, where props and state are observables and the whole MobX model takes care of things as you desire :)
