### ISSUE TITLE
Typescript weirdness with `this` in observable

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#1954]
@mweststrate In response to https://github.com/mobxjs/mobx-react-lite/issues/133#issuecomment-487031399

I made a video showing the issue.

https://youtu.be/EZthJhYKjD0

On top of that, with getters, it gets even weirder. Unless `this` is used, the return type of `observable` turns out `any` 😵 

**MobX version 5.9.4**

```ts
import { observable } from 'mobx'
import React from 'react'

export const WithObserverable: React.FC = () => {
  const [state] = React.useState(() =>
    observable({
      foo: 10,
      setFoo() {
        this.foo = 20 // always any
        state.foo = 20 // works only if getter is using this
      },
      get biggerFoo() {
        // return state.foo * 5 // make state type = any
        return this.foo * 5
      },
    }),
  )
  return null
}
```

PS: In the video, there is TS 3.2, because TS 3.4 slows down my VSCode terribly for some reason. However, I tried it and it doesn't matter regarding these issues.

**Comment by mweststrate** [comment]
Can you include tsconfig?

**Comment by FredyC** [comment]
Fairly standard I would say...

```json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
    "lib": ["esnext", "dom"],
    "sourceMap": true,
    "jsx": "preserve",
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "strict": false,
    "downlevelIteration": true,
    "noImplicitAny": false,
    "rootDir": "src",
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  },
  "include": ["src"],
  "exclude": ["node_modules", "build", "public"],
  "compileOnSave": false
}
```

**Comment by mweststrate** [comment]
Many of the tests in mobx-react-lite use the `this` pattern without problem, I think the problem is that you are referring to `state` in the body, in which case the object definition becomes self referring, and TS can no longer inference the type. I'm pretty sure the issue would be fixed if `state.foo = 20` line would be dropped as well, but otherwise best create a sandbox to demonstrate

**Comment by FredyC** [comment]
Well, unit tests cannot catch that as that variables turns into `any` which is completely valid. I will probably prepare repo, the TypeScript in CodeSandbox is fairly wonky most of the time.

**Comment by mweststrate** [comment]
yes, but if you open the tests of for example `useObservableStore` in the
IDE and hover the types, they are inferred correctly (for me)

**Comment by FredyC** [comment]
Well, I made the CodeSandbox, seems they have "fixed it". Interestingly enough, referring `this` always fails, but closure variables work. I know this wasn't working the same way in my project.

https://codesandbox.io/s/92qqv94wjr

**Comment by mweststrate** [comment]
Finally looked into it! I noticed after downloading that it is indeed `any`, but also noticed that there wasn't a tsconfig. So I generated one (`yarn tsc --init`) and the problem was gone. After toggling all compiler options on and off one by one, to get the `any` back, this is the one that make the difference and is needed to make it all work:

`"noImplicitThis": true`

It is by default enabled in `"strict": true` mode, but  not in loose mode (extremely surprising imho). Anyway, with either `"strict": true`, or `"noImplicitThis": true`, `this` should be all nice and dandy inside object ilterals, so I guess we should mention that in the docs :)
