### ISSUE TITLE
ObservableMap.clear() should return itself

### ISSUE THREAD

**Issue by sergii-aleksieiev-ring** [mobxjs/mobx#1979]
The doc (https://mobx.js.org/refguide/map.html) says:

> replace(values). Replaces the entire contents of this map with the provided values. Short hand for .clear().merge(values)

But method "clear" returns void. So it can not be used as described.

**Comment by ItamarShDev** [comment]
Thank you so much for catching this!
Feel free to submit a PR for this :)

**Comment by urugator** [comment]
Note that native [Map.prototype.clear() returns undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear#Return_value), so perhaps the doc needs to be changed, not the impl...

**Comment by ItamarShDev** [comment]
@urugator good catch

**Comment by Jongkeun** [comment]
@FredyC 
Sorry to bother you. It looks already merged, but why it doesn't apply to [**this**](https://mobx.js.org/refguide/map.html) page?

**Comment by FredyC** [comment]
Well, seems it got somewhat reverted in https://github.com/mobxjs/mobx/pull/2022. I am not sure what is the correct output really.

**Comment by mweststrate** [comment]
Seems the change was merged, but the docs weren't republished since thence. Just regenned and pushed the update (although might still take a while). 

Admittedly this is still a painful process of which I'm currently the SPoF, and we'd really benefit from migrating docs to 11ty / docusaurus / docz / some docs system that is still actively maintained, unlike gitbook 2 :). See for details #1859

**Comment by FredyC** [comment]
Hm, @Jongkeun you got me really confused in here. I thought there is something missing in published docs but it was opposite. It is indeed correct, so closing this one.

**Comment by Jongkeun** [comment]
At the time I checked, this issue was not applied. So I told you. But now this was published well.
Thanks to your checking.
