### ISSUE TITLE
How to use latest version together with v3.2.2 (React) ?

### ISSUE THREAD

**Issue by pratikt-cuelogic** [mobxjs/mobx#2019]
I have a:

1. [x] Question: How to use latest version together with v3.2.2 (React)

Description:
I have an years old application built on top of react, mobx (3.2.2) , mobx-react(4.2.2).
We are doing upgrades and now stuck at mobx, would like to upgrade to latest but looks simply upgrading would break application and observable and etc would behave differently..
We have n no of stores and application is heavily depdendent on them.. we would prefer it tobe done gradually one module by module... or if there is a better way to do so please suggest.

Can we run two versions together ?

**Comment by FredyC** [comment]
MobX V3 is fairly old, we only support V4 (LTS) and V5 which has completely changed how are observables handled internally (using ES6 Proxies). If you need to support IE11, you have to stick to V4 anyway. Sadly, I am not aware there would a migration guide V3 -> V4. 

Regarding mobx-react, if you are upgrading to latest React (16.8) then use V6, otherwise, you have to stick to V5 because V6 uses React Hooks internally.

> Can we run two versions together?

I doubt that unless you would strictly separate observable from V3 with those from V4/V5. If your stores are specific to an enclosed area of the app, it's probably doable, but it will be somewhat painful.

Sorry, I cannot provide better help. Perhaps some other folks who remember V3 will have more insight.

**Comment by pratikt-cuelogic** [comment]
Thanks for info @FredyC , I'll try it out keeping your suggestions in mind
