### ISSUE TITLE
uncheck dirty mark on a filled which has been changed multitimes and at last it's value wasnot changed

### ISSUE THREAD

**Issue by MHA15** [mobxjs/mobx#2025]
3. [x] Idea: check observable changes before run trackable functions to be sure if it was really changed  
  * [ ] What problem would it solve for you? less component renders 

  * [ ] Do you think others will benefit from this change as well and it should in core package (see also mobx-utils)? no it's a core feature
  * [ ] Are you willing to (attempt) a PR yourself? maybe not so sure (I didn't read the source code yet)

I was checking some cases in mobx observable and I figure out that if this action gets run it would not call trackable functions (which is ok and good for app performance)
```js
// store = {x: 10}
runInAction(() => {
store.x = 10;  // not checked as dirty
})
```

but in a case like this it will call trackable functions but data is still not changed and it is a redundant call
```js
// store = {x: 10}
runInAction(() => {
store.x = 5; // checked as dirty
store.x = 10; // should remove dirty mark
})
```

I think that when the most outer action will finish it should not call functions which was listening on changes which have been undo in actions

**Comment by FredyC** [comment]
Can you provide a small runnable example to show the problem in action?

**Comment by urugator** [comment]
Note that you can workaround it like this: 
```javascript
class Store {
  @observable _x = 10;
  @computed get x() {
    return this._x;
  }
}

const store = new Store();

reaction(
  () => store.x,
  x => console.log(x)
);

runInAction(() => {
  store._x = 5; 
  store._x = 10;
});
```
Which raises the question - can't we simply wrap observable accessors into computed?

**Comment by aretecode** [comment]
Wouldn't this add additional complexity in the codebase, and _some_ overhead by doing an additional `isEqual` for _every_ `action`? 
Just to satisfy the edge case where the `property` is changed to a `new value`, and then back to the `original value` inside of the **same** `action`?

If you're changing the `property` to a `new value`, and then back to the `original value`, why not use a temporary variable in your application code instead?

**Comment by urugator** [comment]
> isEqual for every action

Considering the "each observable as computed idea", we could remove the equality check preformed during *every* modification, because the equality check would be performed by computed lazily later during *get* against the cached value - and if there is no reaction, then there is no cache and therefore no equality check...
So in case you're updating single value multiple times, there would be less checks, no checks if value isn't observed and the same number of checks in other cases.
However these checks are really trivial and quite unimportant from the performance perspective.
The main overhead would probably come from the extra node in depedency tree. However I think this could be further optimized, because we don't need full-fledged computed on the top of the observable - we know there will be a single static depedency (the actual value).
The core idea is just to use similar caching/invalidation mechanism as the one in computeds (propagate "possibly changed" on write, perform "equality" check later when requested by reactions)
Obviously I can be completely wrong or missing something important.

**Comment by mweststrate** [comment]
@urugator from top of my head, the reason your alternative works is because you use a reaction, which has a built-in equality check on the output of the first function, so that already avoids the rerun, not just the fact that you use computed in itself. 

Although the proposal sounds appealing, I think there will be a lot of corner cases in the sense that different reactions can have different "base" values of the observables they are using, depending on the moment they are created. Not entirely sure, but I think there is a lot of complexity involved in the said change, as observable values are now the leafs of the dependency trees, that dirty the object tree, schedule reactions to be run, which, in turn causes values through be pulled through the system. So the change might be quite involved. However, if someone is willing to put a couple of hours in it to attempt a PR, feel free. Since the core algorithm isn't that big, I don't the the change in itself shouldn't be too difficult to apply. 

Note however that there might be different performance behavior afterwards, as reactions now can skip checking if computeds are changed, if it knows that observable values used are changed anyway. I think it might be doable to achieve the same, but it might take a while to get the algorithm at the same reliability level with such a fundamental change.

**Comment by urugator** [comment]
@mweststrate 

> the reason your alternative works is because you use a reaction, which has a built-in equality check

It's just a bad example, but it works even with `autorun` or when you return `Math.random()` from subscription part. The reaction/autorun is never invalidated, it's just notified to "pull" the computed.

Given the description of `computed`:
```
 * 1. First time it's being accessed it will compute and remember result
 *    give back remembered result until 2. happens
 * 2. First time any deep dependency change, propagate POSSIBLY_STALE to all observers, wait for 3.
 * 3. When it's being accessed, recompute if any shallow dependency changed.
 *    if result changed: propagate STALE to all observers, that were POSSIBLY_STALE from the last step.
 *    go to step 2. either way
```
The suggested impl should more or less go somehow like:
``` 
 * 1. First time it's being accessed return and remember the value
 *    until 2. happens
 * 2. First time the value is set, propagate POSSIBLY_STALE to all observers, wait for 3.
 * 3. When it's being accessed, compare actual value with remembered value.
 *    if they differs: update remebered value, propagate STALE to all observers, that were POSSIBLY_STALE from the last step.
 *    go to step 2. either way      
```
The cached value is never returned, it's just used when determining whether to propagate STALE to observers. The idea is to use this "2 step invalidation mechanism", rather than immediately propagating STALE on set operation.

**Comment by mweststrate** [comment]
Yep, got the idea. might very well work, not fully sure. I am not 100% sure yet, if "base" and "new" value, are the same for all observers. Probably they are though. So if somebody is interested in implementing the above, that would be welcome, probably some issues arise that we don't think of as of yet, as I think we had a similar discussion before, but not entirely sure yet. I think it touches some of the same problems (not perse problems, but choices in semantics) as discussed in #1805, but it would need to take some quiet hours to be sure of it :)

**Comment by urugator** [comment]
My biggest concern is that while it's an optimization, it would actually "degrade" performance in 99%™ cases (maybe unnoticably, but still...).
How often do you set an observable to multiple values in a single TX? And how often the final value is the same as the initial?

I just found it interesting, because my first idea was some kind of snapshoting/diffing associated with TX context, which would be super expensive and complicated :D

**Comment by mayorovp** [comment]
Experimetnal implementation for perf tests: https://github.com/mobxjs/mobx/tree/exp-uncheck-dirty-mark

**Comment by FredyC** [comment]
I am kinda lost in a discussion here. Do we need to do something about the issue? Is it something worth following in MobX6 @mweststrate?

**Comment by mweststrate** [comment]
I think the change is risky, and that the gains on average are probably making things slower for and edge case that might be faster
