### ISSUE TITLE
Document an approach without models

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#205]
MobX is great because we don't have many concepts.

My suggestion is that we document another approach: one without models, just stores. Looking at Flux docs we have [this](https://facebook.github.io/flux/docs/overview.html#stores):

> Stores contain the application state and logic. Their role is somewhat similar to a model in a traditional MVC, but they manage the state of many objects — they do not represent a single record of data like ORM models do. Nor are they the same as Backbone's collections. More than simply managing a collection of ORM-style objects, stores manage the application state for a particular domain within the application.

Here is the one of the ways I like to implement MobX:

```js
// todoStore.js

class TodoStore {
  @observable todos = []

  getTodos = () => {
    return this.todos
  }

  getTodo = id => {
    return this.todos.find(todo => todo.id === id)
  }

  addTodo = text => {
    this.todos.push({ id: Date.now(), text })
  }

  removeTodo = id => {
    this.todos = this.todos.filter(todo => todo.id !== id)
  }
}

const todoStore = new TodoStore()

export default todoStore

// then in my components I import todoStore and call it's methods
// (instead passing it around through props, I just import it directly)
```

**Comment by otbe** [comment]
This may work for simple models like todos, but if they become more complex I really like to have an extra class. Just for testing and better decoupling. From my point of view one of the big advantages of mobx over other "state management frameworks" is ```store.todos.push(new Todo());```. Plain and simple JS. No extra function that could fail in some circumstances. Nothing to test :D
Also keep in mind that ```getTodo(id)``` is not reactive. This could lead to problems in more complex scenarios.

Btw: I agree with you that passing stores as props is not an ideal solution, because your parent components become very "fat" over time. Maybe we should discuss this point in the docs :D

**Comment by mweststrate** [comment]
I agree with both of you. MobX doesn't need model classes, but for complicated it is still a nice pattern, very imho because it is a matter of taste as well. @hnordt would you feel for adding these clarifications to the docs? (`gh-branch`, `docs` folder)

**Comment by hnordt** [comment]
@mweststrate of course. I'll do this next week.

**Comment by vinej** [comment]
I agree for simples cases that models are not needed, but if you have to create a new record that contains many fields with default values, you will need something like a model to create a new instance of that record. The store can contains a static method to create a new instance.

**Comment by flipjs** [comment]
@hnordt How is it working for you so far? I also prefer a flux-style store because I have used redux for a medium-size application and that's what I am used to. Is the documentation updated with this approach?

**Comment by vinej** [comment]
After one month, I found that models are needed, because you need a definition when you create new records. Lately I changed my todo example (todo_store) to created a factory to have a new form store that includes the model of the form. More and more I think that I have to found a way to have a model that can be use with mongoose (backend) and React/Mobx (front end). I'll think about this weekend. I also changed my example to move all actions @action into the stores. Reducers are only there as a middleware between the action and the store.

**Comment by hnordt** [comment]
@flipjs after working more with MobX I agree 100% with @mweststrate and @vinej: for complicated cases models are good.

I've updated both the title and issue content.
