### ISSUE TITLE
Mobx on server side, Node.js + react native

### ISSUE THREAD

**Issue by thobhanifreddy** [mobxjs/mobx#2088]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

**Please be sure to close your issues promptly.**

I am making a peer to peer to chat app using Node.js and react native. Current react native POC app have mobx integration.

But now I am thinking  about using Mobx class on server side too. Basically I want one `model` folder for both server side and client side(Project will be managed using lerna).

So wanted ask is it good idea to use Mobx class on server side?

**Comment by FredyC** [comment]
Please come back again with an actual question :) It's good as any unless proven otherwise.

**Comment by spion** [comment]
You might want to look into MST (https://github.com/mobxjs/mobx-state-tree) and automerge https://github.com/automerge/automerge due to their support of streaming JSON patches of the changes. Automerge would be better if you intend to develop the chat app with additions where you add more complex state that could have conflicting changes
