### ISSUE TITLE
Attempt to read an array index X that is out of bounds

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx#2089]
Let's start with a simple repro ... https://codesandbox.io/s/pensive-morning-ypt5e

When you try to remove any item, it behaves correctly, but there is a warning 

> [mobx.array] Attempt to read an array index (2) that is out of bounds (2). Please check length first. Out of bound indices will not be tracked by MobX

Is it false positive?

It works correctly if I would render `store.list[idx]` directly in `Item` component. However, wrapping it into another observable like shown is a problem for some reason. My guess is some sort of race condition, but cannot fully comprehend why it would be happening.

Obviously, I am not making that up just for fun, it's part of a more elaborate solution and it makes sense there to have that extra observable there.

**Comment by urugator** [comment]
Firstly two unrelated problems:
1) don't use index as key
2) don't access props directly in `useLocalStore`. The `get value()` is computed and cached ... even if the component gets updated by recieving new `idx`,  `get value()` will yield wrong value (the cached one) ...

To the actual problem:
When you modify `store.list` the computeds `get value()` are notified and they immediately recompute to find out whether they have to notify observers.
But at that time no component had a chance to re-render ... so the number of `Items` and therefore the number of computeds is not in sync with updated `store.list.length`.
So there's one "extra" `computed` which is notified and accesses index out of bounds.
Clear?

**Comment by FredyC** [comment]
Somewhat clearer, yes :) For a full context, this is a part of solution for forms the Item is basically like form field.  Since the fields can be deeply nested, eg. `deep.list[0]` I have observable as a view into that nested path for ease of use. So in practice, it looks something like that.

```tsx
  const state: XFieldState<TValue> = useLocalStore(
    source => ({
      get value() {
        return getIn(ctx.state.values, source.fullPath) as TValue
      },
      setValue(newValue: TValue) {
        const parent = getIn(ctx.state.values, source.parentPath)
        parent[source.baseName] = newValue
      },
    })
  )
```

> 1. don't use index as key

I know that, but this I am not getting any unique value there, I would have to generate something temporary just for a client-side needs.

> 2. don't access props directly in `useLocalStore`. The `get value()` is computed and cached ... even if the component gets updated by recieving new `idx`,  `get value()` will yield wrong value (the cached one) ...

Yea, beginner mistake. Fixed that now in a sandbox, but it doesn't change a thing.

---

So I tried to basically generate item ID based on an initial index, and it seems to have a fixed problem, but I have to think about this later today because I am still unsure why is that.

https://codesandbox.io/s/serene-rain-upp79

**Comment by urugator** [comment]
>  Fixed that now in a sandbox, but it doesn't change a thing.

It would change a thing only if you would change `idx` without changing `store.list` at the same time.
Btw you should do the same for `store` (or add a check it doesn't change inbetween updates). 

I suggest to model the whole thing like this:
```javascript
const store = {
  // all items
  items: {
    itemId1: { label: "Field 1" },
    itemId2: { label: "Field 2" },
    itemId3: { label: "Field 3" }, 
  }
  // relations  
  children: {
    itemId1: [itemId2, itemId3],   
  }   
  // action example  
  removeItem(id) {
    delete this.items[id];
    delete this.children[id];
    for (let parentId in this.children) {
      const childArray = this.children[parentId];  
      const index = childArray.indexOf(id);
      if (index !== -1) {
        childArray.splice(index, 1);
      } 
    }
  }  
}

// pass only store and relevant id everywhere
// no need for computeds to obtain specific item/child
```
I can almost guarantee that anything else will end up being a lot more complicated.

Rule of thumb: normalize state (use ids for anything which has a dynamic number of occurences) and don't mix react's props/state with mobx state.

**Comment by FredyC** [comment]
Well, the order of those items is important for me so converting it to object with keys seems like I won't be able to do tackle that.

I am not entirely sure about those "relations" you have set up there. How is that created and why?

It all seems unnecessarily complicated for such a simple task. Considering it actually works, I might probably just ignore those warnings. Doesn't matter if it's going to cause an extra rerender or whatnot as long as it works and makes sense.

**Comment by urugator** [comment]
What you're dealing with is that the state isn't propagated in correct order, because unlike react, mobx knows nothing about the hiearchy of reactions (observers) - it doesn't know that the existence of `derivationB` depends on a result of `derivationA` so that `derivationA` must be invoked first.
So if you want to avoid similar issues don't mix react state/props and mobx state.
As a consequence you will be forced to move state of individual components (Items) up the hierarchy.   
You will end up with a tree of nodes, in denormalized form it can look like:
```javascript
const tree = { 
  label: 'Node 1',
  children: [
    { label: 'Node 2', children: [/* ... */] },
    { label: 'Node 3', children: [/* ... */] },
    /* ... */
  ]
}
```
The problem is that working with hierarchies is quite complicated.
Change detection requires deep comparison and you also need persistent keys.
Retrieval of specific item requires traversing the whole tree. Etc.
I think you have already noticed some of these issues in #2077
It's not inherently mobx problem, stateful hierarchies are generally really hard to deal with.
So the idea is to avoid all these issues by avoiding hiearchies at the cost of maintaining multiple but flat structures.
The `items` simply holds all the nodes no matter where they are located in the tree. It makes any node accessible by it's ID in a constant time.
The `children` holds child nodes for each parent (it basically represents the tree structure). It makes children accesible by their parent ID in a constant time.

**Comment by FredyC** [comment]
@urugator Thanks. I've refactored to a similar structure and seems to be working without warnings.

I am thinking though, that having such state immutable and using eg. Immer to modify it should work without any normalizing, right? There is no derivation/caching issue. The state is modified and components re-render. Done. Feels like that MobX is an actually worse tool in this case.

**Comment by urugator** [comment]
> immutable and using eg. Immer to modify it should work without any normalizing

Well no. If you want to prevent re-rendering the whole tree, you can't just replace it as a whole...
So in both cases you have to update just the smallest part of the tree ... so you have to localize these smallest parts somehow (eg diffing).
Then the situation with immutables is actually even worse, because in order to replace leaf, you have to replace all ancestors ... so while you can prevent re-rendering of untouched branches, you can't never re-render just a single leaf or subtree alone.
