### ISSUE TITLE
how to code splitting mobx?

### ISSUE THREAD

**Issue by little-yao** [mobxjs/mobx#2121]
I have a:

1. [x] Question: Feel free to just state your question. For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel

there are lots of pages in my project. I don't want to import them in a root store. Instead, I want to dynamically  register each of them on every page. In redux(replaceReducer) and vuex(registerModule) has api to handle this
https://redux.js.org/recipes/code-splitting
https://vuex.vuejs.org/guide/modules.html#dynamic-module-registration
So I ask how to do with it?

**Comment by FredyC** [comment]
MobX does not impose any special rules about code splitting like those two mentioned libraries. It mostly depends on how you structure your stores. Generally, you should probably have decentralized stores instead of a global one, although some things are probably app wise (eg. auth). And in case you wonder how to achieve that with inject-Provider ... Well you cannot, but you can [the Context](https://mobx-react.js.org/recipes-context) instead to have better control about it.

That said, I don't think that code splitting stores is exactly size bottleneck unless you have really huge structures in there.

**Comment by little-yao** [comment]
I see. Thank you for your help. I Close this issue
