### ISSUE TITLE
Why am I getting an `invalid action stack` error?

### ISSUE THREAD

**Issue by spark1031** [mobxjs/mobx#2135]
Context:
I am trying to run some jest/react-testing-library tests with drone and get this error when the test tries to render my component.
`Error message: "[mobx] invalid action stack. did you forget to finish an action?"`
My component renders some data that is being loaded into a store via mobx. Every time this store is created, the `load` action is called inside the store's constructor. Every time this `load` action is called, the test fails. However, there are no errors that arise when I run my app and no errors that arise when I run my tests locally. This error only occurs when I run my tests in drone.

This error seems to originate from here:
https://github.com/mobxjs/mobx/blob/master/src/core/action.ts#L88
Which uses mobx globals which are defined here: https://github.com/mobxjs/mobx/blob/master/src/core/globalstate.ts#L157

1. Looks like there is global state stacking for actions that are being run (and when they finish)
2. Also looks like there are problems with the global state object if there are multiple versions on mobx active

Question:
What are some things I could try that could fix this issue? I tried looking on stackoverflow and had little luck finding others who had run into this issue :(

Hopefully someone can help me here!
Thank you in advance!

**Comment by Bnaya** [comment]
I would guess its related to #2117

**Comment by Bnaya** [comment]
Do you have multiple mobx versions?
Try:
https://mobx.js.org/refguide/api.html#isolateglobalstate-boolean

**Comment by ianmstew** [comment]
I can confirm 2 separate instances of this error halting development at my firm, and we had to roll back to `mobx@5.13.0` until we could determine what is going wrong, whether that's on our side on or the framework side.

@xaviergonz, I am curious the reason for adding this severe of an error.  If the only reason is to support advanced (framework-level) use of startAction/endAction as discussed in the linked issue, then I would argue it should work flawlessly for first class API usage.  If the reason is to catch misuse of first class API usage, then heads up that there are hard to debug edge cases out in the wild (including two separate apps in my firm), and we did not expect to land a dev-breaking error on a patch version.

**Comment by xaviergonz** [comment]
In theory that error (which I added as it was suggested to me here btw: https://github.com/mobxjs/mobx/pull/2117#issuecomment-534512931 ) should never happen when not using those functions directly, but it is true I didn't think of multiple mobx versions sharing the global state (where the new version would update the current action id and the other won't).

I'll create a patch that rather than reusing the global state will use their own local state, though it would be cool if somebody could produce a minimum reproduction code.

**Comment by mweststrate** [comment]
@xaviergonz note that the globalversion object has a version number, that is intended to be used to remain backward compatible / it will warn if there are multiple version of mobx sharing incompatible versions of global state. 

That being said @spark1031; having multiple versions is in most cases a sign of an incorrect package setup, so unless there is an explicit reason why you need multiple versions (the only case I know: having external parties writing plugins for your product that can have their own mobx), the best thing to do is to make sure you have only one version of mobx. It will make your bundle smaller as well. 

Usually this is caused by using npm link, or by using dependencies that have mobx as dependency instead of as peer dependency.

**Comment by FredyC** [comment]
Yarn offers a good option to deduplicate different library versions. In package.json add, for example, following and all packages will be forced to use that version and there will be only one sitting at the root of node_modules.

```
"resolutions": {
  "mobx": "5.14.0"
}
```

**Comment by Bnaya** [comment]
Also using yarn-deduplicae can help in many cases
https://github.com/atlassian/yarn-deduplicate

**Comment by spark1031** [comment]
Thank you so much for your help everyone!! Really appreciate the time everyone took to help explain what might be going on for me and also really appreciate the new update =) Thank you again!
