### ISSUE TITLE
Suggestion: reaction to multiple sources

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx#2150]
Imagine a use case where you want to trigger a reaction when any of two elements change, and let's say these elements are objects with primitives.

E.g, objects with { x: number; y: number }

The naive approach would be to do
```ts
reaction(() => [a.x, b.x, c.x], ([ax, bx, cx]) => {
  // do something
})
```
This wouldn't work properly since if for example a.y changed that would trigger the reaction, since it would generate a new array, which has a different ref from the old array.

The less naive approach would be:
```ts
reaction(() => a.x, (ax) => {...}))
reaction(() => b.x, (bx) => {...}))
reaction(() => c.x, (cx) => {...}))
```

However this would mean creating another function to deduplicate code, and also it doesn't get well with fireImmediately cases (since it would initially trigger twice)

The currently preferred approach would be the first case with comparer structural, but it is not so obvious (also maybe you might not want to compare deeply, but just shallowly).

My suggestion is to add something like:
```ts
reaction(() => multi(a.x, b.x, c.x), ([ax, bx, cx]) => {
  ...
}
```
multi (or "some", or whatever the name) would add some kind of symbol to the array (or generate an special object) to indicate to reaction that it should do a shallow comparison of elements

This syntax could be further expanded, e.g.
```ts
reaction(() => deep(a), (a) => {
  // react when there's a deep change in a
}

reaction(() => shallow(a), (a) => {
  // react when there's a shallow change in a props
}

reaction(() => ref(a), (a) => {
  // react when the ref / primitive changes
  // this is basically the same as the default when just writing () => a
  // but makes intention more clear
})

reaction(() => multi(shallow(a), deep(b)), ([a, b]) => {
  // react when there's a shallow props change in a or a deep change in b
}

reaction(() => custom(a, comparer), (a) => {
  // custom could be the building block of everything above
})
```

Also if polluting the mobx namespace with those is an issue, it would be done like this instead (which would also help IDE discoveralability):
```ts
reaction((r) => r.multi(a.x, b.x, c.x), ([ax, bx, cx]) => {
  ...
}
```
or like this:
```ts
import {r, reaction} from "mobx"
reaction(() => r.multi(a.x, b.x, c.x), ([ax, bx, cx]) => {
  ...
}
```

The only con I see is that it might be at odds with the custom comparer parameter, but it could either:
-  throw when any of those functions is used and a custom comparer is used
- or just a new reaction method with another name

**Comment by mweststrate** [comment]
(disclaimer, I didn't read the entire proposal as I think the first premise is largely not an actual issue) 

> This wouldn't work properly since if for example a.y changed that would trigger the reaction, since it would generate a new array, which has a different ref from the old array.

Since `a.y` changed, it is irrelevant in 98% of the cases that a new array is generated, since something changed, so the effect does need to run anyway; the first function running is already a signal in itself that the effect most probably should run (one could argue that the return value often even doesn't matter)

There are few exceptions, e.g if you do something like `[Math.round(a.y)]` and `a.y` only changes slightly. But there are 2 good solutions for this when it matters: 1) (IIRC) the options of reaction allows setting a custom comperator, consistent with other apis such as computed. 2) extracting `Math.round(a.y)` to a computed also fixes the problem

**Comment by ssured** [comment]
I understand the use case and have successfully used https://github.com/slikts/tuplerone to create tuples using a createTransformer. Just my 2c
