### ISSUE TITLE
N:M data caching best practice

### ISSUE THREAD

**Issue by khrykin** [mobxjs/mobx#218]
Hi, I'm new to `mobx`  and for me the subject is not clear after reading docs/playing with examples. I mean since we don't normalize our data it should cause significant overhead to maintain consistency for  n:m relational data... I'm obviously missing something, what is the best way to handle this cases (for example — Trello-style app, where users live in boards, cards, comments etc.) ?

**Comment by mweststrate** [comment]
Can you elaborate what you exactly mean with maintaining consistency? That data that is displayed from a referred object is consistent, or that objects are properly cleaned up if they are for example no longer be referred to?

**Comment by khrykin** [comment]
@mweststrate I'd say I mean both, actually

**Comment by AriaFallah** [comment]
@khrykin Have you read this https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254#.77jo3gyc5?

**Comment by khrykin** [comment]
@AriaFallah I did. The question is more about how to organize things, i.e. data classes, so, for example when a socket with new comment containing updated author info arrives, I do something like `new Comment(json)` and all components referred to this comment's author will be updated. I just can't imagine how to implement this without collecting `Author` instances in some cache, i.e. some kind of normalization

**Comment by mweststrate** [comment]
Indeed, you will have inevitable a collection of data stored on your client in which you store your data, usually some observable map or array. Usually per type. MobX is quite unopinionated on how you organize this. But you can safely refer from one object to arbitrary other objects in other stores, as long as you update them in place when receiving changes. (or you can normalize stuff and look it up each item you render if you like that better). So you still have stores and collections, but when using MobX you can still use real javascript references between different objects, instead of needing to normalize them to foreign keys.

For standardized store approaches you can best take a look at libraries like [mobx-model](https://github.com/ikido/mobx-model) or mobx-reactor. I guess even standard libraries like bookshelf.js will get you quite far.

**Comment by khrykin** [comment]
@mweststrate thank you, gonna find the best solution for my cases
