### ISSUE TITLE
OnBecomeObserved is not triggered when calling observe on observable map.

### ISSUE THREAD

**Issue by thdk** [mobxjs/mobx#2222]
I have a issue:
  * [x] Provide a **minimal** sample reproduction. 
https://stackblitz.com/edit/typescript-onbecomeobserved

  * [x] Did you check this issue wasn't filed before?
Related to https://github.com/mobxjs/mobx/issues/2067

  * [x] Elaborate on your issue. What behavior did you expect?
I would think that if an onBecomeObserved event in attachted to a observable map, then onBecomeObserved would be called when the code starts to observe it.
I thought the map gets observed when using 
`observe(map, () => {}) `
or 
`autorun(() => {console.log(map)}`
or
`when(() => map.size > 0, () => {})`

onBecomeObserved is triggered for `autorun` and `when` but not for `observe`.
Is that the expected behavior?

  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?
Mobx 5.15.0

**Comment by thdk** [comment]
Sorry, I used the wrong repro link:

Here is the correct repro link: https://stackblitz.com/edit/typescript-onbecomeobserved
(I've also adjusted the original link)

**Comment by FredyC** [comment]
I am no expert here, but why do you want to use `observe`? It's kinda low-level API and `autorun` will generally be more useful. 

Also [from docs](https://mobx.js.org/refguide/observe.html#observe)

> observe reacts to mutations, when they are being made, while reactions like autorun or reaction react to new values when they become available. In many cases the latter is sufficient

**Comment by thdk** [comment]
I do use observe indeed for watching over specific properties in my code, but I may have misused it in my example and for my current problem.

However, it's does not seem to work with reaction either:

```
reaction(() => items, () => {
  console.log(items);
});
```

it does work with reaction when using items.size.
```
reaction(() => items.size, () => {
    console.log(items);
});
```

However, when an observable map is being replaced, with the exact number of items as the original map, then I don't think that reaction on items.size will be triggered.

I have extended my repro to have an example for both: autorun, when, observe and reaction:
https://stackblitz.com/edit/typescript-onbecomeobserved-1hy9va

**Comment by FredyC** [comment]
> However, when an observable map is being replaced, with the exact number of items as the original map, then I don't think that reaction on items.size will be triggered.

That's pretty much expected because size hasn't changed :) I don't think you should be relying on size of anything, that does apply anywhere, not just MobX if you care about actual contents of the object.

> However, it does not seem to work with reaction either:

Yea, I remember from the past that having a reaction over some list of items did not work for me either. I ended up using `autorun` and did not dig deeper.

@urugator can you possibly have a look at this?

**Comment by urugator** [comment]
Naming is a bit misleading, in short:
`observe` has nothing to do with `autorun/reaction/action` etc.
`onBecomeObserved` only relates to `autorun/reaction`.
The mobx is designed around `autorun/reaction`. The `observe` is just something extra, it uses completely different (very trivial) logic and isn't actually very useful (arguably).
For illustration, this is a setter for simple observable value (`observable.box()`):
https://github.com/mobxjs/mobx/blob/c4131f1f008330ecd1fc3d9c5f1603b52760a82e/src/types/observablevalue.ts#L107-L119
`this.reportChanged()` relates to propagating a change through dependency graph, created by `reaction/autorun`.
`notifyListeners` simply invoke callbacks registered via `observe`.

`onBecomeObserved` is invoked when a node is attached as a child of another node inside a dependency graph.
It doesn't care about listeneres attached with `observe` (internally `registerListener`).

`onBecomeObserved/autorun/reaction/action` works with `IObservable`
`observe`, despite it's name, works with `IListenable`

Ok so, how you're supposed to use `reaction/autorun`:
Do not think about detecting changes/diffs. Think about what you want to do with your model.
Whatever you want to do, it must be wrapped inside "subscription" function - either `autorun` or `reaction` (it's first arg)
The difference is that `reaction` produces some value and calls another function (second arg) with value provided as argument.

Let's say you want to print model to console using reaction. Why following doesn't work:
```javascript
reaction(() => items, () => {
  console.log(items);
});
```
Because printing model means to "stringify it" first and then send it to stdout.
The stringification process determines what parts of the model are actually needed. Therefore it must be part of the "subscription" function.
What you want to "subscribe for" very much depends on "what you want to print". 
Eg if you would change the implementation of `console.log` to only print the first `item` of `items`, then we are not interested in changes of other items. 
So it should be like this:
```javascript
reaction(() => stringify(items), string => console.log(string));
```
The implementation of `stringify` function is non-trivial, so in practice you could workaround it like:
```javascript
reaction(() => toJS(items), copy => console.log(copy));
```
However, it presumes that you need a whole `items` object for `console.log` operation, which is not neccessarily true as noted previously.

Note the difference between `autorun/reaction`
```javascript
// prints anytime items are modified
autorun(() => console.log(items));
// prints only if the string actually changed
reaction(() => stringify(items), string => console.log(string));
```

At this point you may have noticed, that Mobx works with discrete observable units called Atoms.
Eg. an observable array of 10 items is basically a collection of 10 atoms + 1 atom representing size. Similary objects have one atom per property.
You cannot subscribe for (observe) an array/object/map as a whole, you can only subscribe for (observe) these individuals atoms.
Therefore `onBecomeObserved` expects such single atom (or computed).
However you can expose the array via another "atom/computed" and use it instead:
```javascript
const store = observable({
  _array: [],
  get array() {
    return this._array;
  },	
})

onBecomeObserved(store, "array", () => console.log("array is being used by someone"));
```

**Comment by thdk** [comment]
@FredyC & @urugator Thanks for looking into and replying with a much detailed answer.

I thought the problem was because i was working with a observable map instead of a simple type such as string or number. But I see observe(string) indeed also does not trigger onBecomeObserved (as you explained in your answer)

I was mainly asking because I'm creating a class that exposes an observable map.
In that class I hook on onBecomeObserved and onBecomeUnobserved.

I wanted to make sure that the class internal code get's notified whenever the exposed map get observed/unboserved. 

I understand now that the exposed map should not be observed using 'observe' but that my users will have to use autorun for that.

Currently it looks like it will mainly be used in an autorun (with react).

So conclusion: it's the naming that confused me into thinking that observe would definitely trigger onBecomeObserved.

I'll probably try to use your last recommendation to wrap the observable map in a container and expose it as such.

My code looks now as follows (also updated [here](https://typescript-onbecomeobserved-1hy9va.stackblitz.io))
```
const itemsReaction: ObservableMap<string, IItem> = observable(new Map());
const wrapper = observable({
  map: itemsReaction
})
onBecomeObserved(wrapper, "map", () => {
  console.log("Ok");
});

reaction(() => wrapper.map, map => {
  map.forEach(value => {
    console.log(value.name);
  });
});

wrapper.map.set("id1", {
  id: "1",
  name: "Item 1"
});
```

**Comment by urugator** [comment]
```javascript
reaction(() => wrapper.map, map => {
  map.forEach(value => {
    console.log(value.name);
  });
})
```
Again... the iteration and `value.name` should be part of the first function.
It won't have any effect on `onBecomeObserved`, which is interested only about `wrapper.map`, but the reaction won't be invoked if anything inside map changes.
The first function should return non-observable object/value.
```javascript
reaction(
  () => wrapper.map.map(value => value.name),
  names => names.forEach(name => console.log(name));
)
```
You can imagine `reaction` like this:
```javascript
function reaction(dataFn, effectFn) {
  let prevValue;

  return autorun(() => {
    const newValue = dataFn();
    
    if (newValue !== prevValue) {
      // untracked disables subscriptions
      untracked(() => effectFn(newValue));
    }

    prevValue = newValue;  
  })	
}
```

**Comment by thdk** [comment]
Oops.. I focused too much on onBecomeObserved being triggered that I forgot to see if my reaction was still triggered. Sorry for that.

Updated my code as follows:
```
const items: ObservableMap<string, {id: string; name: string;}> = observable(new Map());
const wrapper = observable({
  map: items
});

onBecomeObserved(wrapper, "map", () => {
  console.log("Ok: onBecomeObserved has been called.");
});

reaction(
  () => wrapper.map.values(),
  () => {
    console.log("Ok: Reaction invoked");
  }
);

wrapper.map.set("id1", {
  id: "1",
  name: "Item 1"
});
```
https://stackblitz.com/edit/typescript-onbecomeobserved-lnmem6

**Comment by thdk** [comment]
Thanks for your support.
