### ISSUE TITLE
Changing observable array in an action produces multiple notifications

### ISSUE THREAD

**Issue by chebum** [mobxjs/mobx#2271]
2. [x] Issue:

There is an unexpected behaviour when shallow arrow fires a "changed" notification for every change despite being changed inside an action (and transaction).

https://codepen.io/chebum/pen/Exazodp
The source is very short, so I'll post it here too:

```
const arr = mobx.observable.array([1], {deep: false});
arr.observe(() => {
  console.log("This method is fired twice, while should be fired once").
});
mobx.runInAction(() => {
  arr.splice(0, 1);
  arr.push(2);
});
```

I expected that while I change the observable array in an action (and thus inside a transaction), the change notification will be fired once. However, it's immediately fired for every change.
The behaviour is the same for versions 5.15.4 and 3.6.2.

The issue is reproduceable in Chrome.

If this behaviour is by design, is there a way to make actions work for arrays as well?

Thank you.

**Comment by FredyC** [comment]
It works correctly with reaction. AFAIK the `observe` is rather low-level API and ignores transactions.

```js
mobx.reaction(() => mobx.toJS(arr), () => {
  output.innerText += "value changed\n"
})
```

@urugator might provide better explanation most likely :)

**Comment by mweststrate** [comment]
Your analysis is correct. observe is a low level implementation tool, that
on itself is completely unrelated to mobx core abstractions such as actions

Op wo 29 jan. 2020 16:28 schreef Daniel K. <notifications@github.com>:

**Comment by chebum** [comment]
Thanks a lot for the replies. Do you know a way to watch for array changes without memory allocations? From looking to toJS's code, it calls slice and thus is creating a new array instance.

**Comment by urugator** [comment]
Personally I would deprecate intercept/observe...
I don't even know what's a valid usecase for these, they're mostly misued imo.
Naming (`observe`) is misleading (especially in relation to `observer`).
They are weirdly designed (multiple events per single atomic operation...).

@chebum Usually if you need to watch for changes explicitely, you are either using Mobx non-idiomatically or using wrong library (as Mobx isn't suited for providing diffs/changes)

**Comment by FredyC** [comment]
I had used `observe` once when I wanted to know what kind of change has happened, but it's possible there was a better solution. I agree it's confusing in general.

@chebum Closing issue, let us know if you have further questions.

**Comment by chebum** [comment]
@urugator I need to perform an async task when any part of the array changes. The solution proposed by @FredyC copies the whole array every time it changes. I'd like to avoid that for obvious reasons. Is there a better way to be notified of any changes to the array structure?
I tried listening to **length** changes, but these aren't fired when the array is reordered.

**Comment by mweststrate** [comment]
Use autorun

**Comment by chebum** [comment]
@mweststrate Thanks a lot. I forgot about it.

**Comment by FredyC** [comment]
Keep in mind that `autorun` will also fire once initially, not only with your changes.

**Comment by urugator** [comment]
The array doesn't change spontaneously, it changes due to some event, which should result in action, which modifies the data. You can invoke the async task inside the action explicitely, rather than associating the task with particular data. It's a lot easier to follow, compose, debug, parametrize, handle errors, control order of operations, etc... [See last paragraph](https://github.com/mobxjs/mobx/issues/1006#issuecomment-426027838)

**Comment by FredyC** [comment]
@urugator It's a nice ideology, but sometimes for the sake of code separations, it's not exactly viable. You might not have access to the operation that should happen based on that change. Sometimes there might be multiple such operations that need to happen unrelated to each other.

I agree that the event-based data flow can be rather messy. I would love to discover something in the middle. Something that doesn't force you to create an entangled mess of dependencies and also keeps the data flow clear. I am aware it's always a matter of tradeoffs and depends on the current situation, but thinking beyond simple contrived examples makes one wonder there is some hidden golden path we haven't discovered yet.

**Comment by urugator** [comment]
> operations that need to happen unrelated to each other and each of them in different parts of the app. 

What do you mean by "unrelated"? If something has to happen, when something else happens, then there is a relation. If it won't happen the application won't do what it's supposed to do.
You won't remove the coupling by using an event bus, you will just hide it and there is no benefit in doing so - quite contrary - it should be as transparent as possible, because that's where the complexity lies, related things should be co-located, not spread all over without knowing how exactly they relate to one other.
It doesn't mean you cannot split a complex piece of code into a smaller less complex pieces. You just won't pretend that they can be connected in ad-hoc way, because they can't.
Things that are truly unrelated shouldn't be coupled - shared event bus does exactly the opposite - it connects everything to everything else.

> micro-whatever architectures

Physically splitting logically related things can be very expensive.
You often have to introduce whole level of complexity including communication protocol, synchronization layer, locking/rollbacking, ditributed transactions etc.
Some things become harder or impossible - testing, optimization, statical analysis.
And usually we don't do this because it's a great way to do programming, but because of technical reasons (horizontal scaling).

**Comment by FredyC** [comment]
> What do you mean by "unrelated"?

I don't have any specific example, but generally in some sort "plug-in" system where you don't know consumers upfront. But I suppose in theory there is always some list of such plugins, so it should be possible to iterate over it and call some sort of "hook" before/after executing the action. So I guess nevermind :)

> Physically splitting logically related things can be very expensive.

I guess it depends. I haven't done any real micro approach just yet, but I see some sort of latest hype about micro-frontends. It might make sense for large projects so there can be several teams working on completely separate parts that work on its own. Obviously, there are other problems, such projects might not be in sync for a mobx version so it wouldn't work anyway. I guess it's more about establishing a contract that does not depend on such things.
