### ISSUE TITLE
Forms Problem

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx#231]
Hello.

I'm trying to work with forms, but it is not working correctly and I think I'm missing something.

I have a todo input list and when I add two items with some text and try to edit them it doesn't work.

**How to reproduce?**

1. Open https://jsfiddle.net/wv3yopo0/139/
2. Click "Add" button
3. In the new input type `ab`
4. Click "Add" button again
5. In the new input type `cd`
6. Now click the first input and try to edit the value; it doesn't work

![screen capture on 2016-05-02 at 13-51-50](https://cloud.githubusercontent.com/assets/1625399/14960850/17a1a14a-106d-11e6-976b-fe307f844024.gif)

Am I missing something?

**Comment by hnordt** [comment]
@mweststrate @AriaFallah I would appreciate your help on this

**Comment by AriaFallah** [comment]
@hnordt found the problem

addTodo needed to be changed to

```js
addTodo() {
  this.todos.push({ text: '' })
}
```

I think the problem was that you dynamically added a key to a plain object, which caused it to not be observed. If the key exists when it's first inserted it works fine.

The other solution is to use the mobx map to properly be able to dynamically add the key

```js
this.todos.push(map({}))
```

and in handleChange

```js
todo.set('text', event.target.value)
```

**Comment by hnordt** [comment]
You are the best @AriaFallah ! Thank you.

About the key part, please read react index as key

**Comment by AriaFallah** [comment]
@hnordt ah that `key` post makes sense, but perhaps you should find something other than `text` to use there if it's going to break the rerendering.

**Comment by hnordt** [comment]
Yeah, I’ll assign an UID. I used text just for demo purposes.

**Comment by AriaFallah** [comment]
@hnordt actually after thinking about it...does it matter what the key is when you're using MobX? MobX will rerender the component whenever there is a change regardless of what React thinks has changed.

**Comment by hnordt** [comment]
I don’t know.

Anyway as a best practice I’ll always set an unique key.

**Comment by mweststrate** [comment]
@AriaFallah yes it still matters. MobX doesn't need it, but the React reconciler does need stable keys. Without it React will throw away and recreate your components whole the time. And MobX can't optimize that :)

**Comment by hnordt** [comment]
@AriaFallah 

We use `map` for dynamic observables.

So why always use `map`? The main reason is that `const obs = map({ hello: 'world' })` is slower than `const obs = observable({})`?

**Comment by mweststrate** [comment]
@hnordt maybe you can best compare it with Java; use maps if you have a dynamically keyed collection with uniform values. Use objects for anything with (roughly) predefined attributes.

**Comment by hnordt** [comment]
Thank you @mweststrate, unfortunately I don't know Java and your explanation doesn't helped me :(

**Comment by AriaFallah** [comment]
@hnordt 

To me the difference isn't necessarily about speed, but about semantics. It's almost like `let` vs `const`.

When you create an observable object, its keys are constant. You're saying that it is a normal object with all the keys it ever needs. Its values can change, but you're never going add or remove keys from it or want to observe the adding and removing of keys.

With map there are now three differences I have noticed.

1. Difference in API. You cannot use it like a regular object. Instead you must use `.get()` and `.set()`
2. Difference in meaning. You are saying that the keys inside of it are not constant. They will dynamically be added and removed.
3. Difference in level of observability. The main thing is that you can observe the adding and removing of keys. Also this one isn't really apparent in the docs, but it is easier to report an entire MobX map as observed inside an `autorun` because of the `.toJs` function. With an observable object, it's much harder to observe the whole entire thing.

**Comment by hnordt** [comment]
Thank you @AriaFallah 👍
