### ISSUE TITLE
Size of transpiled classes with decorators vs plain observable objects

### ISSUE THREAD

**Issue by manuschillerdev** [mobxjs/mobx#2317]
**Disclaimer:** As suggested in the issue template I tried posting this on the mobx spectrum chat, but I had no luck getting an answer. So I'm going with a regular issue. Sorry for cross posting!!

---
I noticed that the transpiled size of a class using decorators is way larger than when I just use a plain object.
Example:
class based:
https://www.typescriptlang.org/play/?experimentalDecorators=true#code/JYWwDg9gTgLgBAbzhARgZwKZQG4EMUA2GANHAMYTgCuMGAJqbmTMBAHZwC+cAZlJXADkIVAA9BAbgBQUgPSzyBXGjTkIdDFLJKVcAApY07RFLhm4AAVSYc+Ir2BQ0MAHK4QGOAF4hIYGQALXAwCSVNzK3QsPEJPHVd3Tx9BACtoOlw2MPCzCwpqWjo4AHMMeB4qAgI3DwAKAEoTc2a4KDKqKA4AAwASBBgA4DQAOh5HZxqMbj6BoeH4yc4u6WbOGWaLJhZjYray2rZEgC44ZyhgNmLGhByW3CJYWq6ACRCCCFI+w48l+pXzNZrIA
plain object:
https://www.typescriptlang.org/play/index.html?ssl=4&ssc=17&pln=4&pc=24#code/JYWwDg9gTgLgBAbzhARgZwKZQG4EMUA2GANHAMYTgCuMGAJnAL5wBmUlcA5CKgB6cBuAFBCKAOzTwwWNBDFwAvMnRY8hDAAoEQuLtbAoksbhAYAXFxDAyAC1wYCnYjr0FcRk+a4AraHVxiTi66AOYY8CxUBATGphoAlIjBerpQ4VRQ8gAGACQIMDbAaAB0LAYepsx5BUXFbhUYjFnCKYzOKSFp4RYasV6SUMBiIYkKAHxJKSm4RLAaWQASDgQQpHl9TfEteoxCjPFAA
regarding functionality both variants are equally useful to me.
1) is this class based output realistic or will it be optimized further by regular build setups?
2) what benefits do classes with decorators have over a plain object? 

Thanks a lot for you input!

**Comment by FredyC** [comment]
If you don't particularly like decorators, don't use them. You might make yourself service because there is a bunch of other issues with them and given the specification is not finished and might not ever be, it's sort of wrong to bet in that direction. We are even considering deprecating decorators altogether (https://github.com/mobxjs/mobx/issues/2288).

**Comment by mweststrate** [comment]
One thing to keep in mind with plain objects is that they don't share their
methods on a prototype, like a class does. Although you could achieve that
by using a prototype with Object.create and hoisting the methods. In most
cases it probably really doesn't matter, but just to signal that comparing
plain objects with classes is a little bit comparing oranges with apples.
Likewise you don't pick arrow functions over plain functions (I hope)
because it is less characters, but because the one or the other has better
fitting semantics.

**Comment by manuschillerdev** [comment]
sorry for my late response!!

> If you don't particularly like decorators, don't use them. You might make yourself service because there is a bunch of other issues with them and given the specification is not finished and might not ever be, it's sort of wrong to bet in that direction. We are even considering deprecating decorators altogether (#2288).

We actually do like decorators a lot and use them in a fairly large codebase without problems for over three years now.  But we stumbled across the "verbose" output after transpilation and were wondering if that could be optimized.

> One thing to keep in mind with plain objects is that they don't share their
methods on a prototype, like a class does. Although you could achieve that
by using a prototype with Object.create and hoisting the methods. In most
cases it probably really doesn't matter, but just to signal that comparing
plain objects with classes is a little bit comparing oranges with apples.
Likewise you don't pick arrow functions over plain functions (I hope)
because it is less characters, but because the one or the other has better
fitting semantics.

thanks a lot, @mweststrate that makes sense 👍

**Comment by FredyC** [comment]
Well, meanwhile it became official and next major [MobX 6 will be without decorators](https://github.com/mobxjs/mobx/issues/2325) 🚀

**Comment by mweststrate** [comment]
P.s. did you configure tslib for your project? Most of the code should exists once in your project and not for every class.

**Comment by spion** [comment]
> Just so you know, meanwhile it became official. The next major MobX 6 will be without decorators

Since when is a "proposal" official?
