### ISSUE TITLE
Does "Combining multiple stores" recommendation make sense?

### ISSUE THREAD

**Issue by nareshbhatia** [mobxjs/mobx#2354]
For quite some time, I have been following the [Combining multiple stores](https://mobx.js.org/best/store.html#combining-multiple-stores) recommendation in the MobX documentation. Recently I nave been contemplating breaking up my root store into multiple smaller stores to make my application more modular. Wanted to get an opinion from this group before I go ahead with this.

### Motivation
A giant root store makes it very difficult to create standalone reusable components. For example, if a React component needs only one sub-store, it still has to know about the root store and get the sub-store from it. This approach also makes testing very difficult - even simple tests that need one sub-store now requires the entire root store to be instantiated.

### Solution - Multiple standalone stores shared via multiple contexts
This allows me to create reusable components that know only about the stores they need. Thus these components can even be created in separate libraries and pulled into the main application with ease. This approach is also suggested by @kentcdodds in his article [How to use React Context effectively](https://kentcdodds.com/blog/how-to-use-react-context-effectively).

### Example
In the example below, we have two stores that are provided at the highest level of the app - `AccountStore` and `OrderStore`. The `OrderList` component only needs the `OrderStore` and gets only that. This makes the component very reusable - we could create a standalone library that defines `Order`, `OrderStore` and `OrderList`, and it would not have to know anything about accounts.

```
class AccountStore {
    ...
}

class OrderStore {
    ...
}

const AccountContext = React.createContext<AccountStore>(new AccountStore());
function useAccountStore() {
    return useContext(AccountContext);
}

const OrderContext = React.createContext<OrderStore>(new OrderStore());
function useOrderStore() {
    return useContext(OrderContext);
}

// ------ App.tsx -----
const App = () => {
    return {
        <AccountContext.Provider value={new AccountStore()}>
            <OrderContext.Provider value={new OrderStore()}>
                <Router />
            </OrderContext.Provider>
        </AccountContext.Provider>
    }
};

// ----- OrderList ------
const OrderList = observer(() => {

    const orderStore = useOrderStore();

    return (
        // use orderStore to render the list of orders
    );
});
```

**Comment by FredyC** [comment]
I would say that whatever makes you feel good about your code is good to approach :) Sounds a bit political answer, but that's how it is. MobX does not impose any strict rules about it. Best practices are probably outdated quite a lot, mostly coming from the era of Redux that was about a single root store too.

Root stores are convenient for a developer because you can reach anything from anywhere. That might be important for agile projects. One day your boss comes in and wants a feature that requires you to access the store that's pretty much separated. And you have to find a way how to reach it and that can be really messy. It's really hard to predict what crazy ideas business people can come up with :)

Article from Kent is nice but pretty much irrelevant for MobX world where context value is stable and your components are subscribing to it. I don't see where he is suggesting multiple libraries, but it surely can be useful. Just don't over-engineer it :)

**Comment by nareshbhatia** [comment]
Thanks @FredyC - good points! In my case, I am finding that a single root store is causing a hinderance in the sense that I can't reuse components created for one application in another - they carry the baggage of the entire root store created for the original application. So breaking up to root store makes me feel good :-).

As for Ken's article, yes, it has nothing to do with MobX. I am simply referring to his suggestion to create multiple logically separated contexts:

> Remember that context does NOT have to be global to the whole app, but can be applied to one part of your tree and you can (and probably should) have multiple logically separated contexts in your app.

**Comment by FredyC** [comment]
> is causing a hinderance in the sense that I can't reuse components created for one application in another

Well, you can keep the root store, but abstract the access to it. For example, a custom hook which can have useLocalStore() and assembling together what's relevant for the particular set of components/feature.

From my experience, it's not that common to reuse a component as-is in multiple projects that would have some logic attached to it. Since you are referring to Kent, I would recommend you different article: https://kentcdodds.com/blog/aha-programming

![image](https://user-images.githubusercontent.com/1096340/81574356-fc4ccd00-93a5-11ea-84e4-28259c29de07.png)

**Comment by nareshbhatia** [comment]
@FredyC, I like your useLocalStore() idea - it gives me the best of both worlds.

Closing the issue, but others are free to comment on how they deal with multiple stores.
