### ISSUE TITLE
Stale dependencies should not be used

### ISSUE THREAD

**Issue by canonic-epicure** [mobxjs/mobx#2377]
Hello,

Found a case when a stale dependency is affecting a graph.

Use this sandbox to reproduce: https://codesandbox.io/s/cool-murdock-pu0tc?file=/src/index.js

What happens in the test:

1. A small graph is established, in which one node is "dispatcher" - contains reference to another node.
```ts
const i1 = observable.box(0);
const i2 = observable.box(1);
const dispatcher = observable.box(i1);
```
2. Computed value depends on dispatcher and the node it contains
```ts
let counter = 0;
const c1 = computed(function() {
  counter++;
  return dispatcher.get().get() + 1;
});
```
3. First iteration, dispatcher contains reference to `i1`, we compute the value of `c1` based on the value of `i1`
4. We write `i2` to dispatcher and re-compute `c1`, which now depends on `i2` instead of `i1`. The dependency from `i1` to `c1` becomes stale.
```ts
dispatcher.set(i2);

is(counter, 0);

// during these reads the `c1` will acuire a dependency on `i2` and old dependency on `i1` will become "stale"
is(c1.get(), 2);

is(counter, 1);
```
5. We write to `i1` and this write is expected to not affect `c1`. In reality `c1` becomes stale and recomputed.
```ts
// this write should not affect `c1` since it depends on `i2`
i1.set(10);

is(counter, 0);

is(c1.get(), 2);

is(counter, 0); // <---  THIS THROWS
```

**Comment by mweststrate** [comment]
I'm not sure what problem you are trying to solve here, but note that using
computeds without observing them will always suspend them by default. The
counter is increased simply because calling c1.get() will re-evauluate it,
as computeds won't memoize if not observed (unless keepAlive option is set
to force that). So if you want to reason about how computeds work, please
establish observers, as their behavior without observers isnt really
interesting. This is explicitly explained at
https://mobx.js.org/refguide/computed-decorator.html, 3th and 4th
paragraph.

**Comment by canonic-epicure** [comment]
Thanks for the explanations, it seems to work with `{ keepAlive : true }`. Closing it.
