### ISSUE TITLE
your documentation website

### ISSUE THREAD

**Issue by gravitymedianet** [mobxjs/mobx#2378]
We are open to your questions or discussion, but keep in mind it might take a while for us to respond. For a faster response, you can try the following channels.

-   MobX Spectrum community: https://spectrum.chat/mobx
-   StackOverflow (`mobx` tag): https://stackoverflow.com/questions/tagged/mobx

I want to share 2 things, probably will upset the site owners. But it is just a suggestion. --

1. Please consider restoring the color to your website. I just went to it, everything is gray and honestly it is an eyesore, and very difficult to read anything.  The monotone gray is a literal eye ache.

2. Why do you feel the need to enter politics into your website? I mean, it's your site and you will do what you want. But it has nothing to do with Mobx and honestly should be somewhere else. We are here to learn about Mobx, not be lectured on politics.

**Comment by FredyC** [comment]
**This is just my personal opinion, I am NOT speaking on behalf of the MobX team.**

I kinda feel your pain. I don't even know what exactly is happening and why. I like my sanity enough not to really care. I can imagine it's a sensitive topic for some people. I don't judge anyone, but I do agree it shouldn't be spreading to the tech industry.

React team decided earlier to do the same, but now I see they just left the banner but reverted back to colors. That's a good solution in my opinion and I would vote for doing the same here and [Immer](https://immerjs.github.io/immer).

**Comment by gravitymedianet** [comment]
> **This is just my personal opinion, I am NOT speaking on behalf of the MobX team.**
> 
> I kinda feel your pain. I don't even know what exactly is happening and why. I like my sanity enough not to really care. I can imagine it's a sensitive topic for some people. I don't judge anyone, but I do agree it shouldn't be spreading to the tech industry.
> 
> [React](https://reactjs.org/) team decided earlier to do the same, but now I see they just left the banner but reverted back to colors. That's a good solution in my opinion and I would vote for doing the same here and [Immer](https://immerjs.github.io/immer).

Thank you. It is for sure a touchy subject, but I think there are better places to communicate one's political views.

**Comment by koukimetal** [comment]
`$('body').style.filter = 'grayscale(0%)'`

**Comment by mweststrate** [comment]
> 1. Please consider restoring the color to your website

Fair enough, I'll roll the colors back next week (I actually liked it esthetically, but I've seen them in normal colors too often most probably :-P). 

> 2. Why do you feel the need to enter politics into your website?

Firstly, I think this is a welcoming gesture to those coming from underrepresented communities in a western white male dominated scene. (yes, obviously there are more, and I hope reaching out to one will make others feel welcome as well, however tiny the gesture)

I agree that I don't think either politics should have a much place in world wide OSS projects. Especially if they are domestic. So personally I wouldn't put on statements about trump, ICE, libs / dems, whatever. These are US domestic issues and can be addressed through democratic means. This however is a philosophical statement, not a political one; that all life is dignified, including black lives. I mostly assumed that was a no-brainer for most people so far, but apparently it isn't :)

So that is the message I'd love to repeat and ask to respect when using this library. See it as accepting a cookie banner or ads when using a site. Since MobX is free to use I don't think that is too much to ask. If you think not all life is dignified or that black lives don't matter (I mean 'you' here as a general statement for any future readers, I'm not implying any positions of anyone in this thread), then I'd want to ask to forego this library out of respect for our disagreement. 

It's not something that is going to be policed, licensed, shamed or checked, I trust everyone's consciousness in this (shaming is happening too much already). In fact, you are still completely free to use MobX even when we disagree because I like my work to be available to everyone regardless worldview (and that is also what the license implies), but at least you know my position and please don't use this lib for evil in general :)

**Comment by urugator** [comment]
> it is an eyesore, and very difficult to read anything. The monotone gray is a literal eye ache.

Holy smoke, reading books must be excruciating... thank god you ain't colorblind.

**Comment by gravitymedianet** [comment]
> > 1. Please consider restoring the color to your website
> 
> Fair enough, I'll roll the colors back next week (I actually liked it esthetically, but I've seen them in normal colors too often most probably :-P).
> 
> > 1. Why do you feel the need to enter politics into your website?
> 
> Firstly, I think this is a welcoming gesture to those coming from underrepresented communities in a western white male dominated scene. (yes, obviously there are more, and I hope reaching out to one will make others feel welcome as well, however tiny the gesture)
> 
> I agree that I don't think either politics should have a much place in world wide OSS projects. Especially if they are domestic. So personally I wouldn't put on statements about trump, ICE, libs / dems, whatever. These are US domestic issues and can be addressed through democratic means. This however is a philosophical statement, not a political one; that all life is dignified, including black lives. I mostly assumed that was a no-brainer for most people so far, but apparently it isn't :)
> 
> So that is the message I'd love to repeat and ask to respect when using this library. See it as accepting a cookie banner or ads when using a site. Since MobX is free to use I don't think that is too much to ask. If you think not all life is dignified or that black lives don't matter (I mean 'you' here as a general statement for any future readers, I'm not implying any positions of anyone in this thread), then I'd want to ask to forego this library out of respect for our disagreement*
> 
> It's not something that is going to be policed, licensed, shamed or checked, I trust everyone's consciousness in this (shaming is happening too much already). In fact, you are still completely free to use MobX even when we disagree because I like my work to be available to everyone regardless worldview (and that is also what the license implies), but at least you know my position and please don't use this lib for evil in general :)
> 
> EDIT *: not sure if I actually feel this so strong. Good reflection question. One one hand I don't care, on the other hand I do. Who do / don't I want to benefit from stuff created and shared🤔

Thanks for taking the time to reply. I do understand your point of view and I appreciate the time you took to reply. I will reiterate my original point -- it is your website and you may do as you please.

My only point is, I think it would take a seriously demented or evil person to not know that Black lives matter. But when you put any kind of political messages on non-political spaces, it is a sort of lecturing. And you are lecturing to people who already know that Black lives matter. So it kind of comes across as patronizing.

I leave you with this snippet from an interview with Morgan Freeman, an amazing spirit and example. The full article and video can be found here:

https://www.snopes.com/fact-check/morgan-freeman-on-black-history-month/

----

WALLACE: How are we going to get rid of racism until …?

FREEMAN: Stop talking about it. I’m going to stop calling you a white man. And I’m going to ask you to stop calling me a black man. I know you as Mike Wallace. You know me as Morgan Freeman. You’re not going to say, “I know this white guy named Mike Wallace.” Hear what I’m saying?

---

Your library is great, you are great, and we appreciate your creativity. It has helped probably millions of people worldwide.

Do as you wish :)

**Comment by gravitymedianet** [comment]
> > it is an eyesore, and very difficult to read anything. The monotone gray is a literal eye ache.
> 
> Holy smoke, reading books must be excruciating... thank god you ain't colorblind.

You don't know anything about me or my eye condition. I have retinal detachment and I have trouble with solid bright colors and whites. Please think twice before you utter such statements. It is literally an eyeache--I am not joking.

**Comment by urugator** [comment]
> You don't know anything about me or my eye condition.

Maybe I would know, if your OP would be actually concerned about accessibility, but it doesn't seem to.

**Comment by gravitymedianet** [comment]
> > You don't know anything about me or my eye condition.
> 
> Maybe I would know, if your OP would be actually concerned about accessibility, but it doesn't seem to.

**Comment by mweststrate** [comment]
Done, should be updated in a bit.
