### ISSUE TITLE
github Releases is error

### ISSUE THREAD

**Issue by stfenjobs** [mobxjs/mobx#2385]
like this https://github.com/mobxjs/mobx-state-tree/issues/1538

**Comment by stfenjobs** [comment]
too old

![image](https://user-images.githubusercontent.com/6580897/85918849-ce114700-b898-11ea-8de6-d4bed9c91e12.png)

**Comment by mweststrate** [comment]
We don't release through github. Check NPM

**Comment by FredyC** [comment]
I have kinda fixed this because it does feel confusing indeed with the latest GitHub overhaul.

![image](https://user-images.githubusercontent.com/1096340/85919709-27b04c00-b86e-11ea-9477-37d8095e2001.png)

**Comment by mweststrate** [comment]
I'm wondering how releases actually work, I always assumed it would just
pick up git tags. But maybe it doesn't. Or we don't tag properly

**Comment by FredyC** [comment]
You are using releases in Immer repo, so how come you are surprised by it. It's done by the semantic-release. We couldn't use that here due to V4/V5 problem, but perhaps with V6, it would make more sense.

We are tagging it here correctly, but GitHub is unable to automatically create release just based on the tag because it doesn't know if it's the latest or prerelease.
