### ISSUE TITLE
ES 2020 build

### ISSUE THREAD

**Issue by KishanBagaria** [mobxjs/mobx#2403]
We target the latest browsers that support all modern JavaScript features. We're currently using the ES6 build (`node_modules/mobx/lib/mobx.es6.js`) of mobx.

Can you also publish a build targeted at the latest JavaScript version? It'll result in better compression and faster performance. [Instagram ships modern bundles to modern browsers](https://instagram-engineering.com/making-instagram-com-faster-code-size-and-execution-optimizations-part-4-57668be796a8).

**Comment by FredyC** [comment]
Yea, we are not Instagram, so that's wild comparison :) Let's leave this open and boil over time. Unless more people are going to require it, it's not worth the effort. It's just theoretical optimization. 

Besides, there is currently MobX 6 in works, we won't be doing that for current versions.

If you really want that, I recommend you Yalc tool to basically make your own build.

**Comment by mweststrate** [comment]
If someone wants to organize it on the mobx6 branch, contributions welcome.
