### ISSUE TITLE
mobx 6 not throwing an error (only warning) if using enforceActions, is this by design?

### ISSUE THREAD

**Issue by johot** [mobxjs/mobx#2417]
It seems mobx 6 will only do a `console.warn` when using `enforceActions`. What is the reasoning for this? I loved the fact that it forced me to do things the "correct way" in previous mobx versions :) 

If this is intended could an option be added to force it to throw also?

Thank you for all your great work!

**Comment by mweststrate** [comment]
Yeah this is intended, it is not hindering anything from a
technical perspective, and yet another config option seems like overkill.
Most other warnings don't throw either, so this is a bit more consistent
and less obtrusive, especially since this has become the default, so there
is no longer an opt-in.

**Comment by nixaboo** [comment]
I would rather it throws, it makes more sense to me-> especially since it actually performs the state change.

For those intrested in a dirty-hack:

let warn = console.warn;
console.warn = (t) => {
	if (t.indexOf('[MobX] Since strict-mode is enabled') >= 0) {
		throw t;
	}

	warn(t);
};


It's not ideal but better than forking MobX :)

**Comment by mweststrate** [comment]
tip: use patch-package instead

**Comment by nixaboo** [comment]
Niiice! Didn't know this existed, very useful!

**Comment by upsuper** [comment]
Hey @mweststrate,

In Canva, we find it hard to enforce this rule across a massive codebase and large number of developers in the organization without having it throw an error. Very few developers and basically no reviewers would notice an extra warning a change introduces if everything works as expected otherwise. So we also want it back to throw an error instead of just issuing a console warning.

I would also argue that if it doesn't interrupt the normal flow, it is not really "enforcing" anything, just warning, so the name of the option is very misleading.

I can see in https://github.com/mobxjs/mobx/commit/f60c913dc5b887bd647cfe41d29abff6b9971d91, you changed its behavior because you want to make it default without breaking too much existing code that doesn't enforce it currently. I would suggest that a new option should be introduced for the purpose, something like `requiresActions` to be consistent with other options that warn rather than throw. Alternatively, maybe consider making `enforcingActions` accepts more options like `{ on: 'always' | 'observed', level: 'warn' | 'throw' }`, and map the existing string values to `level: 'warn'`.

It would be really unfortunate if we have to patch an actively maintained package like MobX, especially given that we use it in multiple packages.

Could you reconsider the decision?
