### ISSUE TITLE
How to handle observable and computed properties in combination with spread operations

### ISSUE THREAD

**Issue by lukasbash** [mobxjs/mobx#2442]
I have a pretty general question about the usage of mobx' utils in combination with spread/copy operations of javascript.

I have the following architecture:

1. From a server response I get a list (or actually a tree) of objects with some properties. The structure here does not matter at all.
2. This response will be mapped to an instance of a class. The class could look like this:
```
class Foo {
  @observable something = 1;
  @computed get doubleSomething() { return this.something * 2 }
}
```
3. The final set of data will be used inside a React (class) component to display it for the user. I am using an external (3rd party) framework to provide e.g. drag and drop functionality for the items that are rendered. This framework also provides a React component where I can just pass in the set of items (as an array) and handles all the drag and drop functionality (i.e. sorting, adding, grouping, removing and more). So far so good.
4. Now the problem arises. The framework itself follows a very simple coding pattern. Whenever something happens that could modify an input, they copy/dereference the input values. Lets take this example:
```
...
// remove item.selected from list
newList = newList.map(item => ({ ...item, selected: false }));
...
``` 
5. Because they are doing this, I basically lose all the mobx tracking information. After I get the callback of a new (or modified) list, my class instances are objects only. Not only that the `getters` are dropped by javascript itself natively (because it only copies own enumerable properties), the UI component that should track changes of the observable does not work anymore as well.

My question is how to handle those things. I have to rely on several third party modules and I just cannot fork or monkey patch all of those where those problems happen. What is the best approach for fixing/handling this? Do you have any idea?

P.S.: Storing the data twice on the client (e.g. to mock some kinda proxy object where I "follow" the original object if the new one is "broken") is not an option as there can be thousands of objects and they can be very large.

**Comment by urugator** [comment]
You should convert the observables to plain JS before passing them to 3rd party lib and then map the data provided by lib back to observables. I suppose you would need a similar transformation layer even without mutable state, because it's unlikely that the shape of your state exactly matches the API of the lib.

**Comment by lukasbash** [comment]
@urugator Thank you for your reply!
Converting the observables to plain javascript (I assume you mean the classic `toJS` utility from mobx) would not be a problem. How would you convert the new items back to observables though? If I would have to iterate the whole array everytime something changes, then the performance would not be that good.
Do you have a concrete code example that does not have a huge runtime?

**Comment by mweststrate** [comment]
Probably it is better to clone shallowly if you can (e.g. .slice() or `.map (x => ({...x}))` to limit the clone depth. 

That being said, this sounds to me like a problem with your drag and drop library, general purpose libraries typically don't emit state, but events, (e.g. onSelected, onDrop) etc, to prevent coupling to the way state is managed. So if such events aren't exposed, I'd pick it up with the maintainers of the drag and drop library instead, otherwise this is going to hit you in many different ways (for example: you want to send changed items to the server, you want to support concurrent drag and drop from mulitple users), these are all patterns that are very hard to express when sending full state back and forth, but trivial when using events. For the same reason React itself recommends to use `value` + `onChange` for `input`'s; it moves back the responsibility of state updates to the state owner.

**Comment by urugator** [comment]
Ideally the lib would tell you what happend (eg index 5 moved to index 2) so you could apply the change to your state, quess this is not the case.
Could you have a seperate non-observable array like  `[{ id: 'foo1' }, { id: 'foo2' }, ...]` and then acquire the actual item in some render callback `(item) => fooStore.get(item.id).content`?
