### ISSUE TITLE
MobX documentation encourages circular dependency between stores

### ISSUE THREAD

**Issue by NikolajLeischner** [mobxjs/mobx#2483]
The MobX documentation describes a pattern of having a "root store", which has references to every other store, and injecting it into every store: https://mobx.js.org/defining-data-stores.html

This is effectively a circular dependency between all stores, which is commonly seen as an anti-pattern.

Two immediate negative effects of this are:
* Worse testability - every unit test of a store needs a mock of the root store.
* Because every store can access every other store, developers that aren't careful end up writing spaghetti code.

Why recommend this, instead of explicitly injecting the dependencies a store actually needs?

**Comment by kubk** [comment]
Completely agree, I also always pass dependencies explicitly to avoid Service Locator anti-pattern. Dependency Injection doesn't hide dependencies (unlike Service Locator) making code more testable and straightforward.

**Comment by FredyC** [comment]
I haven't really read that recommendation, but generally, I would say it's more approachable to newcomers to have a single state. Especially if they are converting from Redux. The mentioned "negative effects" are sort of opinionated and manageable overall.

Either way, I think it would be most welcome if you are willing to write up an alternative approach that feels easier for you.

**Comment by NikolajLeischner** [comment]
I've actually had discussions with people coming from Redux, who cited that specific recommendation from the documentation as off-putting and as an argument for why MobX in their mind was no good alternative to Redux.

I'd be happy to provide a suggestion, I'll write something up within the next few days :)

**Comment by mweststrate** [comment]
MobX doesn't technically zero care about how you organise your store. The documented pattern is just one of dozens approaches that could be taken in organising models / store / views / data. It was written because "we don't care" was too much freedom for many to handle. So the documentation is just a way in which it could be done, and you should definitely not read too much into it. If you have any argument to deviate from it, by all means do. 

DI can be great, but others find it confusing. But most importantly, if we would use a DI container, it would immediately be read as 'mobx does need a DI container'. Like our current docs are sometimes already read as: MobX needs a single root container. That all isn't the case; mobx is just about propagating state changes from A to B. How that state is organized is just as irrelevant to MobX as in which folders you put your components. 

So please don't read the docs as 'this is the best way to architect your application', but rather 'if you have no clue how to get  started, here is *a* way'. That is what we tried to say in the intro:

> This section contains some of the best practices for building large scale maintainable projects we discovered at Mendix while working with MobX. This section is opinionated and you are in no way forced to apply these practices. There are many ways of working with MobX and React, and this is just one of them.
