### ISSUE TITLE
Loading indicator change for long-running synchronous functions

### ISSUE THREAD

**Issue by jefffriesen** [mobxjs/mobx#249]
I am using mobx successfully building a non-trivial app. But I'm running into a problem that I wouldn't expect. I'm trying to show a loader before a long-running calculation and hide it after it's done. I've done it successfully with async functions, like in the examples:
```
  loadTodos() {
    this.isLoading = true;
    this.transportLayer.fetchTodos().then(fetchedTodos => {
      todos.forEach(json => this.updateTodoFromServer(json));
      this.isLoading = false;
    });
  }
```

But when I set an observable on both sides of a synchronous, long-running operation, the initial setting doesn't rerender the view that is observing it. Inside my observable store class I have something like this:
```
  @observable isUpdating = false

  updateApp() {
    this.isUpdating = true    // This does not re-render the view that depends on it
    this.calc = looongCalculation()   // Over 4 seconds to calculate
    this.isUpdating = false
  }
```

Inside my react component (which uses `@observer`), I have something like this:
```
  update = () => {
    this.props.store.updateApp()
  }

  render() {
    const isUpdating = this.props.store.isUpdating
    console.log('isUpdating: ', isUpdating)
    return isUpdating
      ? <Button icon='cog' spin>Updating</Button>
      : <Button onClick={this.update}>Update</Button>
  }
```

This outputs in the console:
```
isUpdating: false     // initial render
isUpdating: false     // render after updating
```

When isUpdating is set to true, the view that depends on it never re-renders. This calculation takes over 4 seconds so I would think that would be enough time for the view to render twice.

Is this a bug or am I likely doing this incorrectly?

Thanks

**Comment by AriaFallah** [comment]
@jefffriesen 

Gonna wing it here since I'm not 100% sure of this, but could you try updating your observable values using `set` and getting your observable values using `get`?

So for example:

```js
const isUpdating = this.props.store.isUpdating.get()

// ...

this.isUpdating.set(true)
```

There are some docs on the rationale behind what I'm proposing here: http://mobxjs.github.io/mobx/refguide/observable.html#primitive-values-and-references

**Comment by mweststrate** [comment]
@jefffriesen that that doesn't work is simply a combination of the fact that JS is single threaded and React. MobX will actually signal your component to re-render twice (you can verify that by logging `isUpdating` in an autorun for example).

React doesn't render and flush the DOM immediately (this is an optimization to prevent to much redraws), but only on a next tick. But since your calculating blocks the CPU for 4 seconds and JS is single threaded, React cannot repaint flush to the DOM as that next tick will be delayed for 4 seconds. (Nor would it be able to handle your event handlers etc in the mean time)

Your issue would be solved by simply setting `isUpdated` to true, and do the rest of your function in a `setTimeout(() => func, 10)`. However note that it is always a bad idea to block the CPU for such a long time, as your app will feel completely unresponsive during that time. You might consider breaking it up in smaller tasks and schedule those, or use webworkers. 

I hope that that explains why you don't see the update.

**Comment by AriaFallah** [comment]
@mweststrate so I was completely wrong 😅 . When you use the observable decorator I assume `.get()` and `.set()` are called implicitly.

**Comment by jefffriesen** [comment]
@AriaFallah Thanks for the suggestion. 
When I do this:
```
const isUpdating = this.props.store.isUpdating.get()   
// TypeError: this.props.store.isUpdating.get is not a function
```
Same thing with `.set()` - not a function. 

I've also tried to wrap `this.calc = looongCalculation() ` in a `transaction` with no luck.

**Comment by AriaFallah** [comment]
@jefffriesen I realized I was completely mistaken my bad. Please take @mweststrate's advice instead.

**Comment by jefffriesen** [comment]
@mweststrate Great explanation, thank you. Basically, the long-running function is preventing the tick that would render it from happening. That makes sense. I'll do the setTimeout or do it in a web worker.
