### ISSUE TITLE
Can I use @action.bound for modifying states, instead of @action?

### ISSUE THREAD

**Issue by moonformeli** [mobxjs/mobx#2512]
The example from the official Mobx documentation is quite confusing to me. It says you should only use `@action` when to modify a state. But the example of `@action.bound` also changes the state value inside.

```ts
// example
class Ticker {
    @observable this.tick = 0

    @action.bound
    increment() {
        this.tick++ // 'this' will always be correct
    }
}
```

So, if it's okay to use `@action.bound` instead of `@action` for chainging state values, why should I care about using the latter one?

FYI, I'm currently using Mobx 4

**Comment by mweststrate** [comment]
Make sure you understand the meaning of `this` and `function.bind` in
JavaScript (for example checkout
https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/scope-closures). The
difference is that `action.bound` will automatically bind for you as a
convenience, and `action` won't (so it behaves like a normal method). It
doesn't further affect the working of actions itself, but for you / your
callsides it might matter whether you want a function bound to 'this' or
not.

Once you grok the concepts linked, you'll also realize that you could be
using arrow functions + action instead of action.bound. I recommend to
learn those concepts as they are very fundamental to the JavaScript
language and will prevent you a lot of hair pulling in the future. But
these concepts are further unrelated to MobX.
