### ISSUE TITLE
map.clear incorrectly registers a dependency

### ISSUE THREAD

**Issue by liron00** [mobxjs/mobx#256]
The implementation of `map.clear()` accesses the map's observable `._keys` member.

If I call `map.clear()`, I'm not necessarily ever reading the map anywhere in the current computation. Therefore the current computation shouldn't be re-run later if/when the map's set of keys gets mutated.

**Comment by mweststrate** [comment]
Thanks for finding this one! That is incorrect indeed. As a temporarily workaround you can use `mobx.untracked(() => map.clear())`

**Comment by liron00** [comment]
Thanks. Speaking of `mobx.untracked`, I do believe it needs to be in the production API.

Meteor's `Tracker` package is quite similar to mobx and it offers [Tracker.nonreactive](http://docs.meteor.com/api/tracker.html#Tracker-nonreactive).

One use I have for it is in my `LiveQuery` class, which gets constructed with a specification of a Firebase query path like '/users/john-smith' and then makes liveQuery.value an observable value which live-tracks the contents of that endpoints.

Consider this excerpt from https://github.com/liron00/mframework/blob/master/liveQuery.js#L79:

```
@computed({asStructure: true}) get value() {
  if (!this.isActive) {
    throw new Error(`${this} can't get value when inactive`)
  }

  return this._value
}
```

This should probably be `if (!mobx.untracked(() => this.isActive))` because I don't think a dependency on the observable `this.isActive` makes sense.

**Comment by mweststrate** [comment]
@liron00 I doubt whether in your case it makes sense to make `isActive` observable at all? Otherwise `untracked` is nice to use here indeed.

@liron00 In MobX 2.2 a separate concept will be introduced, that should largely remove the need of `untracked` in general (but not in the above example), namely `action`. Actions are intended to modify state and hence are always run with `untracked` and `transaction`.

So if an action is called by an autorun / observer, these kind of issues should not arise anymore.

**Comment by liron00** [comment]
I think it's reasonable to need `isActive` to be observable because I have a higher-level class that offers its own computed `.value` getter that looks something like this:

```
@computed get queryValue() {
  return this.liveQuery.isActive? this.liveQuery.value : undefined
}
```

Looking forward to seeing what you're doing with `action`.
