### ISSUE TITLE
computed with ifavailable cause Error

### ISSUE THREAD

**Issue by doxiaodong** [mobxjs/mobx#2619]
**Intended outcome:**
cause by Reflect.ownKeys
it is seem broken with JSON.stringify

**Actual outcome:**
![image](https://user-images.githubusercontent.com/6927481/99048422-7ddd1c00-25d0-11eb-9126-232818993c38.png)

**How to reproduce the issue:**
https://codesandbox.io/s/multi-selection-forked-vdjqn?file=/src/index.tsx

**Versions**

mobx@6.0.4
useProxies: 'ifavailable'

**Comment by urugator** [comment]
Minimal repro:
```javascript
const o = observable({});
autorun(() => {
  JSON.stringify(o);
})
```
Possible solutions:
a) Don't warn
b) Force user to provide own `toJSON` or use other means for conversion
c) When proxies are not available, add default `toJSON` to every observable object

**Comment by urugator** [comment]
Btw `toJS` has the same problem

**Comment by mweststrate** [comment]
This behavior is correct, as JSON.stringify would behave differently indeed a non proxy environment, and this error is an early warning for it. `toJS` should ideally not suffer from the same thing as it could default to using mobx own iteration mechanism. Feel free to file a separate issue for that.

**Comment by doxiaodong** [comment]
But same code work fine with mobx@5

**Comment by urugator** [comment]
Mobx5 required proxy support - it would not work at all in env without proxies, you had to use Mobx4 instead.
Mobx6 lets you decide - by `configure({ useProxies: "ifavailable" })`, you're saying - this code should work in any environment, but *if available* use proxies as internal implementation. So mobx will warn anytime your code would broke in non-proxy env.

**Comment by doxiaodong** [comment]
Yes, Mobx4 and Mobx5 is fine with JSON.stringify , but Mobx6 with `configure({ useProxies: "ifavailable" })`  is not. That means it's a breaking. By the way, I think it's better to throw warn for all cases of useProxies

**Comment by mweststrate** [comment]
It's breaking because it would break if you would run this code on Internet Explorer, just as this would break on Internet Explorer if you were running this very same code with MobX5 on Internet Explorer. Please read the conversation again, it errors _because you configured it to error_ as an early warning this _will_ not run on older browsers. If you want the MobX 4 behavior, put it on `useProxies: "never"`.

**Comment by urugator** [comment]
@doxiaodong In Mobx4 `JSON.stringify` may not work correctly - if you add or delete prop from the object it would NOT notify the `computed`. We don't warn in Mobx4, because the warning only works when proxies are available and Mobx4 does not have a proxy based implementation at all - so we simply don't have a way to warn in Mobx4 - but the code is still potentially broken (depends on usage).

**Comment by doxiaodong** [comment]
Thanks，I use `always` for proxy.
