### ISSUE TITLE
function-properties in observable objects are not enumerable

### ISSUE THREAD

**Issue by misantronic** [mobxjs/mobx#2629]
**Intended outcome:**

function-properties in observable objects are expected to be enumerable

**Actual outcome:**

function-properties are gone when iterating an observable object

**How to reproduce the issue:**

I created this example: https://codesandbox.io/s/jovial-black-rq0pw?file=/src/index.ts

The `onMore`-prop is actually not contained when calling `Object.keys(x.notification)` since functions are not enumerable in observable objects. I am coming from mobx 4 and this used to work and now it breaks my app in some cases, since I use spreading to pass observable-objects to components like `<Component {...notification} />`

**Versions**

Mobx 6

**Comment by urugator** [comment]
We may change it so that enumerability is respected, but I can't give you a promise atm, it's being discussed/worked on.

**Comment by urugator** [comment]
For the time being as a workaround try: 
```javascript
const obj = {
      text: "abc",
      onMore: action(() => {})
};
```
Or
```javascript
const obj = observable({
      text: "abc",
      onMore,
}, {
  onMore: false
});
```

**Comment by ConneXNL** [comment]
> ```js
> action(
> ```



> For the time being as a workaround try:
> 
> ```js
> const obj = {
>       text: "abc",
>       onMore: action(() => {})
> };
> ```
This seems to throw a warning for me:
`[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: ObservableObject@251.isOpen`

**Comment by mweststrate** [comment]
Please note that spreading observable objects into components as props is an anti pattern: https://mobx.js.org/react-integration.html#tip-grab-values-from-objects-as-late-as-possible. The idiomatic way to pass the notification down is `<Component notification={notification} />`, while making sure `<Component>` is an `observer`. 

If you can't make `Component` `observer` because it is not under your control, I recommend pass down properties down explicitly. Especially with actions you probably want to do that anyway to make sure callbacks are invoked by with the right context (`<Component title={notification.title} onSetTitle={(title) => notication.onSetTitle(title)} />` rather than `<Component {...notification} />` which will break if `notification.onSetTitle` wasn't bound)

**Comment by ConneXNL** [comment]
It seems **very unexpected** that properties may suddenly be removed from an object when enumerating, especially since imo mobx' power has always been that it makes you interact with the observables like they are native object/maps/arrays etc (with a little magic when you wrap them into observers). 

I can see how it is an anti-pattern but I've been using it mostly in tests and stories to quickly create a set of observable values that I then spread into a react component. When I upgraded to MobX 6 many of these stories broke. There might be tons of more use-cases but I think most important is that its just very DX unfriendly .

**Comment by airhorns** [comment]
I think it is worth mentioning that this change from 5 to 6 has a big impact on duck typing using the `in` operator. This is super necessary when using `mobx-state-tree` but applies to plain old `makeAutoObservable` class instances too.

Before we could pretty easily do something like this:

```typescript
class Image {
  highlight() { ... }
}

class Image {
  highlight() { ... }
}

const maybeHighlight = (node: Image | Paragraph | Spacer) => {
  if ('highlight' in node) {
    node.highlight()
  }
}
```

**Comment by airhorns** [comment]
Looks like https://github.com/mobxjs/mobx/pull/2641 might change some of this, but if I understand correctly, `flow`s won't be enumerable?

**Comment by mweststrate** [comment]
Note that class methods are never enumerable by default, unless you turn them into fields: https://www.typescriptlang.org/play?#code/MYGwhgzhAEAa0G8BQ1XQLYFMAuALA9gCYAUAlIkimgL5K1LD4B2E20AHtALzROYDucMpUYt8ITADoQ+AObEkAeQBGAK0zBsk2TkX8mABQBO+AA6Yj2AJ4ARTBGBGAlqez4jxWJNMm318wA00ABEWHhEwaRIUaIQ4lIy8gDkYQSESdBOTBxRSEA. But that isn't needed either for the `in` operator to work.  Could you provide a minimal code sandbox instead to demonstrate the problem?

Also note that `!!node.highlight` might suffice for your ducktyping?

**Comment by airhorns** [comment]
Alas, I have lied, you are right @mweststrate! My bad! The `in` operator works fine for auto-observed plain old mobx objects.

Here's a code sandbox explaining the issue from the MST perspective: https://codesandbox.io/s/loving-benz-3czkp?file=/src/index.ts

`in` returns what I would expect for plain old classes, for `makeAutoObservable` classes, but not what I'd expect for MST `types.model()`s. 

The `in` operator doesn't seem to need properties to be enumerable according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in), so apologies for the mistake. However, I think when invoking it on an mobx-state-tree node, MST ends up invoking some `has` check inside mobx proper which returns false. I am guessing that has something to do with the work done to support observable enumerability, but doesn't strictly related to the property being enumerable. Sorry for the noise here!

**Comment by mweststrate** [comment]
@airhorns I'd file that in the MST repository if it is still an issue after #2641 landed

**Comment by mweststrate** [comment]
6.1.0 has landed. Closing this issue now.
