### ISSUE TITLE
Changing/Deleting ObservableSet.value not trigger reactions

### ISSUE THREAD

**Issue by Aqours** [mobxjs/mobx#2679]
**Intended outcome:**
Reactions will trigger via ObservableSet.delete action or changing ObservableSet.value

**Actual outcome:**
Reactions will not trigger via ObservableSet.delete action or changing ObservableSet.value

**How to reproduce the issue:**
https://codesandbox.io/s/flamboyant-sara-csrle?fontsize=14&hidenavigation=1&theme=dark

**Versions**
4.15.7

**Comment by mweststrate** [comment]
By default Set will clone the values you put into to be able to make them
observable, which is why your `has(d)` prints false, and `delete(d)`
doesn't do anything, as d is not in the set, but a clone of it is.
Creating a shallow set (that doesn't convert values but stores them as is)
fixes your problem: let s = observable(new Set([]), { deep: false }); I
think a strong argument can be made that this is not the most sane default
:), but we cannot change it without releasing a new major. So feel free to
PR a warning on the docs! I guess people don't stumble more often on this
because storing complex objects in sets doesn't seem too common. For Maps,
the default is that we _dont_ convert the keys, but only the stored values,
to avoid similar confusion.
