### ISSUE TITLE
`when` sometimes not firing in MobX 6

### ISSUE THREAD

**Issue by RoystonS** [mobxjs/mobx#2703]
I'm currently upgrading a large (6500+ file) TypeScript codebase from MobX 5 to MobX 6. As would be expected with such a large codebase there have been a few problems.

I'm working through several thousand failing unit tests. My most immediate problem seems to be an odd interaction of class inheritance and `when`:

**Intended outcome:**

We're calling `when` from a base-class constructor, to queue up some behaviour once an object is in a 'ready' state.  With MobX 5 the `when` effect was correctly called.

**Actual outcome:**

With MobX 6 the `when` effect is no longer called even though observables have changed to make the predicate true.

**How to reproduce the issue:**

See CodeSandbox: https://codesandbox.io/s/mobx6-baseclass-when-ofsll

This is a non-React MobX 6 CodeSandbox which emits output to the console.  It consists of a BaseClass and a DerivedClass which extends BaseClass.  The BaseClass constructor uses `when` to subscribe to its own `isReady$` observable becoming true, and the DerivedClass constructor sets `isReady$` to be true.

But the `when` does not fire.

What's particularly interesting is that the `when` call _does_ fire if we remove the definition of `derivedObservable$` from the DerivedClass. Having extra observables in the derived class seems to be interfering with the operation of the `when` in the base class

(Note: this is a heavily distilled version of the actual code from our codebase so will look a little artificial.)

I can confirm that we have:

- configured `useDefineForClassFields: true`
- applied `declare` to all our non-observable properties to try to mitigate the 15%+ increase in our output bundle size due to `useDefineForClassFields`
- added `makeObservable` calls to all our classes which contain `observable`, `observable.ref`, `action` or `computed` decorators, at each level of inheritance hierarchy

(We've also noticed that if a `@computed` property overrides a `@computed` property in a base class this produces an infinite loop in MobX6 but we've managed to work around that as it was rare.)

**Versions**

mobx 6.0.4

**Comment by mweststrate** [comment]
This looks like a bug indeed, we found several so far related to subclassing (as did you), and are trying address them in #2641.

I didn't dive deeper, but looks like a decorator specific bug, without decorators it works fine: https://codesandbox.io/s/mobx6-baseclass-when-forked-x0cbg?file=/src/index.ts, so moving away from decorators might be a solution (at least in the subclassing cases). cc @urugator I wouldn't be surprised if this is fixed by your PR, seeing the changes so far

The `@computed` subclassing case was officially never supported, but #2641 should error clearly in that case as well.

The bundle size increase is something we sadly can't help until you don't need down transpilation anymore. Trust me, we regret this change in JavaScript as well, and did everything we can in TC-39 to argue for the current TypeScript semantics instead, but it is sadly not what has been standardised, so we figured the only responsible thing to do is to rework this, as the current semantics were going to be a problem sooner or later.

**Comment by urugator** [comment]
> I wouldn't be surprised if this is fixed by your PR

Should be I think

> The @computed subclassing case was officially never supported, but #2641 should error clearly in that case as well.

Overriding `computed` should be supported by decorating the getter in subclass with `@override` or leaving the getter non-decorated. Even computed with getter and setter defined on different prototypes should work 💪 
If you try to to apply `@computed` again in subclass it should indeed throw.

**Comment by jeremy-coleman** [comment]
Maybe helpful to share how i ‘upgraded’. I originally had about 7-8k lines of mobx decorated classes using subclasses. To get mobx6 working, i just manually combined parent class into all the subclasses (so no more class x extends y {•••}) and then ran the ts transform. Ended with about 13k loc, done in a day, its pretty straight forward copy paste monkey work. Although ultimately, i decided to not keep the changes and pin all the mobx5 ecosystem deps. I will likely continue to use mobx5 for the foreseeable future because i love it and it predictably does everything i want.

**Comment by urugator** [comment]
Tried in codesandbox, should work on 6.1.*

**Comment by urugator** [comment]
I will close this, please open new issue if there is still some problem.
