### ISSUE TITLE
Regression: Allow store modifications during rendering of components

### ISSUE THREAD

**Issue by olee** [mobxjs/mobx#2710]
It seems like https://github.com/mobxjs/mobx-react-lite/pull/299 was removed when mobx-react-lite was [updated for mobx6](https://github.com/mobxjs/mobx-react-lite/commit/ddce947279938af37873828408698b7de6cbb52a#diff-33c284d6bf49fd504d1250e7090d24ab73dae525efcc6376363ec89722a0df32L109-L128)

I just would like to ask if this was intentional and if so, whether what the reason was for this change.
Not handling this properly makes using local observable state (I know it is advised against, but sometimes you just need it) very difficult in some situations.

**Comment by FredyC** [comment]
There is a linked issue with a lengthy conversation, which I see you have participated in by the end. I am not sure what are you asking for specifically. Better to provide minimal reproduction where you think that PR is breaking something.

 https://github.com/mobxjs/mobx/discussions/2539

**Comment by urugator** [comment]
Intentional. We have deprecated the observable source as a mean to trasform non-observable props to observables. Making user responsible for syncing props with local state in which case he is adviced to use `useLayoutEffect`. It's no different than using non-observable state (if the state is truly local - the state isn't shared with other components, the simple assigment will do as well).
User is also adviced to keep the state definition outside of component (even a local one), so he isn't tempted to access props directly inside computeds etc.
IIRC it was mentioned/discussed in an issue for new mobx-react-lite or mobx-react version, can't find it atm.

**Comment by urugator** [comment]
Found it https://github.com/mobxjs/mobx-react-lite/pull/306

**Comment by urugator** [comment]
And before we move to another lengthy discussion, I have to emphasize again:
You should not need to sync different local states in React - you should merge the state and move it to a common ancestor.
Does it break encapsulation? Yes. That's why hooks were introduced - so you can split the component logic into independent pieces that can be moved around and composed easily.
So the starting point is, that this should be an edge case.

**Comment by olee** [comment]
Ok if it was intentional it's fine - I also did some development on a newer project which is written from the ground up with mobx.
There I do not run into any such issues, because everything is observable and works through stores which are created higher up in the hierarchy.

However with out legacy application we still experience this issue quite a lot because of how it was built (mobx was added afterwards) and there are many places where we kinda have to modify store data inside the render function. However we can just continue using the version of mobx-react-lite which contained the patch so it would be fine.

Considering that not allowing this also promotes better coding style with mobx, I also agree to just not allowing store modifications during rendering in the first place and therefore we can close this.
