### ISSUE TITLE
intercept takes a string, variable is nicer?

### ISSUE THREAD

**Issue by arlair** [mobxjs/mobx#273]
I haven't tried to use this feature, but I was reading through this [medium article](https://medium.com/@mweststrate/mobx-2-2-explicit-actions-controlled-mutations-and-improved-dx-45cdc73c7c8d#.k8znu8aul) and one thing that jumped out at me was the use of a string.

I don't know if there is any clever way to use the variable name instead, like theme.backgroundColor. It seems that would be nicer if you had an static checking, refactoring tools etc.

```
intercept(theme, "backgroundColor", change => {
```

**Comment by mweststrate** [comment]
Note that `intercept(theme, change => { if (change.name ===
"backgroundColor" ... ` would also work, but doesn't entirely resolve the
issue. I think the only way to make this statically working is using
symbols? Or introducing some additional type, but writing
`theme[themeAttrs.backgroundColor] = "#123"` would also be weird. I think
javascript (nor most other languages) doesn't have anything nice for
referring to members of an object, instead of the value of members.

Op za 28 mei 2016 om 08:00 schreef Arlair <notifications@github.com>:

**Comment by arlair** [comment]
Yes, I couldn't think of anything either, but I can dream ;) It doesn't look like anyone found a nice solution here, so I will close for now:
http://stackoverflow.com/questions/13612006/get-object-property-name-as-a-string

I think this approach could also break with minification/uglifying, so care should be taken. Seems like uglify supports --mangle-props.
