### ISSUE TITLE
Observables don't seem to work correctly with function in object

### ISSUE THREAD

**Issue by RickLucassen** [mobxjs/mobx#2835]
**Intended outcome:**
We should be able to extend an observable object, keeping the predefined properties intact, including functions.

**Actual outcome:**
When extending/printing an observable object with a function in it it will disappear.

**How to reproduce the issue:**
MobX 5: https://codesandbox.io/s/competent-dijkstra-3z6jm
MobX 6: https://codesandbox.io/s/keen-bas-7t0is

As you can see the function is still present when using MobX 5.

**Comment by urugator** [comment]
This is by design, since Mobx6 all functions become `autoAction`s - the field isn't observable and therefore is not enumable. Since spread syntax copies only own enumerable props, the function "disappears".
However, you're not the first one suprised by this, so [there is already a PR](https://github.com/mobxjs/mobx/pull/2779) that changes the behavior to be closer to mobx5.
Until then, you can explicitely annotate the functions with `observable`

**Comment by RickLucassen** [comment]
Thanks for the answer, I will close this issue then.
We will monitor the progress on that PR :)
