### ISSUE TITLE
Introduce `isAction`

### ISSUE THREAD

**Issue by satispunk** [mobxjs/mobx#290]
Hi, 

Recently started to explore MobX
I am trying to write own connect that just takes the store, is the a way to recognize that certain function of the class is marked with action decorator?

In the end I'd like to replace redux connect with that new connect and components should stay working without any change.

**Comment by mweststrate** [comment]
Did you check `mobx-connect` package?

I planned to add `isAction` indeed:
* `isAction(fn)`
* `isAction(object, propName)`

That would also allow to pass actions to `(extend)Observable` and copy them verbatim to the target object instead of turning them into computed properties (when they don't have arguments)

**Comment by satispunk** [comment]
Would be great to have isAction! 

I am trying to achieve similar as mobx-connect does, but with a little difference: connect should take selector over store like its done in redux

**Comment by mweststrate** [comment]
This feature will be released in the upcoming 2.3 release
