### ISSUE TITLE
Observable being read outside a reactive context

### ISSUE THREAD

**Issue by beilo** [mobxjs/mobx#2909]
**Intended outcome:**
No warning⚠️ *Observable being read outside a reactive context*

**Actual outcome:**
> [mobx] Observable Store@2.init being read outside a reactive context 
**How to reproduce the issue:**
```JavaScript
configure({
  enforceActions: "always",
  observableRequiresReaction: true // THIS
});

class Store {
  constructor() {
    makeAutoObservable(this);
  }
  count = 0;
  init = () => {
    this.count = 1;
  };
}

const App = observer(function App() {
  const state = useLocalObservable(() => new Store());
  useEffect(() => {
    // _allowStateChanges(true, () => { // not work
    //   state.init();
    // });
    // state.init(); // not work
    runInAction(() => {
      // It works, but it feels redundant
      state.init();
    });
  }, []);
  return (
    <div className="App">
      <h1>{state.count}</h1>
    </div>
  );
});```


https://codesandbox.io/s/romantic-dewdney-lxge4?file=/src/App.js

**Versions**
"mobx": "^6.2.0",

**Comment by beilo** [comment]
I am puzzled about this question. 
Why is ` action` observable,How can I avoid this problem.
Please help me, thank you

**Comment by urugator** [comment]
You have 3 options:
1. don't use `observableRequiresReaction: true`
2. use `runInAction` or  `useEffect(action(() => state.init()))` (you can easily abstract this to `useMobxEffect` or similar)
3. Explicitely mark the field as `action`: `makeAutoObservable(this, { init: action })`

By default the field is both - `observable` and value is `autoAction`, because we don't know what's your actual intention see https://github.com/mobxjs/mobx/pull/2842#issue-586131863 for details.

**Comment by urugator** [comment]
Actually since you're using class, there is 4th option: don't use arrow function and use `makeAutoObservable(this, {}, { autoBind: true })`

**Comment by mweststrate** [comment]
Note that semantically the point of actions is that they should wrap around the _events_ that are happening in your system, rather than just the operations that mutate, so that the batching is optimal as explained here: https://github.com/mobxjs/mobx/discussions/2901#discussioncomment-627757. So idiomatically the correct thing to do is `useEffect(action(() => { updates }), [deps])`.

**Comment by beilo** [comment]
> 实际上，由于您使用的是类，所以有第四个选择：不要使用箭头功能，而要使用 `makeAutoObservable(this, {}, { autoBind: true })`

Thank you very much. This reply perfectly solved my problem

**Comment by beilo** [comment]
@mweststrate Using this method can feel very burdensome. For example,
1. Add `action` to all events, such as `onClick`
2. We already have `runInAction` in the asynchrony. Adding `action` to the asynchrony is confusing

```JavaScript
onClick={action(() => {
  state.init();
})}

async init() {
  const res = await aaa();
  if (res.status === 200) {
    runInAction(() => {
      this.resData = res.data;
    });
  }
}
```

**Comment by mweststrate** [comment]
1. https://mobx.js.org/configuration.html#enforceactions
2. https://mobx.js.org/actions.html#asynchronous-actions
