### ISSUE TITLE
`isObservable` equals false for primitive properties in observable object/class 

### ISSUE THREAD

**Issue by antitoxic** [mobxjs/mobx#298]
Having this: https://github.com/mobxjs/mobx-reactive2015-demo/blob/master/src/stores/domain-state.js#L18

The following outputs as false:

```
isObservable(store.boxes[0].x) // outputs `false` should be `true`, right?
```

Is this desired behaviour or bug?

**Comment by antitoxic** [comment]
From what I'm seeing in the docs, mentions that `observable()` is infectious/recursive so by my logic the above should output `true`.

Another reason why I see this should output true is because the following outputs as true:

```
var primitiveValue = observable(2)
isObservable(primitiveValue) // outputs `true`
```

**Comment by AriaFallah** [comment]
If you look at the property descriptor of the properties of an observable object, you'll see

```js
get: function() {
  return observable.get();
}
```

Meaning that really behind the scenes `store.boxes[0].x` is `store.boxes[0].x.get()`.

Changing your test to reflect that

```js
var primitiveValue = observable(2)
isObservable(primitiveValue.get()) // outputs `false`
```

you'll see the behavior is consistent.

**Comment by AriaFallah** [comment]
The primitive values in the object **are** observable, but when you access them the property descriptor has been changed so it calls `get()`, meaning you get their value instead of the `ObservableValue` type.

Do you need to access the actual observable value for some reason?

**Comment by antitoxic** [comment]
I'm exploring what I can do with mbox. I thought I can pass an object property as observable down to another React component. May be the idea of having observable primitive (like `var counter = observable(1)`) confused me in the first place.
.
If you think I'm out of my mind, you can close this issue :)

**Comment by mweststrate** [comment]
@antitoxic primitive values are never observable in javascript; since primitives are immutable (like in almost any language). So the real question is whether the property is observable. To refer to the _property_ you indeed need to pass "x" as second argument, otherwise javascript will just dereference the property and pass its _value_ to `isObservable`.

**Comment by antitoxic** [comment]
That's what confused me:

```js
// Rerenders:
var counter = observable(1)
<MyComponent counter={largeState.counter} onClick={() => this.props.counter++}/>

// Does not rerender:
var largeState = observable({
...
  counter: 2
...
})
<MyComponent counter={largeState.counter} onClick={() => this.props.counter++}/>
```

Feel free to close the issue. May be some docs will clarify this? Or removing the option for primitives to be observable?

**Comment by satispunk** [comment]
Faced the issue while converting redux project to mobx.
With redux you usually connect minimal representaion of the state to the component, ie 

```javascript
function mapStateToProps(state => {
    return {name: state.domain.name, fetching: state.domain.fetching}
})
```
Using the same selector with mobx will not work as expected, since name and fetching variables not observable. So domain object should be provided to component, unfortunately it requires some cosmetic changes in components.

**Comment by AriaFallah** [comment]
@antitoxic @mweststrate 

So the problem is that we can't pass observable properties of objects to other elements, and keep them observable because `.get()` is called implicitly.

I can think of two solutions that aren't ideal:

1. The most obvious/annoying solution would just be to pass all of `largeState` into the component so that you would do `this.props.largeState.counter++`. 

2. Another option would be to change the property descriptor so `.get()` isn't called implicitly, but that'd be a breaking api change that'd require people to call `get()` themselves. (I think keeping the implicit `set()` would be fine).

Thoughts or other ideas?

**Comment by antitoxic** [comment]
I've just completed reading all the documentation (hoorey!) I see that this is called "dereferencing" in the docs (https://mobxjs.github.io/mobx/best/react-performance.html)

Probably there is reasoning why this is as it is. It's up to you whether this stays this way.

A good simple solution is to mention this a bit earlier in the docs. The "react performance" topic is probably considered advanced material (I mean people look at optimization docs if they need optimization).

**Comment by mweststrate** [comment]
Yes I definitely want to make this more clear in the docs and also in the egghead course (WIP). But didn't find the right wording yet
* "MobX / `observer` reacts to the dereferencing of values" might sound a bit vague
* "Assigning a new value to a property doesn't modify the old value, it modifies the object owning the property. So if you want to react to changes, pass on the owning object, not the value!" might be clearer. 

Note by the way that this is completely consistent with the semantics of javascript, but people usually don't realize this when working with JS because it is such a subconsciousness notion. 

```javascript
const Jan = "Jan"

const person = { name : Jan }
person.name = "John" // doesn't modify Jan! 
```
...it modifies person. So `person` is the thing we want to observe. So we should pass `person` onto the object not `person.name` which would only pass `Jan` along, which is never gonna change. 

I know you already understood this, but I am just trying out different explanations :). Any suggestion to clearly explain this in a few sentences are highly appreciated!

**Comment by antitoxic** [comment]
What about "References to primitive values are not observable/tracked by mobx unless you explicitly wrap them in `observable()`. Example: ... (code)... To trigger a change, set the value using the owning/parent object: ....(code sample)...."

**Comment by mweststrate** [comment]
Updated the docs: http://mobxjs.github.io/mobx/refguide/observer-component.html. I hope I addressed all angles of the issue :)

**Comment by antitoxic** [comment]
More than perfect. @mweststrate I'm getting to love mbox and the way it's developed more and more.
