### ISSUE TITLE
Change and call before using `observable` value, code get unexpected results

### ISSUE THREAD

**Issue by JevonsCode** [mobxjs/mobx#3107]
```js
import { observable } from "mobx";
import { useEffect } from "react";

const x = {
  value: 1
};

class Store {
  constructor() {
    console.log("mobx class constructor");
  }

  @observable
  storeValue = x.value;
}

const store = new Store();

export default function App() {
  useEffect(() => {
    // if you remove the "before console store.storeValue",
    // the "after store.storeValue" will be 2
    // console.log("before update");
    console.log("before ", store.storeValue); // before 1
    x.value = 2;
    console.log("after ", store.storeValue); // after 1
  }, []);

  return <div className="App">see console ↓</div>;
}

```

**Intended outcome:**

the `console.log("after ", store.storeValue);` print `after  1`

**Actual outcome:**

If you call `storeValue` before changing the `x.value` (no matter how it is called, even console), this value is changed.

**How to reproduce the issue:**

exp code: [codesandbox](https://codesandbox.io/s/this-suspected-problem-in-mobx-5-bjhj7?file=/src/App.js)

**Versions**

mobx version < 6

---

Through debug, I found that it is the timing problem of `createdocumentorforenhancer`, but I don't know why. Is this a bug?

**Comment by urugator** [comment]
Prior v6, when using decorators, the field is actually redefined and made observable lazily the first time the field is accessed (because we need access to `this`, which isn't available at the time the decorator is invoked).
It doesn't seem to play well with the way the field initializers are transpiled. The problem goes a way if you assign the value in constructor or use `decorate/extendObservable`. 
Looks like the right side of the assigment gets captured in some closure, perhaps decriptors's getter, dunno. If you're using `babel` make sure to use 
```
"plugins": [["@babel/plugin-proposal-class-properties", { "loose": true }]],
// Babel >= 7.13.0 (https://babeljs.io/docs/en/assumptions)
"assumptions": {
  "setPublicClassFields": true
}
```
These are not defaults in newer babel versions.
