### ISSUE TITLE
Data structure updates inside of a store have unintended side effects

### ISSUE THREAD

**Issue by 619** [mobxjs/mobx#3127]
**Intended Effect**

class SearchStore {

hits = {};

setHits(query, category, metric, hitsList, nbHits, mode, searchSectionMode, extensionMode) {
    var indexCode = query + '-' + mode + '-' + category + '-' + metric + '-' + searchSectionMode + '-' + extensionMode;
      if (indexCode in this.hits) {
        this.hits[indexCode]['hitsList'] = hitsList;
      } else {
        this.hits[indexCode] = {hitsList: hitsList, nbHits: nbHits, initialized: true};
      }
  }

}

I have one object inside of hits. When I call setHits, another object with a different indexCode (the difference being the extensionMode in this case) should be stored inside of hits. The first object should remain unchanged.

**Actual Effect**
Instead, the second object is stored inside of hits AND the first object has its hitList updated with the second object's hits added to it, which is supposed to be the first clause in the if case. Another strange thing: when I console.log(this.hits) at the top of setHits, it has ALREADY been changed, even though the console.log takes place before the if statement in setHits. 

**How to reproduce the issue:**
Just call that function.

**Versions**
6.2.0

**Comment by 619** [comment]
Also not the first time I've had this type of issue. In a previous function, I tried to add an element to an array inside of a store object, and it also had unintended side effects.

**Comment by mweststrate** [comment]
Console.log statements might not be representative, since they evaluate lazily (e.g when you expand then, rather than when you create them). 

Beyond that this looks like it will probably be a programming error, not an issue with MobX. But without any minimal, runnable reproduction it will be impossible to say anything with some certainty. Please create a reproduction that a) shows the problem and b) shows that the problem is caused by Mobx (e.g. the same problem doesn't occur when using plain objects). Without that, I recommend to use StackOverflow instead to help with programming in general.
