### ISSUE TITLE
IObjectDidChange `type: "remove"` type annotation mismatch with `type="delete"`

### ISSUE THREAD

**Issue by ptboyer** [mobxjs/mobx#3179]
**Intended outcome:**

The `observer` listener's event object's `type` should be inferred union of "add" | "update" | "delete", and I should not get a type error when trying perform a comparison on `type` against the `"delete"` value.

![Screenshot_20211110_142742](https://user-images.githubusercontent.com/8391902/141044461-853c81ff-ae1d-4f85-bdc9-de7a1dd35a99.png)

**Actual outcome:**

Getting a type error because the actual value being provided by MobX's runtime can be `"delete"` -- whereas it is typed as `"remove"`. [`mobx/src/types/observableobject.ts#L70`](https://github.com/mobxjs/mobx/blob/6519021a3e2071189111be33aa9e05ab4188d76a/packages/mobx/src/types/observableobject.ts#L70) needs to be changed to `"delete"`

![Screenshot_20211110_142251](https://user-images.githubusercontent.com/8391902/141044042-a02eb73e-714f-42e0-bbf1-9efcfbd1a54f.png)

**How to reproduce the issue:**

```typescript
observe(this.anythingObservable, (event) => {
  if (event.type === "delete") { ... }
})
```

To match the screenshot.

**Versions**

`mobx@6.3.6`

**Comment by kubk** [comment]
On the first screenshot I see the field `observableKind: 'map'`. It means that it is a Map, not just an object. Type `IMapDidChange` has `delete` type which is correct: https://github.com/mobxjs/mobx/blob/6519021a3e2071189111be33aa9e05ab4188d76a/packages/mobx/src/types/observablemap.ts#L63

And I see that observe function should correctly infer the `IMapDidChange` type: https://github.com/mobxjs/mobx/blob/6519021a3e2071189111be33aa9e05ab4188d76a/packages/mobx/src/api/observe.ts#L34

The issue is inside `observe` function:

<img width="376" alt="Screen Shot 2021-11-10 at 09 15 37" src="https://user-images.githubusercontent.com/22447849/141060161-338cb0c8-c23e-4a37-a41e-ea538b027bc5.png">

I'll investigate and come up with a solution.
