### ISSUE TITLE
Object.freeze doesn't work on serializable objects

### ISSUE THREAD

**Issue by pixelkritzel** [mobxjs/mobx#3298]
Codesanbox

https://codesandbox.io/s/objective-hooks-z5nb1z?file=/src/index.js

**Intended outcome:**

I assumed I could freeze simple observables.

**Actual outcome:**

It throws the error: [MobX] Dynamic observable objects cannot be frozen

**How to reproduce the issue:**

Have a look at the CodeSandbox.

**Versions**
 mobx 6.3.13

**Comment by mweststrate** [comment]
If you intend to freeze something, why make it observable? These are
conceptual opposites

**Comment by pixelkritzel** [comment]
It's not me. It's Storybook which freezes the object.

**Comment by urugator** [comment]
If you're passing your observables to 3rd party component/function, pass copy instead (`toJS(observableObject)`). Otherwise you will have to be a bit more specific if you want help.

**Comment by pixelkritzel** [comment]
Maybe it would a good a idea to put in the Gotchas section of the docs. Which I couldn't find anymore.

**Comment by kubk** [comment]
I assume no one would try to call `Object.freeze` on observable intentionally, because it doesn't make any sense. So probably a user can only encounter this bug after passing observable to some 3rd party library that calls `Object.freeze`. My suggestion is edit the Mobx warning and link it to the urugator's comment. So instead of these:

https://github.com/mobxjs/mobx/blob/e60b36c9c78ff9871be1bd324831343c279dd69f/packages/mobx/src/errors.ts#L25
https://github.com/mobxjs/mobx/blob/e60b36c9c78ff9871be1bd324831343c279dd69f/packages/mobx/src/errors.ts#L27

We could have something like "Dynamic observable objects cannot be frozen. The details are here: https://github.com/mobxjs/mobx/issues/3298#issuecomment-1041304341"

**Comment by pixelkritzel** [comment]
Yes, something like this would be helpful. "Dynamic object" didn't really help. Especially because it was such a simple object.

**Comment by urugator** [comment]
"Dynamic" in this context means proxied object (object that supports adding/deleting props in reactive manner)
