### ISSUE TITLE
Applying jest.spyOn to observed value in one test case results in an error when referencing the observed value in another test case

### ISSUE THREAD

**Issue by Thiry1** [mobxjs/mobx#3371]
**Intended outcome:**
pass all tests with enable Proxy support.

**Actual outcome:**
test with `configure({ useProxies: "never" })`: all tests pass
test with `configure({ useProxies: "always" })`: a test case after using jest.spyOn fails with `TypeError: Cannot read properties of undefined (reading 'get')`
https://github.com/Thiry1/mobx-bug-repro/blob/master/src/__tests__/index-test.js#L11-L19

**How to reproduce the issue:**

1. clone [reproduction repo](https://github.com/Thiry1/mobx-bug-repro)
2. yarn test

**Versions**
mobx@6.5.0

**Comment by kubk** [comment]
Hi, thanks for the reproduction 👍 

I did some experiments and here are the results. Test fails even with `configure({ useProxies: "never" })`. Try to fully comment this test:

https://github.com/Thiry1/mobx-bug-repro/blob/8aaf4986d45adca9f3b7e94353d452352e9f20ac/src/__tests__/index-test.js#L9-L21

The reason of the issue is that you use shared state (variable `store`) between many tests. A way to fix it is to add `mockRestore` to your test:

```diff
  it("case2", () => {
-    jest.spyOn(store.state, "key", "get").mockReturnValueOnce("bar");
+    const spy = jest.spyOn(store.state, "key", "get").mockReturnValueOnce("bar");
     expect(store.isFoo).toBe(false);
+    spy.mockRestore()
  });
```

If you run this test with `configure({ useProxies: "always" })` commented, it'll succeed. But if you uncomment the test it'll fail. It looks like Jest can't restore proxy values properly, the `spy.mockRestore` doesn't work. A workaround is to avoid shared state in tests:

```js
function runTests() {
  configure({ safeDescriptors: true });
  let store;
  beforeEach(() => {
    store = new Store({
      key: "foo",
    });
  })

  it("case1", () => {
    expect(store.isFoo).toBe(true);
  });
  it("case2", () => {
    jest.spyOn(store.state, "key", "get").mockReturnValueOnce("bar");
    expect(store.isFoo).toBe(false);
  });
  it("case3(same as case1)", () => {
    jest.clearAllMocks()
    expect(store.isFoo).toBe(true);
  });
}
```

As a conclusion - it is definitely not a Mobx issue. Either avoid shared state between tests or make sure it is restored somehow before / after each test.

**Comment by kubk** [comment]
My personal opinion - mocking your store methods with `spyOn` lead to subtle tests, because such tests tightly coupled to the code internals. I often write Mobx tests but never use this approach. I may help you if you describe what exactly are you trying to test. Because the code is very abstract to give any advices.

**Comment by Thiry1** [comment]
@kubk Thank you for quick reply and explanation.
We will modify the test according to your advice.Then consider changes to the test architecture.
