### ISSUE TITLE
Observable map additions cannot be batched in a transaction or a merge

### ISSUE THREAD

**Issue by lucsky** [mobxjs/mobx#339]
The following snippet outputs 6 `add` changes when I would expect only two (even semantically different ones would be fine):

```javascript
const m = mobx.map();

mobx.observe(m, (ev) => {
  console.log(`${ev.type} : ${ev.name}`);
});

mobx.transaction(() => {
  m.set('1', 'one');
  m.set('2', 'two');
  m.set('3', 'three');
});

m.merge({
  '4': 'four',
  '5': 'five',
  '6': 'six'
});

// Output:
// add : 1
// add : 2
// add : 3
// add : 4
// add : 5
// add : 6
```

(Try it here: https://jsbin.com/fahegucebi/edit?js,console)

**Comment by mweststrate** [comment]
Hi @lucsky,

By design `observe` (and `intercept`) do not respect transactions; transactions postpone derivations, but observe is not a derivation but merely an event log.

If you would use `reaction`  or `autorun`  instead, you will see that only two log lines are printed. I hope that helps!

**Comment by lucsky** [comment]
Like this ? That doesn't seem to work at all 🤔

```javascript
const m = mobx.map();

mobx.reaction(
  ()  => m,
  (m) => console.log('changed')
);
```

**Comment by mweststrate** [comment]
Because the map doesn't change, it just a pointer to an object :) It's
contents did change. So autorun will only react to the properties you
*use*. And reaction only to to the properties you use to create a data
structure to pass to the second callback.

So `mobx.reaction(() => m.has("a") ? m.get("a") : null, a =>
console.log(a))` would react to changing "a" in the map, but it wouldn't
react to changing "b". This way MobX ensures the minimal amount of work is
done, instead of firing everything that somehow relates to the map

Op vr 17 jun. 2016 om 17:01 schreef Luc Heinrich <notifications@github.com>:

**Comment by lucsky** [comment]
Aaaahh, ok, got it now 😊

So if I want to react to any addition or deletion to the map I can do:

```javascript
const m = mobx.map();

mobx.reaction(
  ()  => m.values(),
  (m) => console.log('changed')
);
```

Thanks for the help !
