### ISSUE TITLE
Merging objects and Cycle in reactive function

### ISSUE THREAD

**Issue by hellectronic** [mobxjs/mobx#340]
Hello,

maybe this is simple to solve but I really need a hint how to proceed. I read #179 and I know why this error appears. This is what I try to do:
```javascript
class ExampleUIStore {
  @observable obj = {};

  constructor( otherStore ) {
    this.otherStore = otherStore;
    autorun( () => {
      this.obj = this.mergeObj( this.obj, this.otherStore.otherObj );
    } );
  }
}
```
The cycle is triggerd by using `this.obj` in `mergeObj()`. I want to merge changes from OtherStore to `this.obj`. I cannot use a `computed` because `this.obj` needs to be changeable. Do I miss something? Is there some "best-practice" for this?

**Comment by mweststrate** [comment]
I think you should use a reaction here (or untracked) so that you can separate the looping of your own object from reading the other one. Probably you want to react to changes in `otherStore` but not to changes in your own properties. So you could use something like `reaction(() => <object representing the other store>, (otherObject) => { this.obj = this.mergObject(otherObject) }`

**Comment by hellectronic** [comment]
Hey thanks. That is working. I was so fixed on the autorun that I missed this possibility.
