### ISSUE TITLE
Observer HOC is not getting displayName from forwardRef

### ISSUE THREAD

**Issue by kazah96** [mobxjs/mobx#3422]
When i wrap forwardRef by observer, any infomation that can be used as display name is lost.

For example:

```
const ComponentWithForwardRef = forwardRef(function ComponentWithForwardRef(
  {},
  ref
) {
  return <div ref={ref} />;
});

const ObserverComponent = observer(ComponentWithForwardRef)
```
So ObserverComponent has name **ObserverForwardRef** instead **ComponentWithForwardRef**.

If i explicitly set
```
ComponentWithForwardRef.displayName = "ComponentWithForwardRef"
const ObserverComponent = observer(ComponentWithForwardRef)
```
i see same thing

The only variant ive found is to explicitly set displayName after wrapping in observer
```
const ObserverComponent = observer(ComponentWithForwardRef)
ObserverComponent .displayName = "ComponentWithForwardRef"
```
but it isnt look pretty

Also, mobx/no-anonymous-observer is not happy with all of listed variants.

Any ideas?

Checked for mobx-react-lite: 3.4.0
Here: https://codesandbox.io/s/condescending-glade-yx3qgy?file=/index.js

**Comment by kazah96** [comment]
@urugator Thank you for the reply. 
Seems we dont got much to do, but ive check source code of [observer](https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/src/observer.ts), and found  
`const baseComponentName = baseComponent.displayName || baseComponent.name`,

and it looks like if we wrapping React.forwardRef, we can get its name from `render.name` of forwardRef component

`"componentWrapperFunctions" + react/display-name` works fine with explicit `Component.displayName = "Component"` setting. Should we add this workaround to [mobx-eslint-plugin](https://github.com/mobxjs/mobx/tree/main/packages/eslint-plugin-mobx) docs?

**Comment by urugator** [comment]
> and it looks like if we wrapping React.forwardRef, we can get its name from render.name of forwardRef component

Yea, I dunno what would be a proper thing to do here - whether we should get the name from ref wrapper as now or rather from wrapped component. Ideally it should behave as with react alone. The whole displayName business is [a bit magical](https://github.com/mobxjs/mobx/pull/3192) and can even differ from version to version. I would have to investigate, however I don't think it's worth it atm because once [we apply memo](https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/src/observer.ts#L130), the displayName seems lost anyway. Or perhaps I am missing something?

> Should we add this workaround to [mobx-eslint-plugin](https://github.com/mobxjs/mobx/tree/main/packages/eslint-plugin-mobx) docs?

Yes and deprecate and remove it from [recommended](https://github.com/mobxjs/mobx/blob/45e364293a7f5ab9315a1abc723f2605fa9229c3/packages/eslint-plugin-mobx/src/index.js#L18). PR welcome.

**Comment by kazah96** [comment]
@urugator, if we set displayName after wrapping in memo, things gonna work (at first glance). But this looks a bit hacky

Btw, i made a PR with docs edit and rule removal, check please
