### ISSUE TITLE
An exception is thrown when using Mobx6 and react18 in development mode

### ISSUE THREAD

**Issue by guochengcheng04** [mobxjs/mobx#3492]
**Intended outcome:**

When I use React18's new rendering API `ReactDOM.createRoot().render`, I get a lot of warnings. It should be guaranteed to be consistent with the previous behavior, run normally, and not throw warnings

warning message: react_devtools_backend.js:3973 Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.

**Actual outcome:**

I get a lot of warnings, but can't find the information I have in it, like below

**Versions**

mobx@^6.6.1 mobx-react@^7.5.1

![Dzdw92s8dG](https://user-images.githubusercontent.com/103164744/183839113-aede2bd2-4a99-412a-b1ab-a43c1e76ba73.jpg)

**Comment by kubk** [comment]
Please create a runnable reproduction using codesandbox. Here is an example of Mobx + React 18 that shows no warnings: https://codesandbox.io/s/vigilant-hellman-3mjsty?file=/index.js

**Comment by guochengcheng04** [comment]
> Please create a runnable reproduction using codesandbox. Here is an example of Mobx + React 18 that shows no warnings: https://codesandbox.io/s/vigilant-hellman-3mjsty?file=/index.js

@kubk hello, this is the demo code link. https://codesandbox.io/s/mobx6-and-react18-2rx40e?file=/index.js

**Comment by guochengcheng04** [comment]
Is there any progress on this please?

**Comment by guochengcheng04** [comment]
> > Please create a runnable reproduction using codesandbox. Here is an example of Mobx + React 18 that shows no warnings: https://codesandbox.io/s/vigilant-hellman-3mjsty?file=/index.js
> 
> @kubk hello, this is the demo code link. https://codesandbox.io/s/mobx6-and-react18-2rx40e?file=/index.js

and in this case, this problem can also be reproduced by clicking the button, https://codesandbox.io/s/mobx6-and-react18-2-gu58ts?file=/CompA.js

**Comment by guochengcheng04** [comment]
> > Is there any progress on this please?
> 
> @guochengcheng04 please remove this comment. It is rude, and completely uncalled for within four hours. This software is provided to you as-is, and people are helping out here on a voluntarily basis, to help you with the problems you are probably paid to solve. So please refrain from such comments, and if you want to increase your chance on follow up, consider instead contributing to the community yourself, by helping out others with their issues.

sorry, my bad. because this problem is stable and recurring, and it is important

**Comment by urugator** [comment]
@mweststrate We will have to handle reaction disposal of class components similary to functional ones. Apparently react can now decide to run render and throw the component instance away without running lifecycle methods. It does it when using `Suspense` in render.

**Comment by guochengcheng04** [comment]
> @mweststrate We will have to handle reaction disposal of class components similary to functional ones. Apparently react can now decide to run render and throw the component instance away without running lifecycle methods. It does it when using `Suspense` in render.

@urugator If you can provide me with some ideas, I think I'd be happy to solve it

**Comment by urugator** [comment]
@guochengcheng04 If you mean to PR, then you will have to take a look at:
https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/src/utils/reactionCleanupTracking.ts
and how it's being used in `useObserver`:
https://github.com/mobxjs/mobx/blob/28e080e119e69a0fd0b8c4d0ae3fbf1fe1c1d1db/packages/mobx-react-lite/src/useObserver.ts#L5-L7
Then the goal is make use of these in a similar fashion in `observerClass`:
https://github.com/mobxjs/mobx/blob/main/packages/mobx-react/src/observerClass.ts

If you mean what you can do in your code base, then you can rewrite components using `Suspense` into functional ones or instead of using `Suspense` directly, you can wrap it into a simple wrapper and use it instead:
```javascript
function SuspenseWorkaround(...props) {
  return <Suspense {...props}></Suspense>
}

const root = createRoot(document.getElementById("root"));
root.render(
  <SuspenseWorkaround fallback={<div id="outer-loading" />}>
    <CompA />
  </SuspenseWorkaround>
);
```

**Comment by guochengcheng04** [comment]
@urugator Can we use `updater.isMounted` check whether the target component is loaded? When I changed it like this, the warning disappeared.
In this example, we can't check whether the initialization has been completed through `componentDidMount`. I guess it may be because of fiber.
![image](https://user-images.githubusercontent.com/103164744/188440819-13e25f6d-fc21-43f5-9296-dbe0e70bbd8e.png)

**Comment by guochengcheng04** [comment]
and I checked the implementation of the function component you said. It may not be applicable to class components, because `componentDidMount` does not take effect

**Comment by urugator** [comment]
@guochengcheng04

> Can we use updater.isMounted check whether the target component is loaded? When I changed it like this, the warning disappeared.

It's only part of the solution, same as here:
https://github.com/mobxjs/mobx/blob/f0e066f427d573cbef4b92f3310eb069c3aca205/packages/mobx-react-lite/src/useObserver.ts#L49-L51

> It may not be applicable to class components, because componentDidMount does not take effect

No it's exactly what it tries to solve:
The problem is that we create `reaction` during render, but if the component isn't commited (concurrent mode), no effect or lifecycle method is called, but we still have to dispose the reaction created in render.

**Comment by guochengcheng04** [comment]
@urugator I mean, like the code in the figure, in the function component scenario, we can assign a value to `trackingData. mounted` through `useEffect`, because it is accurate. However, in the scenario of class components, if we use the same strategy to assign the value to 'trackingData. mounted' when 'componentDidMount', a warning will inevitably appear in the next render. We can't mock the implementation of `isMounted` according to the existing API, or do you have any other ideas?

**Comment by urugator** [comment]
> trackingData.mounted when componentDidMount, a warning will inevitably appear in the next render

Why? Once the `componentDidMount`/`useEffect` is called, it is safe to call `forceUpdate/setState` until `componenWillUnmount/disposer` is called. It's exactly the same.

**Comment by guochengcheng04** [comment]
https://codesandbox.io/s/mobx6-and-react18-2-gu58ts?file=/CompA.js

**Comment by guochengcheng04** [comment]
![image](https://user-images.githubusercontent.com/103164744/188498783-958a93a0-2b5a-4894-95dd-56c5eef9de71.png)

**Comment by urugator** [comment]
@guochengcheng04 Yes because `componentDidMount` is triggered on different component instance, then the one that throws the error. This is what happens:
React creates component instance (+ reaction), renders for the first time, throws component instance away without calling `componentDidMount/Unmount` (reaction isn't disposed), then it creates second component instance (+ reaction), renders for second time, commits the component, calls `componentDidMount`.
When the state is mutated, we notify both reactions, but the first one (leaking) calls `forceUpdate` on uncommited component, therefore the warning.

**Comment by guochengcheng04** [comment]
@urugator so the idea is still to associate the mock mounted flag with reaction one by one, right?

**Comment by guochengcheng04** [comment]
@urugator  I implemented the logic of the class component according to the idea of ​​the function component, and the verification passed, please help to see if there is any problem, expect your approval

https://github.com/mobxjs/mobx/pull/3515/files

**Comment by guochengcheng04** [comment]
I have completed the repair and verification of this issue, can any maintainer help me merge and publish it?
