### ISSUE TITLE
Unexpected deep: false issue and/or maybe performance issue

### ISSUE THREAD

**Issue by emilmuller** [mobxjs/mobx#3523]
Consider the following code:

```
class FooClass {
	@observable fooMember;
	constructor(fooMember) {
		this.fooMember = fooMember;
		makeObservable(this, null, { deep: false });
	}
}

let fooInstance = new FooClass({ a: 123, b: { c: 1234 } });
console.log(fooInstance.fooMember);
```

Testing in Chrome yields:

![image](https://user-images.githubusercontent.com/2487546/190363421-c1bc1f63-ba97-4d4d-a676-441a66dcf3c7.png)

What I don't understand is why does it iterate through all of fooMember's properties and create proxies of its properties (`b` property in this case), etc. (what I would consider deep iteration) when I specifically set _deep_ to false in makeObservable. Or maybe I misunderstood what _deep_ does.

This, however, works as expected:

`observable.box({ a: 123, b: { c: 1234 } }, { deep: false }); // No Proxy created for 'b' and no getter and setter for 'a'`

Kind regards, Emil 🙃

Version: 6.6.1

**Comment by urugator** [comment]
As noted here https://mobx.js.org/observable-state.html#options-
`deep` only changes the default behavior if you don't specify annotation/decorator explicitely.
It's not very useful in case of `makeObservable` as it's only effective when you do:
`makeObservable(this, { field: true }, { deep: false })` (`true` means auto, `deep` option modifies this auto behavior)
Since you're using decorators, just use:
`@observable.ref fooMember;`
Or, depending what your actual goals is, you may want to use
`@observable.shallow fooMember;`

**Comment by emilmuller** [comment]
Thank you! Sorry for my ignorance :)
