### ISSUE TITLE
extendObservable with computed getter makes getter inaccessible

### ISSUE THREAD

**Issue by paulftw** [mobxjs/mobx#3633]
```javascript
import {
  get,
  makeObservable,
  extendObservable,
  observable,
  computed
} from "mobx";

class Base {
  x = 123;
  constructor() {
    makeObservable(this, { x: observable });
  }
}

class Child extends Base {
  constructor() {
    super();
    extendObservable(this, { x2: computed });
  }

  get x2() {
    return this.x * this.x;
  }
}

const child = new Child();
console.log("child.x2=", child.x2);
console.log("get (child.x2)=", get(child, "x2"));
```

**Intended outcome:**

Both `console.log` calls should have printed 123 squared.

**Actual outcome:**

```
child.x2= ƒ Child@61.x2() {}
get (child.x2)= ƒ Child@61.x2() {}
```
It seems like mobx proxy returns some wrapper function instead of calling the getter and returning its result.
It work as expected when getter and annotation are moved to the base class.
Wrapping console calls into a `runInAction` does not change the output.

**How to reproduce the issue:**

[Codesandbox](https://codesandbox.io/s/infallible-scooby-m891cp?file=/src/index.tsx)

**Versions**

Codesandbox uses v6.8.0, I've hit this problem in a project with 6.7.0 installed.

**Comment by urugator** [comment]
You're supposed to call `makeObservable` (even in subclass) ... IIRC `extendObservable` should work as well, but the signature and use case is different:
`makeObservable(target, annotations?, options?)` annotates existing properties (if prop doesn't exist on target it throws)
`extendObservable(target, properties, overrides?, options?)` adds new properties to the target and makes them observable - you can customize annotations in  `overrides`. It's basically just a shortcut for
```
o.foo = 5;
makeObservable(o, { foo: observable });
// =>
extendObservable(o, { foo: 5 });
```
In the past `extendObservable` was the only way to make any class observable with pure JS, because field initializers did not exist (there weren't any existing properties, you had to introduce them in constructor, so you would do that as part of `extendObservable` call). Also dynamic objects (proxies) did not exist, so it was the only way to introduce new observable prop to object. Currently you won't probably need it.

**Comment by paulftw** [comment]
Thanks @urugator
I've re-read the docs and it does indeed say `extendObservable` doesn't work how I assumed, my bad.
Multiple calls to `makeObservable()` give me the result I wanted
