### ISSUE TITLE
ReferenceError: Property "FinalizationRegistry" doesn't exist - using mobx + mobx-react/mobx-react-lite on android

### ISSUE THREAD

**Issue by aikhsanov** [mobxjs/mobx#3656]
**Intended outcome:**

Trying to use mobx with react-native expo. Like this: 

```
import { Text } from "react-native";
import { observer } from "mobx-react-lite";

function Comp() {
  return <Text>hehe</Text>;
}

export default observer(Comp);

```

And if rn version is 0.69.xx everything works fine on android phone.

**Actual outcome:**

But if rn version is > 0.69, using the "observer" creates this error:
![image](https://user-images.githubusercontent.com/71754926/224366475-490e49b7-6d16-46a6-a8ad-c1f800a3c2e1.png)

If you remove "observer" usage from code, error dissapears

**How to reproduce the issue:**

[Repo](https://github.com/aikhsanov/mobx-react-native-71.git)

**Versions**

"mobx": "^6.8.0",
"mobx-react-lite": "^3.4.1",

**Comment by iChenLei** [comment]
https://github.com/facebook/hermes/issues/604
https://reactnative.dev/blog/2022/09/05/version-070#hermes-as-default-engine
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry

**Comment by kubk** [comment]
Could you try updating to 3.4.2? https://github.com/mobxjs/mobx/pull/3646/files

**Comment by aikhsanov** [comment]
> Could you try updating mobx-react-lite to 3.4.2? https://github.com/mobxjs/mobx/pull/3646/files

Thank you ver much! That solved the problem!)

**Comment by samuelawal** [comment]
I also have the same issue 
ReferenceError: Property 'FinalizationRegistry' doesn't exist, js engine: hermes
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
