### ISSUE TITLE
Add support for generators in @action

### ISSUE THREAD

**Issue by Nopik** [mobxjs/mobx#386]
It would be great, if `@action` would allow generators and handle them intelligently (e.g. resolve promises, throwing errors on rejects, handle callback functions, etc.), basically like redux-saga does.

**Comment by yelouafi** [comment]
You can use redux-saga with mobX if you want using the [`runSaga` Api](http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-options). You can get all the features:  promise handling, sync error handlng, forking tasks, cancellation and even dispatching global events. 

I'm not sure however about the usage with `@action` since the operations inside the body of a generator will typically run asynchronously (eg ajax fetch). I dont think it's desirable to hold a transaction during the whole lifecycle of an async flow.

**Comment by alinz** [comment]
would it be easier to just use `runInAction` inside your async action? I don't like too much magic done by libraries. It makes code a lot harder to debug when you don't know what's happening under the hood. You can also see the doc related to `async` operation inside `@action` in [here](https://mobxjs.github.io/mobx/refguide/action.html)

**Comment by mweststrate** [comment]
I think cool abstractions could be made here, but I doubt they belong to the mobx-core. So closing this issue for now. But feel free to write an insanely awesome package or create a PR on mobx-utils :)
