### ISSUE TITLE
Updating to 6.13.0 causing error: `Cannot find name 'ReadonlySetLike'. Did you mean 'ReadonlySet'?`

### ISSUE THREAD

**Issue by schen-fn** [mobxjs/mobx#3903]
**Intended outcome:**
Upgrading to the 6.13.0 minor update should not produce any errors, specifically the `Cannot find name 'ReadonlySetLike'. Did you mean 'ReadonlySet'?` error.

**Actual outcome:**
Upon upgrading to version 6.13.0, the following error occurs: `Cannot find name 'ReadonlySetLike'. Did you mean 'ReadonlySet'?`.

**How to reproduce the issue:**
1. Upgrade to version 6.13.0
2. Observe the Error: `Cannot find name 'ReadonlySetLike'. Did you mean 'ReadonlySet'?`

**Configuration Details:**

Using es2020 in tsconfig.json.
This issue mirrors the problem described in this [release job on GitHub](https://github.com/mobxjs/mobx/actions/runs/9765918034).

**Additional Information**
The error is resolved by switching the target in tsconfig.json from es2020 to esnext. However, this change is not backward-compatible, which may be problematic for a minor update.

**Comment by mweststrate** [comment]
The release build was fixed in https://github.com/mobxjs/mobx/commit/32c934bea82feaddff01aad67231ee4a1d64ede9. 

In this case you'll indeed have to update the TSLib to ESNext. Like TypeScript itself, we don't follow semantic versioning closely for static types, as otherwise we'll have to fork the package for every different tsconfig / target people are using. (E.g. if we made this a major change, it means that anyone not on `esnext` would stop receiving any update to MobX! Even though there is no actual functional consequence)

It is not ideal, and generally I avoid this problem (many libs suffer from it) by slamming a `skipLibCheck: true` in my projects' tsconfig.

**Comment by triemstr** [comment]
Seems there are 7 tsc errors for me, all for `ReadonlySetLike` from https://github.com/mobxjs/mobx/pull/3898/commits/7131addbf363fc94a37867194de35fbc14651efa

If @inoyakaigor has a thought otherwise that can make this work for those using defaults on vite 5+ (target: modules is the default), that would be appreciated also.

Until then, if anyone else enters this issue, yes you can use esnext (although I have not been able to get that to work despite setting it in 3 different vite config targets per stackoverflow), or give up and downgrade like me to mobx - 6.12.5.

**Comment by inoyakaigor** [comment]
@trimester could you provide minimum reproducible sample?

**Comment by mweststrate** [comment]
skipLibCheck: true in tsconfig json?

**Comment by triemstr** [comment]
No skipLibCheck is not true...and I understand that is suggested and eventually all developers have to go that route more or less. 

I'm just suggesting this is the one `tsc` error that just started with mobx 6.13.0 that did not exist on 6.12.5. If there is but one error, then I thought someone smarter than I may know a quick fix. (I'm not the original poster of this issue, just happened upon it.)

**Comment by triemstr** [comment]
Breaks when importing `runInAction`.

[runInAction.zip](https://github.com/user-attachments/files/17594216/runInAction.zip)
@mweststrate @inoyakaigor here is the smallest possible project that will cause the issue for me at least.

- Extract zip
- `npm install`
- `npm run compile` which calls tsc

If you don't want to use the package, here is what I did:

1) Made stripped down tsconfig.json and package.json (with typescript ^5.6.3 and mobx ^6.13.5).
2) Add to any file: `import { runInAction } from 'mobx'`

I'm sure we can also switch this to some other function if you had advice. But others may be experiencing it and can't just use vite esbuild instead like I can.

**Comment by mweststrate** [comment]
Underlying problem here is that collections that are provided by the standard types (the `lib` field in tsconfig) differ per JavaScript version. E.g. you might be compiling for a version that has `array.flatten` or doesn't have it. However, it is untenable for us to maintain a MobX version against every combination of lib flags you are using. So in the source code we just compile against the _newest_, assuming that `flatten` exists and then we deal with the difference at runtime. 

TSC however cannot know that, and so it will complain if the library itself has a dependency on `array.flatten` if you are trying to compile with a configuration that doesn't have it. This is a very common problem and not very practical fixable (libraries depending on node features typically suffer from the same), so that is why I recommend to use `skipLibCheck` and not further worry about it. 

In this case, ReadonlySetLike is defined by lib `esnext.collection` (but not es2015.collection which es2022 depends on, but only has `ReadonlySet`), which you could add to your lib config to solve the error, but that might lead to other problem, and make incorrect assumption about YOUR code, so I wouldn't do it.

**Comment by triemstr** [comment]
ok thanks! I was using nodenext but can adjust the approach!

**Comment by elektronik2k5** [comment]
I just hit this issue and the workaround is indeed to set `"ESNext", "ESNext.Collection"` in `compilerOptions.lib`.
