### ISSUE TITLE
How to update a dirty-flag on any change inside my observed graph?

### ISSUE THREAD

**Issue by neekibo** [mobxjs/mobx#398]
I have a model-store and a UI-store.
```javascript
class ModelStore {
   @observable complexGraph = { ... }
}

class UiStore {
   @observable dirty = false
}
```
I want to change the dirty flag to true whenever the complexGraph changes. How do I do this? computed, autorun, reaction? I am using mobx-react also.

**Comment by mweststrate** [comment]
You can do that by walking through the graph in an autorun and set the dirt flag on each run. But with MobX you usually don't need to track dirty status in the first place. If you can elaborate a bit more on your problem, there might be a cleaner solution

**Comment by neekibo** [comment]
Problem description: The user can save the graph/model (server-side). I want to disable the save-button on successful save (easy) and want to re-enable the button on first state change (problem).

Maybe I don't need a dirty flag but I need to be notified on state change (any) to communicate to the use if there is change that can be saved (pristine or dirty).

**Comment by neekibo** [comment]
@mweststrate Does this clarify my use case to you? Is there a better way than walking the complete graph in an autorun-method? I really enjoyed leaving reducers behind and I do like mobx a lot. It seems to me a fairly common use case to get notified if a graph has changed.

**Comment by mweststrate** [comment]
@neekibo thought a bit about it, I think there are several ways to approach this

1. use `reaction(() => mobx.toJS(graph), () => model.isDirty = true)` (simple way to walk the whole tree)
2. we usually have viewModels that wrap models. In it we have temporarily dirty / new value state and computed props that wrap the original model (so things like `@computed getName() { this.isDirty ? this.name : this.model.name }` and then in the 'commit' we update the model with the local temporarily name value. But not entirely sure whether this is relevant for your problem domain
3. Use the `spy` api, but this is a global event handler, so that might not be very scalable. 
4. Not really related to mobx, but simple set a isDirty flag explictly whenever an action modifies the graph (some higher order function can help with this)

If I come up with other approaches I'll let you know :)

**Comment by neekibo** [comment]
@mweststrate thank you very much! Suggestion 1 (toJS) is a neat trick and it works great. I will use it. I thought about suggestion 4. but I am not experienced in writing decorators/higher order functions and I have a lot of @action-methods.

Thanks again for your help and thoughts and for MobX!

**Comment by mweststrate** [comment]
By the way, totally forgot to mention: the `intercept` is also quite convenient for patterns like this. Although there is no `deepIntercept`, it is is a perfect hook to use if your graph is not too complex, to change an isDirty flag. Probably not perfect for this use case, but keep it in mind :)

E.g: 
```
mobx.intercept(myObservableObject, () => {
  console.log("modifying some attribute of myObservableObject")
  isDirty = true
})
