### ISSUE TITLE
Does MobX Optimise Array.map?

### ISSUE THREAD

**Issue by ronag** [mobxjs/mobx#429]
e.g. if I do this:

```javascript
@computed get items () {
  return ids.map(id => new Item(id))
}
```

Will MobX reuse items or recreate everything every time? i.e.

```javascript
ids = [0]
ids = [0, 1] // new Item('0') could be re-used
ids = [1] // new Item('1') could be reused
```

This issue and debouncing is what's keeping me from leaving RxJS.

**Comment by mweststrate** [comment]
No, `map` by default creates a fresh, dumb, plain javascript array. However, using create transformer you can make this mapping memoizable:

```
const idToItemTransformer =  createTransformer(id => new Item(id))

@computed get items() {
   return ids.map(idToItemTransformer)
}
```

Note that the transformation automatically garbage collects, so make sure that the computed value is in use by some reaction to benefit from the optimization. For further details: https://mobxjs.github.io/mobx/refguide/create-transformer.html.

In the future "liveMap" and similar operations will be added that returns an observable array. This has the advantage that only changes need to be mapped, instead of the complete array. See #166 

Debouncing is available for `reaction` and `autorunAsync`. See the docs. 

For extensive async, time driven events RxJS is still a good choice. See also: https://github.com/mobxjs/mobx/wiki/Mobx-vs-Reactive-Stream-Libraries-(RxJS,-Bacon,-etc)
