### ISSUE TITLE
Dependency tracking implementation

### ISSUE THREAD

**Issue by bennidi** [mobxjs/mobx#437]
Just a quick question about the way mobx constructs dependency trees of observers. Are dependency trees updated any time an oberserver is executed such that formerly untracked values are incorporated? Am I right assuming that I have to access all values that I want to subscribe to, regardless of whether I use would need them in the current execution. Example: My initial render() does not use a certain variable of my model but obviously wants to be reexecuted when the underlying value changes. I would have to read that value no matter what. Is there a best practice for this situation?

I have read [this article](http://www.knockmeout.net/2014/05/knockout-dependency-detection.html) about how knockout does the tracking. Is that comparable to what mbox is doing?

UPDATE: Seems I have overlooked the full explanation in [autorun docs](http://mobxjs.github.io/mobx/refguide/autorun.html):

` autorun will only observe data that is used during the execution of the provided function.`

Still interested to know whether the tree updates after first creation...

**Comment by mattruby** [comment]
For what it's worth, my understanding is that no you do not need to "touch"
all observed values initally.  In an autorun for example, I may have an if
statement that will stop the execution of some code. When the if block is
satisfied, the code inside will fire and then be observed.

**Comment by bennidi** [comment]
@mattruby I don't quite understand what you mean by `stop execution at some point`. Also I would be very keen to see how it is done that a dependency tracker knows about my dependencies without the client code every calling them...

**Comment by mattruby** [comment]
@bennidi It adds them to be tracked as they're accessed.  Here's a simple example: https://jsfiddle.net/s8c9q0v0/3/
See the mobx.whyRun() output change based on the active index.  Does that help clarify what is being watched?

**Comment by urugator** [comment]
I have been using MobX just a few days, but here is my perspective:

"My initial render() does not use a certain variable ..."

If you mean by it, that the observed value is only accessed conditionally and it's not accessed on the first run, because the condition is not satisfied, than it won't be registered as dependency and observer (render) won't be triggered on the value change.
If the observed value is not used, it means that it does not have any impact on rendered output and therefore there is no need to track it's changes.
This will change, when the the condition outcome change - the value gets accessed and therefore registered as observer's dependency - when it's actually used for rendering.

What you're not realizing (I think) is that aside from you'r conditionally used observed value, there must actually be another value holding a state. The value that decides the outcome of the condition.
And that value will be the one causing the rerendering in the end.

However if you need to autorun a function, when some particular observable(s) changes, check "observe" and "reaction":
https://mobxjs.github.io/mobx/refguide/observe.html
https://mobxjs.github.io/mobx/refguide/reaction.html
(but I can't imagine why you would need it with render() method)

**Comment by bennidi** [comment]
@urugator Thanks for helping me do the thinking part here :+1:
