### ISSUE TITLE
[mobx] Invariant failed: Cannot obtain administration from [object Object] inside a class with observables

### ISSUE THREAD

**Issue by mattiamanzati** [mobxjs/mobx#444]
Hi everyone!
I am trying to replace a large MVVM app codebase with some mobx bits.

The old app core had a property decorator that calls before[PropertyName]WillChange and after[PropertyName]DidChanged when a property changes and I was telling the UI to change using a notifyPropertyChanged(object, "propertyName")

I would like to only rewrite the base class. i order to avoid an entire app rewrite, but I am struggling with setting up intercept and observe on ES6 object constructor.

I set up a webpack bin to show up the problem: http://www.webpackbin.com/V1uG1iG_b

```javascript
import {observe} from 'mobx'

class ViewModel{
  constructor(){
    this._disposers = [
      observe(this, (change) => {
        bin.log('change!', change)
      })
    ];
  }
}

class LoginViewModel extends ViewModel{
  @observable username = ''
}

const viewModel = new LoginViewModel()
viewModel.username = 'change!'
```

```
VM200 bundle.js:2Uncaught Error: [mobx] Invariant failed: Cannot obtain administration from [object Object]invariant @ VM200 bundle.js:2getAdministration @ VM200 bundle.js:2observeObservable @ VM200 bundle.js:1observe @ VM200 bundle.js:1ViewModel @ main.js?ee81:6(anonymous function) @ main.js?ee81:14(anonymous function) @ VM201 main.js:47__webpack_require__ @ VM201 main.js:20(anonymous function) @ VM201 main.js:40(anonymous function) @ VM201 main.js:43
VM202:1 '//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
```

**Comment by mweststrate** [comment]
As far as I can see, the decorators seem not to be applied at all in webpackbin. Not sure how webpackbin is supposed to work / set up with custom babel plugins like `transform-decorators-legacy`. Note that your bin doesn't even import `observable` in the first place, so that the script even starts in the bin sounds like a bug in webpackbin to me. 

Besides that, it is correct that your fiddle throws; because the ViewModel constructor is called _before_ the LoginViewModel constructor, the observe is established before the `username` is introduced. However, the object is not an observable object at that time as no observables where introduced on it yet. Simple giving the ViewModel an observable property as well, or moving the observe subscription to the constructor of the LoginViewModel fixes this.

See:

http://jsbin.com/dobehu/1/edit?html,js,console,output

**Comment by mattiamanzati** [comment]
Fixed! Thanks!

```javascript
export class ViewModel{
    // used to avoid https://github.com/mobxjs/mobx/issues/444
    @observable private _SUPER_SECRET_PROPERTY_DO_NOT_USE_OR_YOU_WILL_BE_FIRED_PLZ = false
}
```
