### ISSUE TITLE
decorate action when change state in autorun

### ISSUE THREAD

**Issue by dreambo8563** [mobxjs/mobx#457]
I hope find the card and assign it to local observable automatically.
the problem is when I turn on the strict mode. there is a warning about action.

I don't know if there is a way to add the action decorator for the autorun or other solution to make it reactive

the repo https://github.com/dreambo8563/mobx-KanbanBoard

```js
  @observable editCard = {
        id: Date.now(),
        title: '',
        description: '',
        status: 'todo',
        color: '#c9c9c9',
        tasks: []
    };

    componentDidMount() {
        autorun(() => {
            console.log("autorun")
            this.editCard = appState.cardsList.find((card) => card.id == this.props.params.card_id) || this.editCard;
        })
    }

```

**Comment by mweststrate** [comment]
Hi @dreambo8563, 

I think you found a typical example of a case where you want to use `computed` instead of `autorun`. If you have an autorun assigning a value instead of triggering some effect, computed is the better choice. They are easier to trace and will be cleaned up automatically in contrast to autorun which needs manually disposing in the `componentWillUnmount`. So I would recommend something like:

```javascript
    @observable defaultEditCard = {
        id: Date.now(),
        title: '',
        description: '',
        status: 'todo',
        color: '#c9c9c9',
        tasks: []
    }
    @computed get editCard() {
         return appState.cardsList.find((card) => card.id == this.props.params.card_id) || this.defaultEditCard

    }
```

For completeness sake, it is indeed possible to change the state in autorun in strict mode, by wrapping an action. Make sure that the autorunnable part happens outsid that action though, because mobx won't track actions to avoid confusion (now this explanation might sound a bit confusing, but remember from the overview image of MobX that actions should not depend on state but produce it, hence they are untracked by default):

```javascript
autorun(() => {
            console.log("autorun")
            var nextCard = appState.cardsList.find((card) => card.id == this.props.params.card_id) || this.editCard;
            runInAction(() => this.editCard = nextCard)
})
```
\which can be written in a nicer way as (a reaction is an tracked expression that triggers an action if the output changes):
```javascript
reaction(
  () => appState.cardsList.find((card) => card.id == this.props.params.card_id) || this.editCard,
  (nextCard) => this.editCard = nextCard
)
```

But, in this case using computed is the better choice

**Comment by dreambo8563** [comment]
thank you so much.
