### ISSUE TITLE
Should @action autobind method to store?

### ISSUE THREAD

**Issue by satispunk** [mobxjs/mobx#458]
Hi,

When I use
```jsx
class Store {
    @action method() {
        this.prop = 'some'
    }
}

// then in component 
render() {
    return <button onClick={this.props.store.method} />
}
```

In this case it fails as 'this' in action not bound to something.

Workarounds are:
```jsx
<button onClick={(e) => this.props.store.method()} />
```
With this I should write inline arrow functions or write extra handler in component instead of just passing prop.

```jsx
@action method = () => {
}
```
This doesn't support inheritance

**Comment by Kukkimonsuta** [comment]
I believe this is correct and `@action` should not autobind, if you need such behavior you can always

```
import { autobind } from 'core-decorators';

class Store {
    @autobind @action method() {
        this.prop = 'some'
    }
}

// then in component 
render() {
    return <button onClick={this.props.store.method} />
}
```

And everything will work correctly.

**Comment by mweststrate** [comment]
Correct, `@action` is indeed not supposed to bind, but respects the normal javascript scoping rules. Note that bound methods never support inheritance, because the same property cannot exist twice on the same object instance. (Binding moves a function from the prototype to the instance and binds it) This is further not related to MobX.

**Comment by satispunk** [comment]
Guys, thx for clarification, totally agree
