### ISSUE TITLE
Can the values of @computed be changed?

### ISSUE THREAD

**Issue by arddor** [mobxjs/mobx#468]
First, thank you for mobx, it's great. 

I'm trying to find the best way to approach my usecase: I have a `matrix` and `vector` which should have the dimension according to `rows` and `columns`:
```javascript
class State {
  @observable rows = 3;
  @observable columns = 3;

  @observable vector = [1, 1, 1];
  @observable matrix = [
    [1,1,1],
    [1,1,1],
    [1,1,1]
  ];
}
```
When changing `rows` or `columns` the size of `matrix` and `vector` will adjust. However the user can also change the values in `matrix` and `vector` and on increase they should not be overwritten.

So my questions is if this usecase can / should be done with `@computed` or in the `@action` which changes row or columns or if a `@reaction` would be appropriate?

The problem with `@computed` is that I'm not sure if it is acceptable that it depends on the size, but I will later on change the values in it.

**Comment by mattruby** [comment]
If I understand, yes, you should use computed for rows and columns.  If you
cut a fiddle, I'll double check for you.  Here's a baseline :
https://jsfiddle.net/gh/get/library/pure/mattruby/mobx-examples/tree/master/baseline

**Comment by mweststrate** [comment]
Personally I'm not sure whether I would set this up as a derived value, but instead set up the matrix in an action, probably you need some special logic if elements need to be added or removed, and you probably want to retain the current collections as they already might have data in them? So I would personally just introduce a ` setRows` action. Using computed is a bit tricky here as it would need some work-arounds to make sure you don't return new collections each time the computed value is updated (unless that is not an issue of course)

If you still like it to react automatically to a change of `rows` (instead of  calling an action explicitly), you can also set up a `reaction(() => this.rows, rows => this.setRows(rows))`.

**Comment by arddor** [comment]
I played around with it and I have to say that it makes more sense to do the changes with an action. I assume to prevent the changes in case of faulty values (e.g. below 0) I can just do `reaction(() => this.rows, rows => if(this.rows > 0){this.setRows(rows)})`? Anyway thank you for the help.

**Comment by mweststrate** [comment]
Yep, (note that (if rows > 0)) would be nicer)

Op vr 12 aug. 2016 om 00:08 schreef Marc Heimgartner <
notifications@github.com>:
