### ISSUE TITLE
deprecate `untracked` ?

### ISSUE THREAD

**Issue by dzearing** [mobxjs/mobx#49]
One dangerous thing we've encountered in the past with Knockout's computed observables is implicit subscriptions. In cases where you evaluate an observable one time on startup and don't care about future updates, you need to "peek" at the observable.

```typescript
@observable foo: string;
@observable get bar() {
  return peek(this.foo);
}
```

Is there a way to peek at an observable without taking the dependency in the computed observable? Sorry if I'm missing it!

**Comment by mweststrate** [comment]
Currently there is no such thing. I thought of it, (it's easy to add) but didn't find a use case for it yet :). Note that a dependency is only made if you peeking code is inside `autorun` or `@observer`, otherwise no subscription is made, but the value is just computed on demand.

**Comment by dzearing** [comment]
FWIW when we rewrote onedrive.com in knockout, we found computed observables taking dependencies implicitly and unintentionally (for example, calling a helper function in a computed that would access an unrelated observable value), and it would have perf implications. So we opted to always use "peek" for getting values, unless you really needed the computed mutation to occur. We were considering a more explicit model of computed modeling that was less error prone, where instead of creating implicit subscriptions, you have to explicitly opt in to it. E.g.:

Instead of:

```typescript
let foo = ko.computed(() => a() + b() + c.peek());
```

You explicitly opt in, and general access doesn't auto subscribe:

```typescript
let foo = customComputed(() => a.subscribe() + b.subscribe() + c());
```

This would make it easy for devs to do the right thing (avoid unnecessary subscriptions and by extension performance issues) and a little more difficult to do the expensive thing (create subscriptions that cause the computed to mutate).

I'm not asking to really change to the explicit model above, but I do think there is a use case for peek.

**Comment by mweststrate** [comment]
Hi David,

So far 'unexpected' dependency actually saved a lot of UI bugs for us so far. The simple idea behind it is; if you actively use a value *somewhere*, the outcome of your function does depend on it; otherwise you shouldn't be using the value in the first place. So far this didn't bring us in performance issue yet that couldn't be easily solved by either wrapping mutations in a `transaction`, or by splitting up the computations in multiple smaller ones (unchanged (computed) values won't trigger upstream computed values to re-evaluate). Opt-in instead of opt-out feels to me like a premature optimization that can cause a lot of staleness bugs if you forget to actively subscribe (which will happen eventually).

That being said, probably there should be an opt-out possibility in the future. Maybe something along the lines of `mobservable.unobserved<T>(() => T): T` which can be used inside `autorun` / `@observer` / `observable`. Any data accessed inside `unobserved` should then be treated as a 'peek' inside the value. E.g:

```javascript
let foo = observable(() => a() + b() + unobserved(() => c() + d()))
a(3); // updates foo (if observed)
c(5); // never updates foo
```

**Comment by mweststrate** [comment]
Releases as part of 1.1.0, `mobservable.untracked`. Further as described in the example above.

**Comment by jameslk** [comment]
I've decided to try this feature out as a more appropriate alternative to observe() (since it doesn't respect transactions). I only wanted to observe one thing very explicitly and when it changed I wanted it to run an initializer function, without having to worry about having my initializer function called again for something else. Here's the code I created to do this:

```javascript
function observeItem(observableItem, watcher) {
    return autorun(() => {
        const value = observableItem;
        return untracked(() => watcher(value));
    });
}
```

which I use like this:

```javascript
observeItem(someImportantUiState, (newValue) => {
...perform some initialization code
});
```

I'm not sure if I'm going about this correctly or if there's a better way of doing this? Or perhaps I'm just abusing the design of things completely?

**Comment by mweststrate** [comment]
Hi @jameslk you might want to take a look at these 10 lines, that implements the `observe` api using autorun and does respect transactions (it didn't make it into 2.0 in the end), but the pattern still works and is similar to yours: https://github.com/mobxjs/mobx/commit/c3a5520b420ac9ccffa406dec7c5b87a448b1222#diff-f5b5b227f456456dd2aca7183f1f2c26R51

This one does as you correctly mention, track the things you do in the handler. However since MobX 2.0 can now handle cycles triggered by autoruns, that might now work as expected while it would throw in Mobservable 1.

But if not being triggered by something else is important in your code, then your approach is perfectly fine. Of course it might be interesting in that case to answer the question: _why_ should it not be triggered by something else, if that 'something else' is apparently used in the `watcher`? Answering that question might maybe lead to using `when` or another approach to the problem.

I hope that helps! Otherwise feel free to elaborate more on the case, that might make the answers more to the point and less vague.

**Comment by jameslk** [comment]
Hey @mweststrate, thanks for the helpful response! I think I was burned a number of times by the error regarding cycles in autorun so I just became compulsively weary of it :) But with that no longer the case, I'll try to do things more normally.

In this specific scenario, however, I run some initialization code to fetch data from the server and I only need to do it once per unique value of the observed item. I also test to see if initialization was already run for that value, but I felt it was cleaner regardless to have it run only when the value changed.

I'll take a look at `when` to see if it might be more appropriate. Thanks again for your help!

**Comment by andykog** [comment]
Consider situation where we want to send comment text to server, but only if user is loged in.
It was easy with `untracked`:

```js
const state = observable({
  commentText: "",
  userLoggedIn: false,
});

autorun(() => {
  const json = state.commentText;

  // we don't want to mave make request
  // every time user logging in/out
  const loggedIn = untracked(() => state.userLoggedIn);

  if (loggedIn) {
    httpApiRequest(json);
  }
});
```

@mweststrate, how would you solve this without `untracked`? Use `observe`? May be, some hack like this?
```
let untrackedLoggedIn;
autorun(() => untrackedLoggedIn = state.userLoggedIn)
autorun(() => {
  const json = state.commentText;
  if (untrackedLoggedIn) {
    httpApiRequest(json);
  }
});
```

**Comment by mweststrate** [comment]
@andykog I think `untracked` will stay. I'm even considering putting the new `@actions` always in an `untracked` so that actions never can fire automatically (but maybe you want to trigger an action from an autorun? don't now)

Besides that, I think the following is a nice solution to your case?

```javascript
const state = observable({
  commentText: "",
  userLoggedIn: false,
});

when(
  () => state.userLoggedIn
  () => httpApiRequest(state.commentText)
)
```

**Comment by andykog** [comment]
Oh, I completely missed that there is such thing. Unfortunately, doesn't seems that your snippet works, https://jsfiddle.net/Sl1v3r/4dso36c3/ I'll take a closer look at `when` to say why :-)

**Comment by mweststrate** [comment]
Oh note that  `when` runs only once, and the action is not tracked or something, so in your case you probably need:

```javascript
when(
  () => state.userLoggedIn
  () => autorun(() => httpApiRequest(state.commentText))
)
```

**Comment by andykog** [comment]
@mweststrate, in that way it doesn't respect the condition: https://jsfiddle.net/Sl1v3r/4dso36c3/

**Comment by mweststrate** [comment]
argh more acceptance criteria!

```javascript

when(
  () => state.userLoggedIn
  () => {
     const submitDisposer = autorun(() => httpApiRequest(state.commentText))
     when(
        () => !state.userLoggedIn,
        submitDisposer
  }
)
```

**Comment by uweg** [comment]
Is this still experimental? According to documentation, it is. Just to let you know: I'm using this feature to avoid unwanted dependencies and performance issues that come with it.

**Comment by mweststrate** [comment]
Nope it is a landed feature now, since mobx 2.2. I'll update the docs.

**Comment by Yaakov-Belch** [comment]
Thanks for having a permanent `untracked` feature.  I am using it in my application now...

**Comment by mweststrate** [comment]
Yeah I just noticed that that message is accidentally still in the docs,
should have been removed a long time ago :)

Op wo 17 aug. 2016 om 23:26 schreef Yaakov Belch <notifications@github.com>:
