### ISSUE TITLE
Autorun doesn't trigger when calling actions

### ISSUE THREAD

**Issue by winterbe** [mobxjs/mobx#490]
Hi,

while experimenting with MobX I've encountered an issue when calling actions from autorun.

I've set up a jsfiddle to demonstrate the scenario: https://jsfiddle.net/o0j1115z/1/

In this example when you click on the checkbox, the value of `controls.flag` change. I would expect method `loadMessage` to get called via `autorun` but that's not the case. However if you remove `@action` from method `loadMessage` the method gets called by autorun as expected.

The best workaround I found was changing the code like this:

```js
  constructor() {
  	autorun(() => {
    	console.log('auto-load message');
    	this.loadMessage({...this.controls});
    });
  }  
  
  @action loadMessage(controls = this.controls) {
  	const flag = controls.flag;
        setTimeout(() => {
          this.message = flag
            ? 'Flag is enabled'
            : 'Flag is disabled';
        }, 300);
    }
```

However this would be rather confusing to read for other team members.

Is this a bug or intended? It's kinda confusing that autorun behaves differently for actions and "normal" methods.

Please correct me if I made a fundamental mistake.

Thanks in advance.

**Comment by mweststrate** [comment]
This is the expected behavior, actions are [untracked](http://mobxjs.github.io/mobx/refguide/untracked.html). The idea behind that is that actions are intended to modify state, so having them reacting to state changes as well might quickly lead to unwanted loops. The pattern above is typically expressed using `reaction` where the data to be tracked, and the side effect reacting to that data are clearly separated:

`reaction(() => this.controls.flag, flag => setTimeout(....))`

**Comment by winterbe** [comment]
Thanks for the hint. I guess I missed the `untracked` part about actions.

I've updated the jsfiddle to use `reaction` instead of `autorun`:

https://jsfiddle.net/o0j1115z/4/

It works as expected, however using this function as first parameter to `reaction` doesn't seem to work: `() => this.controls`. I guess it's because `this.controls` doesn't get dereferenced so I have to explicitly access `flag1` or `flag2`?

Thanks for helping out on that! 👍
