### ISSUE TITLE
How to add observer to a component in node_modules

### ISSUE THREAD

**Issue by sagarparikh** [mobxjs/mobx#537]
Hi,

This is my first project in Mobx, I am trying to migrate from Redux to Mobx. 

I am working on a dashboard project for which I require an editable data grid. I am using Material-ui with React and Mobx. So instead of building one i picked up -> http://bit.ly/2c8Kuj0. 

I have my store and everything setup all going well until the above grid wouldn't get updates from the store. I was already in the POC and had to submit it that day itself hence there was no going back, instead of trying to find an innovative solution I went ahead and forked the repo and added observer to the component. What is a good way to get around this, I am sure it's an easy solution but unable to get my way around it.

Thanks,
Sagar

**Comment by urugator** [comment]
I quess I am missing something, but maybe...?
```javascript```
const observer = require('mobx-react').observer;
const EditTable = observer(require('material-ui-table-edit'));
```

**Comment by mweststrate** [comment]
Note that it is a bit risky to add `observer` around existing components as it could break internal assumptions of the component. I recommend converting observables to plain objects in the parent component (with `@observer`) before passing them to external components.

Closing since the question was also answered on twitter if I'm not mistaken ;-)
