### ISSUE TITLE
Using MobX with Immutable.js data structures

### ISSUE THREAD

**Issue by jvorcak** [mobxjs/mobx#538]
Hi,

I've started integrating MobX in one of my projects and it solves a lot of previous problems I used to have. However, I'd like to use Immutable.js for my data structures. The reason for it is that the structural sharing is very important for me in this project (especially comparing by id ref) + the core concept of immutable data structures really fits into my project).

I'm wondering, is it a good practice to use Immutable.js in MobX or does it kill MobX core concept? 
What if I have sth like this? https://tonicdev.com/jvorcak/57cec8b508d7f71400753c45
Autorun works, but I assume there is something conceptually wrong about this (I suspect that it could kill `shouldComponentUpdate` optimisation when using with React), so I want to see someone else's opinion. I've searched for answers online, but there is not so many threads on this topic.

Is it OK to do it like this? If not, why? Thanks a lot for an answer.

**Comment by urugator** [comment]
I think it depends on how far you want to go with immutability:
```
app = {
  persons: [
    { person:       
      comments: [
        { text: "foo"; }
      ]
    } 
  ]
}
```
Consider all objects are immutable and observable and you want to change text of the comment.
Comment is immutable so it can be changed only by replacement. Because comments array is immutable it must be replaced as well, same goes for person, persons array and finally the app itself.
Ideally we would like to update only components, which depends on comment's text, but a lot more observable references has been changed, so all component's depeding on them will be updated as well.

To overcome this, we would have to define a special way for observing object references. Instead of comparing them by value, they would have to compared by ID's.
So for example replacing a person by a different updated person instance with the same ID, wouldn't update observers observing for persons array.
I don't know if it can be done with mobx, maybe take a look at [Atoms](http://mobxjs.github.io/mobx/refguide/extending.html)

**Comment by jvorcak** [comment]
@urugator first of all, thanks for your answer. I was thinking you could compare by [is()](https://facebook.github.io/immutable-js/docs/#/is), that is the fastest you can get, right?
You're right that you would replace the whole object up to the root, but you could also decide whether or not to `shouldComponentUpdate` everything in that object by calling fast `is()`method.
The root object would be mutable as I show in the example.

```
const mobx = require('mobx');
const Immutable = require('immutable');
const {Map} = Immutable;
const {autorun, observer, observable} = mobx;

const person = observable({
    info: Map({
        name: Map({
            first: "Jan",
            last: "Abc"
        })
    })
});

autorun(() => console.warn(person.info.getIn(['name', 'last'])));

person.info = person.info.setIn(['name', 'last'], 'a');
person.info = person.info.setIn(['name', 'last'], 'b');
person.info = person.info.setIn(['name', 'last'], 'c');
```

**Comment by Strate** [comment]
I had the same issue, and I've chosen to migrate from Immutable structures to mutable observable structures. First of all, I've reduced set of immutable's api to use, then I made a wrapper around arrays & maps and reimplement that api, and then change usage of immutable structures to my own.

**Comment by urugator** [comment]
@jvorcak Note that only observable field in your example is `info`. 
Fields `name`, `first`, `last` are not observable. 
The autorun runs only because of the replacement propagation of immutable structures.
The propagation ends by replacing value of `info`, which eventually triggers the autorun.
So in the end, you're not in fact combining immutables with observables, there is no object which would be both immutable and observable at the same time.

Preventing update in `shouldComponentUpdate` could work, however what's the point of MobX than?
MobX would always update the "root", no matter which observable in the immutable subtree would change.
You would get the same result without declaring the objects in the immutable subtree as observable.

**Comment by jvorcak** [comment]
@urugator exactly, I would mark only the "root" as observable and treat it's nodes as immutables. The point of MobX in my application is that it rerenders my React components once the relevant part of the this root tree changes. Now the question is, is this approach necessarily a bad practise?

**Comment by urugator** [comment]
Hard to talk about "approach" if we don't know to which problem, so it's hard to offer any alternatives. 
You asked `does it kill MobX core concept?`, I would say it kind of does, or at least there are incompatibilities. 
However, from what you say, you don't need to observe immutable structures at all, just a references to them.
In that case I don't see any problems.
Just keep in mind that MobX will update ONLY every component with the occurence of `person.info` in it's render method, nothing else.

**Comment by jvorcak** [comment]
Thanks for your help @urugator I'm closing this one.

**Comment by dhenson02** [comment]
@jvorcak while I'm sure you've resolved this for yourself by now, you may be interested in this solution:

https://github.com/tictail/tide

https://medium.com/tictail/introducing-tide-our-react-state-management-library-1dcc6e80551e#.p4bcoep7q

IMO this is basically a "redux meets mobx"

**Comment by jwalton** [comment]
This is a state library I wrote that looks and feels a lot like MobX, but uses immutable data.  You do need to use selectors to fetch state from a React component, but you get "stores" or "controllers" that you can create locally in a component, and that you can unit test without any React.  Best of all, the library is tiny - mobx + mobx-react-lite is about 18.2k min-zipped, but SoloX is only 3.6k, and only 1.2k without immer.

https://github.com/jwalton/solox

The whole library is so small, you can easily read the source and understand what's going on, and I have a post that walks through how it was developed:

http://www.thedreaming.org/2021/08/10/solox/
