### ISSUE TITLE
Uncaught Error: [mobx] Invariant failed: Cannot obtain atom from [object Object]

### ISSUE THREAD

**Issue by foxhound87** [mobxjs/mobx#570]
I don't know why I'm getting this error.

I'm calling a method inside componentDidMount which calls another method with an action. 
It just update the observable object keys: https://github.com/foxhound87/mobx-react-matchmedia/blob/a24ccb8c9bcb6be5c70e54ecdcc23dc14f6c4a55/src/MatchMediaProvider.jsx#L23

The error appears only if I activate the mobx-react-devtools logging.
If I don't activate it, the lib is working without problems.

I created a demo if needed: 
https://github.com/foxhound87/mobx-react-matchmedia/tree/master/demo

**Comment by foxhound87** [comment]
I just noticed that my form library has a similar error,
in this case the error is thrown here:

https://github.com/foxhound87/mobx-react-form/blob/e39cd14ab4c221329601e34214cab1775e30ae87/src/Form.js#L88

It seems like I cannot use computed values inside a promise.
It also throws: `error: [mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer`

No error when devtools are disabled.

**Comment by amir-arad** [comment]
In my experience this happens when you have more than one copy of Mutable in your module system. the ```getAtom``` function [check for atoms using ```instanceof``` javascript operator](https://github.com/mobxjs/mobx/blob/1a44ed75ded08d79c18b8b7b8465d86ec3de6499/src/types/type-utils.ts#L32), which uses nominal typings (checks ```thing.__proto__.constructor === BaseAtom```) instead of using duck typing (``` typeof thing. reportObserved === 'function' && typeof thing. reportChanged === 'function'```).
The rationale here is, when you have multiple instances of the Mobx module, you have multiple instances of the module's constructor functions, with no pointer equality between the two otherwise matching functions.

**Comment by foxhound87** [comment]
The html-webpack-plugin was injecting 2 time the build.js into the index page.
