### ISSUE TITLE
Do implicit reactions that are generated by @computed or @observer require some kind of disposal?

### ISSUE THREAD

**Issue by nadavsof** [mobxjs/mobx#578]
calling observe() returns a function that should be called for disposing the reaction. It seems that mobx has no way to know that an object which has a getter marked with @computed should be disposed.

If that's true, when an object X has a getter marked with @computed that returns some computation on object Y, then as long as Y is alive, it keeps X alive. Seemingly, there should be some dispose() function to call on X to let mobx know it should kill all the reactions X has.

I wanted to ask if this is true and such disposal should be done, and if so, how should we dispose such objects, because @computed, unlike observe(), does not return a dispose function.

Thanks!

**Comment by jeffijoe** [comment]
I had this question earlier as well and from what I understand from @mweststrate it would appear that the disposer function being returned is purely a convenience for you to dispose _early_. When nobody cares about the reaction/computed anymore, all subscriptions have already been removed (If I understand correctly), and can therefore be GC'ed with no issues.

**Comment by nadavsof** [comment]
Thanks jeff for the reply. But wouldn't the observable keep the observer alive because it would hold a reference to it, not enabling GC to clean it?

Same problem happens in some other UI frameworks when you register to events and need to unregister later. UI framework can theoretically handle it when a component unloads from the visual tree, but here we are talking about POJOs that don't have unload events.

So how is it possible that the GC would know that no one uses the POJO observer (not @observer but just a pojo with @computed) when the observable would have a reference to it?

**Comment by jeffijoe** [comment]
@nadavsof good question, and I don't have an answer but I'd like to know as well :) @mweststrate care to pitch in?

**Comment by mweststrate** [comment]
@nadavsof @jeffijoe the difference between computeds and reactions is that the one produces a value and the other an effect. For effects, MobX cannot determine when they need to stop, so preferably they need to be stopped manually, so that MobX can move the subscriptions. They can however be cleaned up, if they only refer a specific (set) of objects, and those objects in there entirety become unreachable. So you get a detached graph and only in that case they can be GC-ed. So not that reactions cannot automatically GC-ed as long as any observable object used in it is still reachable. 

Computed values are however much simpler, MobX just tracks whether they have any active observers (other computeds or reactions). As soon as that isn't the case, the computed value is suspended, that is, all observation is stopped. So that means that at that point the observed object will no longer now about the computed value it is used by. This means that the computed value can be safely cleaned up. (Not the other way around, as soon as the computed value is used again, the observation is continued, which can be done because the expressions still hold a reference to the observed object in their closure). 

I hope that helps :) In images it is probably a lot easier to explain than with words ;-)

**Comment by jeffijoe** [comment]
So the question is, should we be worried about code like this not being cleaned up?

```js
class Wee {
  @observable test = ''
  
  constructor() {
    autorun(() => {
      sendRequest(this.test)
    })
  }
}
```

**Comment by mweststrate** [comment]
It depends, if `sendRequest` implementation itself doesn't access any other observables it is safe. (To make sure not to make mistakes with that `reaction` (or untracked) is useful: (`reaction(() => this.test, d => sendRequest(d))`)

**Comment by jeffijoe** [comment]
What observables would it have to access to make it unsafe?

**Comment by mweststrate** [comment]
@jeffijoe in the `sendRequest` case it is a bit hard to find such a case, but you could have for example:

```
userStore = new class {
  @observable loggedIn = false
}

sendRequest(data) {
  if (UserStore.loggedIn)
     sendXhr(data)
}
```

But it is a bit artificial example, as this one is buggy ;-). It would re-run the autorun if the `loggedIn` status toggles which is probably not the intention in the first place. But similar patterns one could have when you have for example prices of order lines, which are calculated using a global VAT. The price would depend on the VAT, and the VAT would keep the autorun of each order alive.

**Comment by jeffijoe** [comment]
Ah, I see - so if `autorun` only uses internal state of the class, then it's no problem? Won't that `globalState` keep it alive?

**Comment by mweststrate** [comment]
@jeffijoe `globalState` in the mobx sources you mean? Nope, that is only used during mobx function runs, but if your app is idle, there is nothing in there

**Comment by jeffijoe** [comment]
Aha, got it! Thanks for clarifying!

**Comment by nadavsof** [comment]
Thanks for the helpful answer!
