### ISSUE TITLE
Communication Between Stores

### ISSUE THREAD

**Issue by Kamaraju333** [mobxjs/mobx#622]
I think this question might been asked before but i havent got the answer what i require .
Please find below the scenario :

Class ExampleStore {

@action
getExamples(){
agent.get("https://abc.com/examples-api/examples").then((result)=>{
//I have to update the messages 

approach 1:Update the state Directly
MessageStore.messages.push("Retrieved successfully")

approach2:Update the state using an action 
MessageStore.setMessages("Retrived SuccessFully")
)

}
}

Class MessageStore{
@observable messages

@action
setMessages(message){
this.messages.push(message)
}
}

Can you say me which approach is better and should be followed .

**Comment by nightwolfz** [comment]
If you go for approach 1, you will need to wrap the `callback` of `agent.get` with `action()`.

```
getExamples(){
    agent.get("https://abc.com/examples-api/examples").then(action(result =>{
        ....
```

Personally I prefer approach 2.

**Comment by urugator** [comment]
The @action approach is more robust, but obviously adds a little more complexity, so I woudn't necessarily claim it *should* be followed.

1) You can introduce or customize any behavior later, without changing the client code.
For example introduce conversion, validation, logging, metrics, notifing other parts of the system, change the way the messages are internally stored (replace an array for some Messages object), etc...

2) You can prevent the client to change the state in uncontrolled way (possibly leading to state inconsitentcy)
However to really ensure that, you would also have to change the way how messages are obtained - either by providing reading methods directly on MessageStore, or by making returned messages object read only (but still using the state under the hood).     
 
Btw setter can be action as well.

**Comment by Kamaraju333** [comment]
@nightwolfz 

Why do we need an action in approach 1?

**Comment by Kamaraju333** [comment]
@urugator as per point a, do we have a approach to achieve that ? more like an interceptor

**Comment by urugator** [comment]
In some of the mentioned scenarios, interceptor (or aspect oriented programming in general) could be appropriate, but I woudn't consider it as a possible overall solution to the problem.
Let's say you want to introduce logic which also changes some another internal state, so you would simply update `setMessage` like this:
```javascript
@action
setMessage(msg) {
  this.messages.push(msg);
  this.messageSetCount++; // changing another state  
}
```
With interceptor, first obvious problem is that you can't intercept `messages.push`, only `messages`, so to know that message was added, you would have to somehow diff the change of `messages`.
Second problem is, that you're now changing 2 state fields at the same time, so you really want to introduce action (or transaction at least). You can't do that in interceptor, because it intercepts only a change of the single field. 
And the biggest problem, it would add even more unnecessary complexity.

**Comment by nightwolfz** [comment]
@Kamaraju333 because it's the callback function that updates the state.

**Comment by mydbol** [comment]
You really should never change state without an action. I will make debugging difficult. just my opinion.
