### ISSUE TITLE
Observable Objects 

### ISSUE THREAD

**Issue by Kamaraju333** [mobxjs/mobx#624]
Simple question on observables how they behave 

Class TodoStore {
@observable todo 

createTodo(){
this.todo = new Todo("test","home")
}

}

class Todo {
id
@observable name
@observable type
status

constructor(name,type){
this.status="Active"
this.name=name
this.type=type
}

}

or Should I have to give as below 

Class TodoStore {
@observable todo  ={
name:"",
id:="",
status:"",
type:""

}

}

Few questions for the above Example :
1.How will Observable work now , Todo store has a observable Todo , I am creating an observable using Todo Class which doesnt have is or status as observable , will those attributes be observable as I have a observable around todo in TodoStore

**Comment by urugator** [comment]
Afaik `@observable` basically does this:
1) Adds mobx administration object ($mobx property) to prototype if not already present  
2) Makes the property observable in a way that the observers are notified when the property value changes.
By default, the value is considered changed when `newValue !== oldValue`. If you use `asStruct` modifier, the values are compared deeply (as strucutre instead of as reference).  
3) If the property value is an array or a plain object (without prototype) and `asReference` modifier is not used, the mobx additionaly converts the value into observable object/array.

So answer to you question: No, `id` and `state` won't be observable, because `Todo` is not a plain object, so it's Todo's responsibility to make it's properties observable. 
https://mobxjs.github.io/mobx/refguide/observable.html

**Comment by Kamaraju333** [comment]
Thanks @urugator
