### ISSUE TITLE
Using when() in Jest test

### ISSUE THREAD

**Issue by benjamingeorge** [mobxjs/mobx#639]
When trying to convert the tests in this article [https://medium.com/@mweststrate/how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount-cc90b787aa37#.ra7lm9657](url) to Jest, it doesn't work because for async, Jest expects you to return a Promise from the "it" block.  So assertions in "when()" are never called.  Is there another way to test fromPromise() using Jest  ?

**Comment by mweststrate** [comment]
@benjamingeorge are you pointing at `fromPromise` specifically or `when` in general? 

For the first, you can just return `fromPromise(stuff).promise`. To test `when`, you could simply wrap the test in a promise. Note that [`whenWithTimeout`](https://github.com/mobxjs/mobx-utils#whenwithtimeout) might come in handy as well:

```
it("should work", () => {
  return new Promise((resolve, reject) => {
    whenWithTimeout(
      () => someCondition,
      () => resolve(),
      2000,
      () => reject("timeout")
    )
  })
})
```

This is quite some boilerplate, but it should be easy to create a generic utility around this. If you have one, feel free to create a PR on mobx-utils :)

On a side node, it is also possible to convert jest tests to mocha style tests, where a `done` callback is provided to the test instead of returning a promise. I heard some colleagues about that, but didn't see it yet.

**Comment by benjamingeorge** [comment]
Thanks for quickly shedding some light.  I was able to get a working test with your `fromPromise(stuff).promise` hint.  
```
describe('View Store routing', function() {
  it('it should be possible to open the shop rewards', () => {
    const viewStore = new ViewStore(stubFetch)
    viewStore.showShop()

    return viewStore.currentView.documents.promise.then(() => {
      expect(viewStore.currentView.name).toBe("shop");
      expect(viewStore.currentView.documents.state).toBe("fulfilled")
      expect(viewStore.currentView.documents.value.length).toBe(4)
    })
  });
});
```
