### ISSUE TITLE
Computed arrays and maps with useStrict

### ISSUE THREAD

**Issue by spiffytech** [mobxjs/mobx#646]
I have a question:

I routinely want an observable array or Map that's derived from other observables, but I can't find an elegant way to do this. Ideas are welcome.

`computed` isn't sufficient, because I want each element in the collection to be independently observable, instead of dereferencing the whole collection to access a single value (any change to any item would cause all observers of the collection to fire, even if their particular value hadn't changed).

I'm using an `IObservableArray` / `ObservableMap` and using `autorun` to watch the source collection and update the derived collections. But since I've enabled `useStrict`, my updates need to be done inside `action`s, which `autorun` can't track. So I wind up with stuff like this:

```js
const source = observable([]);
const dest = asMap([]);
autorun(() => {
  source.forEach(value => null);  // Redundant O(N) access to make autorun observe source
  action(() => {  // Nested anonymous functions just to satisfy MobX
    dest.clear();
    dest.merge(source.map(value => [value.id, some_func(value)]))
  })();
});
```

That seems complicated for what, in my mind, could be something like:

```js
const source = observable([]);
const dest = computedMap(map => {
  map.clear();
  source.forEach(value => map.set(value.id, some_func(value))
});

const source2 = observable("turtles");
const dest2 = computedMap(map => map.merge(some_func2(source2.get())));

const dest3 = computedArray(arr => arr.replace(source.map(x => x * 2)));
```
Is there a better way?

**Comment by urugator** [comment]
You can use `untracked` when dereferencing the map/array observable entries:
```javascript
const source = observable([]);
const dest = computed(() => {
  return source.map(value => { // change of source will recompute and notify observers
    return untracked(() => value.id); // change of id wont recompute and wont notify observers
  });
});
```
Also take a look at `reaction`

**Comment by mweststrate** [comment]
@spiffytech you are right, this could be much simpler indeed, see #166. So far there didn't seem much need for it though, so that is why it never got implemented. The idea there is that mapping an array into a derived array could much more effecient when doing things like: 

```javascript
observe(source, splice => {
   target.splice(splice.index, splice.removedCount, splice.added.map(mapFunc))
}
```
The above will only process the added / removed items instead of all of them. But without that being built in it is even more verbose then your solution ;-).

Anyway, minor improvements you could do on the above is using `runInAction` instead of action, or use a `reaction` instead of autorun (the effect of `reaction` is an action automatically):

```
reaction(() => source.map(mapFn), data => target.replace(data))
```

**Comment by mweststrate** [comment]
@spiffytech Also note: since MobX 3 `map.replace` is added, and both `replace`, `clear` and `merge` are actions themselves. That means that the desidered behavior can be achieved in the `autorun`, without the action. (Because although call `replace` starts an action, passing the arguments to replace happens before that and is still tracked by the `autorun`). Hope that helps! 

Closing the issue for inactivity, but feel free to re-open for follow up questions
