### ISSUE TITLE
Introduce `dynamicObject` for dynamically keyed objects in Proxy supporting environments

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx#652]
See also #336 

Introduce `object = dynamicObject(object)` and implement that using ES6 proxies. This allows plain objects to be used as observable objects, without the current limitation of not supporting dynamic keys.

I think that is a nice case to start working with Proxies, learn about their caveats, performance etc. It has a clear use case and advantage over the current getter / setter implementation, yet there is a fallback for those needing to support browsers without proxies (probably the most of us): `ObservableMaps`

Example:
```javascript
const todos = dynamicObject({
  "a23bf": { completed: false}
})

autorun(() => console.log(Object.keys(todos)))
// prints "a23bf"

todos["a8235"] = { completed: true}
// prints "a23bf", "a8235", something that currently can only be achieved through observable maps
```

Should throw clear error if proxies (or too limited polyfill) are not available at runtime and hint at using ObservableMaps instead

**Comment by solkimicreb** [comment]
Stale data in transparent reactivity is new to me as I never worked on getter/setter based solutions and I never experienced the issue with Proxies. I have a few questions about why stale derivations could occur. I have a feeling that proxies can solve it for free.

- Does MobX save actual save data (values) of computed properties?
- Does MobX transform computed props into getters? If so, is it the reason why it needs to save a cached value? (Otherwise it could be simply the native equivalent of computed, which is a getter.)
- Finally, are these the reason of possible staleness? Are there any other possible reason, apart from computed derivations?

With Proxies I don't see any reason to save any data on the framework level. Proxies can wrap getters/setters and even other Proxies. Without storing data the issue is gone in my opinion. With Proxies I never met with stale derivations. I might be missing something and I might be just lucky though.

**Comment by amir-arad** [comment]
MINE!

**Comment by mull** [comment]
Did anyone start working on this yet?

**Comment by amir-arad** [comment]
I have #776 with pending tasks, but it's not going to get any serious boost from my end

**Comment by ascoders** [comment]
Hi @mweststrate , I implemented mobx in proxy, although not all of the API has been implemented, but the core functionality has been opened and has passed 50 unit tests and has been run online.

**Comment by ascoders** [comment]
And implemented a similar mobx-react called [dynamic-react](https://github.com/ascoders/dynamic-react), i wish I could merge into mobx

**Comment by mweststrate** [comment]
@ascoders didn't see the comments earlier, thanks! Will check the code out when starting on proxies. 

Closing this issue now in favor of #1076
