### ISSUE TITLE
Different behaviour of plain JS array and mobx observable array

### ISSUE THREAD

**Issue by deveweber** [mobxjs/mobx#663]
Accessing the non-existed element in observable array produces "Index out of bounds" exception. In plain JS array accessing the index that is out of the array boundaries automatically extends the array to the length needed. The elements between the old and new are filled with 'undefined' values.

In my opinion the mobx array should have the same behaviour because it will make mobx array more predistable.

I have prepared jsfiddle demo to show what I mean:
https://jsfiddle.net/0s157x6q/

**Comment by urugator** [comment]
It's not possible, because the ObservableArray is an object, the indices are actually it's properties and it's not possible to detect that you're accessing undefined property (index).
You may wonder how is it than possible to print "Index out of bounds" error.
That's because of mobx optimization - mobx  creates the indexes (defines properties) in "batches", even though they haven't been assigned any value yet. It would be slow to define the properties one by one. The mobx also recycles already created indexes.
So it's possible to detect accessing an index > lenght only sometimes, not consistently, as you can try:

```javascript
const Mobx = require("mobx");
const arr999 = Mobx.observable([]);
const arr1000 = Mobx.observable([]);
console.log(arr999[999]); // warning
console.log(arr1000[1000]); // just undefined
```

**Comment by mweststrate** [comment]
I think the limitations of observable arrays are sufficiently described in the docs, so closing this issue for now.

https://mobxjs.github.io/mobx/refguide/array.html
