### ISSUE TITLE
How to get previous variable value?

### ISSUE THREAD

**Issue by alexander812** [mobxjs/mobx#664]
I tried to migrate form Backbone states to mobx, but I cant find easy solutions in some situations.
For example in Backbone when attributes changed model keeps previous value of it ( modell.previous("sum") ). Is it possible to get it in mobx without using Intercept or observe?

Small example:

    class SomeStore{
        @observable sum = 100;

        @computed get diff() {
            //ideally I'd like to compute diff between old and new sum
            //like: return this.sum - this.sum.old

            return this.sum
        }

        constructor(){

            setTimeout(()=>{
                this.sum = 200;
            }, 1000);

            autorun(()=>{
                console.log([this.diff]);
            });

        }

    }

Thanks a lot!

**Comment by mattruby** [comment]
You'd have to store the previous value or use something like observe.

**Comment by alexander812** [comment]
If I got right the only way is to like this:

    class SomeStore{
        @observable sum = 100;
        @observable sumPrev = 100;

        @computed get diff() {
            return this.sum - this.sumPrev;
        }

        constructor(){
            observe(this, "sum", (newValue, oldValue) => {
                this.sumPrev = oldValue;
            });
        }
    }

**Comment by mattruby** [comment]
That or update the previous value when you set sum.

On Nov 18, 2016 8:12 AM, "alexander812" <notifications@github.com> wrote:

If I got right the only way is to like this:

class SomeStore{
    @observable sum = 100;
    @observable sumPrev = 100;

    @computed get diff() {
        return this.sum - this.sumPrev;
    }

    constructor(){
        observe(this, "sum", (newValue, oldValue) => {
            this.sumPrev = oldValue;
        });
    }
}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mobxjs/mobx/issues/664#issuecomment-261540485>, or mute
the thread

**Comment by mweststrate** [comment]
Or another alternative:

```
class SomeStore{
    @observable sum = 100;
    /* not observable */ sumPrev = 100;

    @computed get diff() {
        const res = this.sum - this.sumPrev;
        this.sumPrev = res
        return res
    }
}

**Comment by alexander812** [comment]
Thanks a lot!  Good solution!

**Comment by alexander812** [comment]
Done

**Comment by zhaofeihao** [comment]
> If I got right the only way is to like this:
> 
> ```
> class SomeStore{
>     @observable sum = 100;
>     @observable sumPrev = 100;
> 
>     @computed get diff() {
>         return this.sum - this.sumPrev;
>     }
> 
>     constructor(){
>         observe(this, "sum", (newValue, oldValue) => {
>             this.sumPrev = oldValue;
>         });
>     }
> }
> ```

update ↓
``` javascript
 constructor(){
         observe(this, "sum", ({newValue, oldValue}) => {
             this.sumPrev = oldValue;
         });
 }
```

the listenner's parameter need to use Destructuring or 

``` javascript
constructor(){
         observe(this, "sum", (change) => {
             this.sumPrev = change.oldValue;
         });
 }
```

**Comment by FredyC** [comment]
Please, don't encourage the use of `observe`, it's not recommended and might be removed over time due to its unexpected behavior in some cases. Same for the `intercept`.

This approach is more resilient and understandable for anyone passing by.

```js
class SomeStore{
    @observable sum = 100;
    @observable sumPrev = 100;

    @computed get diff() {
        return this.sum - this.sumPrev;
    }

    @action updateSum(newSum) {
        this.prevSum = this.sum
        this.sum = newSum
     }
}
```

---

Also locking the thread because it's very old and only few people will see the response. If you have something new to add, feel free to discuss it on Gitter, Spectrum or open new issue.
