### ISSUE TITLE
MobX extendObservable Compatibility with React 0.14

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx#667]
Welcome to MobX. Please provide as much relevant information as possible!

I have a*:

1. [x] Question. Feel free to just state your question :) For a quick answer, there are usually people online at our [Gitter](https://gitter.im/mobxjs/mobx) channel
2. [x] Issue. Please make sure you have the following:
  * [x] What MobX version(s) are you using? Which browser / node / ... version?

Why does extendObservable not fire upon change?

I have an object.

`
const obj = observable({
someVal = ''
});

obj.someVal = 'else'

This triggers an update HOWEVER,

extendObservable(obj, {newDynamicKey: 'newVal'});

This does not trigger an update.

My React version is 0.14 is that the primary reason this is not updating?
What's the compatibility chart for extendObservable?
Will extendObservable fire upon deep object change?
`

**Comment by urugator** [comment]
The `extendObservable(obj, {newDynamicKey: 'newVal'});` makes `newDynamicKey` observable.
Because it wasn't observable before, there cound NOT have been registered any observers yet and therefore there is nothing to trigger.

`observable({ someVal = ''});` is a shortcut for `extendObservable({}, { someVal = ''});`

If you want to observe for adding a property I think you can do that with `observe`
https://mobxjs.github.io/mobx/refguide/observe.html#event-overview
(first event)

**Comment by mweststrate** [comment]
@OverseePublic for dynamic keyed objects, it is preferred to use maps. If your object keys are known upfront, just make sure you declare them all upfront (initializing them with `undefined` if needed)

**Comment by MovingGifts** [comment]
@mweststrate I have a [fiddle set up as a MobX 3 observable map](http://jsbin.com/pamofafoba/1/edit?js,console,output) hoping the dynamic keyed object would work using the `observable.map({})  and extendObservable`. [In the fiddle's](http://jsbin.com/pamofafoba/1/edit?js,console,output) `@action addMapContent` is there a way to rewrite the `extendObservable(map.get(author), toJS(mapContent));` line to have the UI auto refresh? (I thought the `@computed get isLoadingSchoolBooks()` would pick it up automatically since it is newly added to the map, and I thought observable maps would trigger a refresh)

I came across @alexhisen [post](https://github.com/mobxjs/mobx/pull/737) and read [his article](https://alexhisen.gitbooks.io/mobx-recipes/content/use-extendobservable-sparingly.html), and it mentioned to use `merge` instead, but I don't see any examples of how to do this, especially for an item using a specific map key `author1`.

How can I implement the refresh correctly using merge the MobX way?

**Comment by alexhisen** [comment]
@MovingGifts replace your extendObservable line with:
map.set(author, Object.assign({}, map.get(author), mapContent));
Even though your object is referenced from a key in a map, it's still an object. As mentioned in my article, the only way to add observable keys to an object is to replace the whole object with a new one. :-)

**Comment by MovingGifts** [comment]
@alexhisen Wow, that worked perfectly :) Thank you so much for getting back to me so quickly and I really enjoy reading your articles, they're very informative and a pretty awesome contribution :)
