### ISSUE TITLE
the sequence of autoruns

### ISSUE THREAD

**Issue by mickeyinfoshan** [mobxjs/mobx#686]
If there are multiple `autorun`s observing the same change, the sequence of these `autorun`s is a bit wired. Here's an example to explain:
Code:
```es6
let todos = observable([
    { title: "Spoil tea", completed: true },
    { title: "Make coffee", completed: false }
]);

autorun("autorun1", () => {
    console.log("autorun1")
    console.log("Remaining:", todos
        .filter(todo => !todo.completed)
        .map(todo => todo.title)
        .join(", ")
    );
});

autorun("autorun2", () => {
    console.log("autorun2")
    console.log("Completed:", todos
        .filter(todo => todo.completed)
        .map(todo => todo.title)
        .join(", ")
    );
});

todos[0].completed = false;
```
Output:
```
Remaining: Make coffee
Completed: Spoil tea
Completed: 
Remaining: Spoil tea, Make coffee
```
As you can see, `autorun1` is triggered before `autorun2` at the first time but the sequence is reversed at the second time.

Appreciate for your answers!

**Comment by mweststrate** [comment]
@mickeyinfoshan there is no guarantee of the ordering of autorun; it is like setting multiple timeouts with the same interval. If there is a happens-before relationship needed between your autoruns, that should be made clear in your code and not a hidden assumption (in this case it is obvious, but those autoruns might be distributed over multiple files etc). You can make it explicit by either merging the autoruns, or if there is a value on which syncing should happen, that value should have been expressed as computed instead of being updated by autorun (updating values in autorun is usually an anti pattern).

Hope that helps!

**Comment by mickeyinfoshan** [comment]
Thank you! Closed
