### ISSUE TITLE
Question: best way to fire change based on observable change

### ISSUE THREAD

**Issue by themre** [mobxjs/mobx#696]
Hi,
I'm looking into mobx and I'm trying to find a way to call a function when certain `@observable` is changed. What would be the correct approach? Let's say for example you have form where you have 3 inputs and once all three inputs are filled out, you can enable submit button. I know it's a silly example, I just wanted to know if this can be handled by store and how. Thanks!

**Comment by urugator** [comment]
You can react to specific observables and call whatever you want with `reaction`, however a better aprroach is to have a derived state representing a submittable form:  

```javascript
Mobx = require("mobx");
React = require("react");
MobxReact = require("mobx-react");

class MyForm {
  @observable input1 = "";
  @observable input2 = "";
  @observable input3 = "";
  
  @computed get submittable() {
    return this.input1 && this.input2 && this.input3;
  }
}

const SubmitBtn = MobxReact.observer(props => {
  return React.DOM.input({ type: submit; value: "Send", disabled: props.form.submittable }); 
});
```
Because submit button uses `props.form.submitable` during rendering, it automatically subscribes for changes of `submittable`. 
Similary `submittable` uses `input1`,`input2`,`input3`, so it will change whenever one of these input values changes.
As a result SubmitBtn is re-rendered when `input1`,`input2`,`input3` is changed and the result of submittable is changed.

**Comment by benjamingr** [comment]
The general API is [autorun](https://mobxjs.github.io/mobx/refguide/autorun.html) which runs a function whenever an observable changes. You typically don't want to use it at all but instead use `computed` for derived data and `@observer` for subscribing to changes in React. If you really _have_ to do non-reactive-side-effects it's the easiest tool for the job.

**Comment by gate3** [comment]
I know this is coming late, but will it be an overkill to use an emitter. For example, facebook emitter?
