### ISSUE TITLE
Question: Best practice to observe child's store

### ISSUE THREAD

**Issue by kuon** [mobxjs/mobx#713]
Given the following store and component example:

````typescript
class Todo {
  id: string
  name: string
}

class TodoStore {
  @observable todos: Todo[]
  @observable selectedTodo: Todo

  @action select(todo: Todo) {
    this.selectedTodo = todo
  }
}

class TodoItemStore {
  @observable todoStore: TodoStore
  @observable todo: Todo

  @action select() {
    this.todoStore.select(this.todo)
  }

  @computed get selected() {
    return this.todo === this.todoStore.selectedTodo
  }
}




interface Props {
  todo: Todo
  todoStore?: TodoStore
}

@inject("todoStore")
@observer
class TodoItem React.Component<Props, void> {
  store = new TodoItemStore()

  private selectTodo = () => {
    this.store.select()
  }

  private updateStore(props: Props) {
    this.store.todoStore = props.todoStore
    this.store.todo = props.todo
  }

  private componentWillMount() {
    this.updateStore(this.props)
  }

  private componentWillReceiveProps(nextProps) {
    this.updateStore(nextProps)
  }

  render() {
    const todo = this.store.todo
    const selected = this.store.selected

    return (
      <div className="todo-item" onClick={this.selectTodo}>
        {todo.name} {selected ? 'SELECTED' : ''}
      </div>
    )
  }
}




@observer
class TodoList React.Component<void, void> {

  store = new TodoStore()

  render() {
    return (
      <Provider todoStore={this.store}>
        <div className="todo-list">
          {this.stores.todos.map(t => <TodoItem todo={t} key={t.id} />)}
        </div>
      </Provider>
    )
  }
}


class AppWrapper React.Component<void, void> {
  render() {
    return (
      <TodoList>
      // I'd like to be able to observe TodoList
      </TodoList>
    )
  }
}

````

I have those "black box" components, like `TodoList`. Internally, I use mobx "stores" to manage complex state.

Now, in the above example, I'd like to be able to observe `TodoList`'s store `selectedTodo`.

Of course, I could add `onSelect` as a function prop to `TodoList`, like so `<TodoList onSelect={(selectedTodo: Todo) =>...}>` but this is really cumbersome, because I might want to observe many properties on my child component.

Options I thought of:

- Create the child store in the parent, and pass it.
- Pass a `onStoreReady` callback, like so `<TodoList onStoreReady={(store: TodoStore) =>...}>`

**Comment by urugator** [comment]
Can't say it's best practise, but what I recommend is to copletely decouple state (store) from react components and always pass state (store) through props, reasons:
- what is the benefit of having state coupled with rendering logic? (notice that with MobX you no longer use react state management, therefore moving state higher in component tree won't result in re-rendering of whole subtree)
- store dependency graph is decoupled from component rendering tree, so you don't have to think about how to access state of child component from parent component  
- you can pass state (store) wherever you want (to children or to multiple components sharing same state)
- all react components are now dead simple `observer(props => { /* render */ });`
- it can be used consistently everywhere
- you got optimization for free, because you pass whole stores and dereferences them lately

**Comment by kuon** [comment]
@urugator I get what you say, this what I was initially doing, I had one root store with substores that I passed to components as props. But it became cumbersome with collections. I realised I had a store graph similar to the component graph so it became more natural to create stores in component. I also get store lazy creation for free (store is created only if component is mounted).

**Comment by urugator** [comment]
It's not about creating all stores at app initialization, that's not desirable and it's possible only with singletons (I quess that's the collection problem you're talking about).
Just design and create the whole app with OOP principles, but make "modifiable" things observable. Then write simple renderers accepting these domain objects as props.
Most of the time number of stores will correlate with the number of components, but that's fine, because components are now just render functions (there is no new code introduced, code is just extracted from components to stores).
You will end up with objects like AppStore, CoolLayoutStore, TodoItemListStore, TodoItemStore, LeftPanelStore, RightPanelStore, etc... and some of them will have a renderer(s).
(Personally I don't use term "store", it doesn't fit, so that might be misleading)

**Comment by kuon** [comment]
I'm not a super fan of the term "store" also, but how do you differentiate component with "stores"? For example, a TodoItem, is it a store or a component? "Naturally", in my above example, "TodoList" would be more like a plain object (some array wrapper that can hold a selection and maybe other stuff).

In fact, I think this is a bit the source of my current approach. At first, my TodoList was taking an array of Todo as a prop, then I had to manage selection, at first it was state in my TodoList component, then I extracted that to a TodoListStore which let to the above code.

I followed this approach in my app with no problem at all, until I hit this "accessing child state from parent".

So basically, I should do something like this?:

```typescript
class Todo {
  id: string
  name: string
}

class TodoList {
  @observable todos: Todo[]
  @observable selectedTodo: Todo

  @observable items: TodoListItem[]

  @action select(todo: Todo) {
    this.selectedTodo = todo
  }

  constructor() {
    autorun(this.buildItems)
  }

  private buildItems = () => {
    this.items = this.todos.map(t => new TodoListItem(this, t))
  }
}

class TodoListItem {
  todoList: TodoList
  todo: Todo

  constructor(todoList: TodoList, todo: Todo) {
    this.todoList = todoList
    this.todo = todo
  }

  @computed get selected() {
    return this.todoList.selectedTodo === this.todo
  }

  @action select() {
    this.todoList.select(this.todo)
  }

}



interface TodoListItemViewProps {
  item: TodoListItem
}

@observer
class TodoListItemView React.Component<TodoListItemViewProps, void> {

  private selectTodo = () => {
    this.props.item.select()
  }

  render() {
    const todo = this.props.item.todo
    const selected = this.props.item.selected

    return (
      <div className="todo-item" onClick={this.selectTodo}>
        {todo.name} {selected ? 'SELECTED' : ''}
      </div>
    )
  }
}

interface TodoListViewProps {
  list: TodoList
}

@observer
class TodoListView React.Component<void, void> {

  render() {
    return (
      <div className="todo-list">
        {this.props.list.items.map(i => <TodoListItemView item={i} key={i.todo.id} />)}
      </div>
    )
  }
}


class AppWrapper React.Component<void, void> {
  render() {
    return (
      <TodoListView todoList={built elsewhere}>
      </TodoListView>
    )
  }
}

```

**Comment by urugator** [comment]
> how do you you differentiate component with "stores"

If you mean semantically differentiate component from store, there are some alternatives like "Cmp", "View" or "Model" suffixes, but I still don't like it.
I would rather solve this via namespacing, but then I would have to place things into namespaces either during export or during import, which both seems like an unneccesary boilerplate, not worthing the effort.
Currently when I am in react component context (that is `moduleName/react/componentName.js` file) and I need to import store, then I use "Model" suffix.
Vice versa, if I am in model context (that is `moduleName/modelName.js` file) and I need to import react component, then I use "Cmp" suffix.
(btw, due to a separation of models and components, most of the time I need only components from component context and only models from model context ...) 

>  At first, my TodoList was taking an array of Todo as a prop...

Adding complexity gradually is completely natural and you can stick with it. Any observable array or plain observable object can work as a store the same way as any class instance, no need to introduce class until neccessary. 
Static list of items -> `[]`
Dynamic list of items -> `observable([])`
Dynamic list of items with selected item -> `observable({ selected: {}, items: [] })`
Dynamic list of items with selectable item -> probably a good time to introduce a class since you need an action 
Just focus on model first and don't think about rendering, component hierarchy, passing props etc...
Don't introduce stores because a renderer (component) needs it. Think about it other way around, introduce renderer (component) when stores need to be turned into elements. 

> So basically, I should do something like this

Do whatever works best for you, but yes I would go with something like that.
I would also turn components into functions (stateless components) (you have to bind actions in stores/models).
I probably woudn't let the item to select itself (item renderer would have to accept both item and list or select callback) and I wouldn't select item by reference, but by ID, however that's unrelated to the problem.

**Comment by kuon** [comment]
I think the "rename on import" might be a good way.

> Do whatever works best for you, but yes I would go with something like that.
> I would also turn components into functions (stateless components) (you have to bind actions in stores/models).

For turning components into functions, I don't do it when I need to handle events, I always do things related to the DOM (like evt.preventDefault() or just reading event data) in components and forward the processed data to my stores/models. I guess I could do that with plain functions inside my component file (I hardly ever access `this` in my event handler). Is there a significant gain to it (using function instead of class)?


> I probably woudn't let the item to select itself (item renderer would have to accept both item and list or select callback) and I wouldn't select item by reference, but by ID, however that's unrelated to the problem.

In my real code, the item store does a bit more than just wrapping the list select. Of course, with my example, I would just do `this.props.listStore.select(this.props.todo)`. And I don't use ID because I render the selectedObject by itself in another component. But again, the example is just an example to illustrate my initial problem.

**Comment by urugator** [comment]
> Is there a significant gain to it

Functionally, I don't think so.
I just like to keep components as simple as possible and being consistent. Stateless components are easy to write, read, understand, explain, test, etc (no component class, no this context, no lifecycle, no state, ...) it greatly reduces number of reacts concepts and needed knowledge.
I also believe there is no significant gain of NOT doing so. My stores are already dependent on web API (ajax,forms,window object, etc) so why it should be different with elements and events objects? I have never needed to render to something else then DOM, everybody is familiar with it's API, stores and renderers are written by the same developers and sometimes you want to store DOM element as apart of the state and access it's API from store.
From this perspective I don't think it really matters if onClick handler is placed in component or store, but in the sake of consistency I rather place it in smart model to keep component dumb.

**Comment by kuon** [comment]
Thanks for your insight.

I'll do a code review and see what I can extract from components.

I'll close this for now, and add any comment I might have later on.
