### ISSUE TITLE
cannot extend ObservableMap used as domain object via extendObservable in ES5

### ISSUE THREAD

**Issue by geekflyer** [mobxjs/mobx#740]
browser: Chrome 55
mobx: 2.7.0

Hi,

I'm trying to extend the `ObservableMap` to use it itself as domain object (and not as property of a domain object) and extend it by a few observable properties in ES5. I tried to use `extendObservable` for it, but it fails with the following error:
```
Uncaught Error: [mobx] Invariant failed: extendObservable should not be used on maps, use map.merge instead
    at invariant (mobx.umd.js:2676)
    at Object.extendObservable (mobx.umd.js:320)
    at new I18nKeyTextMap (<anonymous>:21:12)
    at <anonymous>:33:5
```

The code which causes the issue can be found here:
https://github.com/mobxjs/mobx/blob/4b582eb8dee19166c342c93914171159c2c8bcf4/src/api/extendobservable.ts#L16

In my understanding this check has probably been introduced to avoid *accidental* use of an ObservableMap like an object, where one would extend / write to the keys directly, instead of invoking `set`. However the current check prohibits intentional extension of ObservableMap, even if there's no clash with the standard methods.

the snippet below can be used to reproduce the issue

```
var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }

        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
      };

    __extends(I18nKeyTextMap, mobx.ObservableMap);

    function I18nKeyTextMap(keyTextPairArray) {


      var plainMap = {};

      (keyTextPairArray || []).forEach(function (keyTextPair) {
        plainMap[keyTextPair.key] = keyTextPair.text;
      });

      mobx.ObservableMap.call(this, plainMap);

      mobx.extendObservable(this, {
        get asArray() {
          return this.entries().map(function (entry) {
            return {
              key: entry[0],
              text: entry[1]
            }
          });
        }
      })
    }

    new I18nKeyTextMap([{key: 'foo', text: 'bar'}]);
```

**Comment by geekflyer** [comment]
@mwestrate any updates on that? The issue also remains in mobx 3.0.

**Comment by mweststrate** [comment]
Apologies, looked into it but somehow forgot to post the answer. In the current form this is quite tricky to achieve.
First of all, maps and objects keep a mostly different internal administration. Those administrations would collide on some points however,
like listeners, names etc. So to achieve this an object must be able to run / merge multiple internal administrations.

What is more nasty, is that MobX has a number of generic functions that base their runtime behavior based on the type of observable collection. Merging those would make things very complex. Examples include `toJS`, `intercept`, `observe` and the debugging api's. It's quite complicated to determine the "right" behavior if a certain name is both a key in the map in itself, and the extended observable property.

So to keep things simple, a won't fix for now. 

Note that in your example `this.asArray = function() { ...  }` would also work (albeit being less efficient), or otherwise: `this.asArray = computed(function())` to create a boxed computed value, with the slight annoyance that you would have to use `this.asArray.get()`. The latter of course can be "fixed" by defining a getter:

```
this._asArray = computed(function() { return stuff })
Object.defineProperty(this, "asArray", { get: function() { return this._asArray.get() } } )
```

This way you can achieve the desired behavior, and it is clear no assumptions can be made on how generic MobX methods as mentioned before should deal with it.
