### ISSUE TITLE
Cannot initialize map from [object Object]

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx#742]
```js
class Test {
  @observable.map items = {}
}
```

Results in an invariant violation `Cannot initialize map from [object Object]`.
I've found the problem to be with the decorator function.

```
IObservableFactories.prototype.map = function (initialValues, name) {
  return new ObservableMap(initialValues, deepEnhancer, name);
};
```

It's called like this(code is generated by `babel`):

```
desc = decorators.slice().reverse().reduce(function (desc, decorator) {
  return decorator(target, property, desc) || desc;
}, desc);
```

where `target` is the class instance itself, not an object `{}` that I provided as an initial value to the decorator. So `initialValues` is equal to the class instance and `mobx` throws.

```
"mobx": "3.0.0",
"mobx-react": "4.1.0",
"babel": "6.5.2",
"babel-core": "6.21.0",
"babel-plugin-transform-decorators-legacy": "1.3.4"
```

Browser: latest stable Chrome 55.0.2883.95.

**Comment by le0nik** [comment]
Looks like only the function call is supported for `observable.map/array/etc...`. Very not obvious from the docs. Is there any way to create maps with decorator syntax?

**Comment by mweststrate** [comment]
Hey leOnik, there is currently no way to observable from objects using a decorator. The reason for that is type soundness, if this was done, typecheckers will infer the wrong type:

```
@observable.map x = { y: 3 }
@observable y = []
```
Any typechecker will now think that `x` is of the type `{ y: number }`, not `ObservableMap<number>`. Note that even an type annotation would not prevent this; then the assignment would not be valid. Note that for observable arrays this problem doesn't hold, because `IObservableArray` extends `Array` the typechecker now correctly infers that `y` is an array, which is true (although it is more).

So to solve this you can do two things:

```
@observable x = new Map() 
/*@observable.ref */ y = observable.map({ y: 3 }
```

The first option is new in MobX 3, Maps are now automatically converted to observable maps. 

PR's to the docs to make this more clear are appreciated btw :-)

PS. As usual, be aware of reassignments in both cases. `@observable` will convert any future *Maps* to observable maps, and in the second case be sure to always assign a new observable map. I general I recommend using the `.replace` method of observable methods to replace the contents instead of a full reassignment.

**Comment by le0nik** [comment]
@mweststrate, thank you! I was used to `@observable x = asMap({})` in mobx 2 so I naturally thought that new `@observable.map` was going to work. Will use the 2nd option now.
