### ISSUE TITLE
MobX is converting variables passed to store to observables

### ISSUE THREAD

**Issue by pastelsky** [mobxjs/mobx#754]
Say, I have a few config variables in a file similar to the following structure:
```js
export features = [
  FEATURE_A: { a: 1, b: 2 },
  FEATURE_B: { a: 3, b: 4 },
]

export featuresByType = {
  TYPE_A: [features.FEATURE_A, features.FEATURE_B]
}
```

In my isomorphic store I do:

```js
import { featuresByType } from config;

export default class FeatureStore {
  constructor(initialState = {}) {
    runInAction('hydrate-store', () => {
      extendObservable(this, {
        features: featuresByType['TYPE_A'], // <= This
      }, initialState)
    })
  }
}
```

What's funny is, after the assignment in `extendObservable`, when I try to `console.log(featuresByType)`, It shows me that the nested keys inside `featuresByType` have now become observable objects. (However on server it is still a normal JS object).

Spent a lot of time debugging this. Probably a case of `mobx` / `mobx-react` shallow cloning my variable?

**Comment by urugator** [comment]
In MobX 2.* plain objects are "patched" to become observable. Only arrays are cloned, because they can't be "patched/extended". The conversion to observable happens by default recursively unless you use a modifier. So in your case: `featuresByType['TYPE_A']` is an array, the array can't be "patched", so it's cloned (original array reference is lost), however due to a recursive behavior the array content is also converted to observables if possible. Because the array items are plain objects, they're converted by "patching" - the original object references are preserved.

Since MobX 3.* everything converted to observable is first cloned, the bahavior is also recursive.

**Comment by capaj** [comment]
@pastelsky as urugator pointed out-just update to latest MobX. If you can't do that, you can still clone your object before you make it observable.

Closing for now, but don't hesitate to ask any more questions.
