### ISSUE TITLE
A question about Proxies and staleness

### ISSUE THREAD

**Issue by solkimicreb** [mobxjs/mobx#757]
Stale data in transparent reactivity is new to me as I never worked on getter/setter based solutions and I never experienced the issue with Proxies. I have a few questions about why stale derivations could occur with other libraries. I have a feeling that proxies can solve it for free.

- Does MobX save actual data (values) of computed properties?
- Does MobX transform computed props into getters? If so, is it the reason why it needs to save a cached value? (Otherwise it could be simply the native equivalent of computed, which is a getter.)
- Finally, are these the reason of possible staleness? Are there any other possible reason, apart from computed derivations?

With Proxies I don't see any reason to save any data on the framework level. Proxies can wrap getters/setters and even other Proxies. Without storing data the issue is gone in my opinion. With Proxies I never met with stale derivations. I might be missing something and I might be just lucky though.

Edit: just to clarify, I understand that MobX solves these things in a rather amazing way, I am just curious about the issue in general and if it could be solved more efficiently in the future.

**Comment by urugator** [comment]
AFAIK

Without storing derived data anywhere, the data would have been re-derived (re-computed) every time they're requested.
The MobX prevents this by tracking which observable data were used during derivation and it re-derives (re-computes) only when any of these (observable) dependencies has changed. Otherwise stored (cached) value is immediately returned. 
What's more, stored value is used for comparison with the newly re-computed value, if value hasn't actually changed, there is no need to invoking observers (for example react component won't be unnecessarily re-rendered).

> Does MobX save actual data (values) of computed properties?

The value returned from computed is cached only when there are some observers attached to computed property, otherwise it recomputes every time. (that is to prevent memory leaks, behavior can be modified by [keepAlive](https://github.com/mobxjs/mobx-utils#keepalive))

> Does MobX transform computed props into getters?

Any observable property is transformed into getter (getters/setters are just means for implementation, proxies would work as well). Computed prop is already declared as getter (or getter function), but it's redefined to provide MobX magic.

> Finally, are these the reason of possible staleness?

Since data can be only **non-derivable** (forming minimal state) or **derived** (computed from non-derivable) and **non-derivable** data can never be stale from it's definition, than only **derived** data can become stale and we can talk about staleness only when data is stored somehwere, than logically only cause of staleness is storing derived data.

**Comment by solkimicreb** [comment]
Big thanks for the detailed explanation, it was very helpful. 👍  I created another Proxy based solution and I don't yet see why MobX does what it does behind the scene. If your are interested in my take on reactive programming check [this issues](https://github.com/nx-js/observer-util/issues/8). I would love to unite some ideas with MobX, if they prove to be worthy (from either part).

I am closing the issue now, thanks again

**Comment by mweststrate** [comment]
@solkimicreb the reason for the derivation graph is pretty simple, performance. In the use cases we needed it for things would utterly die. Take the following simple example:

```javascript
class User {
   @observable firstName =  "Michel"
   @observable lastName = "Weststrate"
   @computed firstNameUpper() {
       return this.firstName.toUpperCase()
   }
   @computed lastNameUpper() {
       return this.lastName.toUpperCase()
   }
}

const user = new User()

autorun(() => {
   renderSomeWhereInDOM(`<h1>${user.firstNameUpper} ${user.lastNameUpper}</h2>`)
}

autorun(() => {
   renderSomeWhereInDOM(`<h2>${user.firstNameUpper} ${user.lastNameUpper}</h2>`)
}
```

Now if you change `user.firstName` to e.g. `"John"`, with a derivation graph there will only one computation be run; `firstNameUpper`, and it will only once. Without derivation graph, this would run 4 derivations (both of them twice). 

Of course in this fiction example it doesn't matter, but we would simply not be able to get this running with any acceptable performance in our real life use cases. For every reaction to a single mutation, every derivation (even completely unrelated ones), has to run again. In others words the performance of the application would exponentially degrade when the complexity increases lineary. That is simple not acceptable in our use cases :)

For example, try to imagine if you would sort 1000 users based on their lastName, you would be looking into dozens of evaluations (based on the details of the sorting algorithm) of the lastNameUppercase function per user, in contrast to MobX, where it would be only evaluated once per user.

**Comment by solkimicreb** [comment]
@mweststrate Thanks for the answer! Sorry I somehow missed it and didn't check again for ages 😞 .

I still feel like that this should be handled by memoization libraries instead. If it would be simple JS code it would run all of those getters (derivations) and most developers would not care. If a function is expensive to run and returns a similar value frequently it can still be memoized.

I went with a 'run-everything-that-would-run-in-plain-JS' approach and I didn't notice any huge performance impact (compared to DOM manipulation and other heavy tasks). Most derivations are pretty simple few lines long functions usually.

It is just a theoretical thing though, MobX is pretty performant so it is not an issue. I was just curious.
