### ISSUE TITLE
Strict version of typescript definition

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#816]
Tried to upgrade from mobx@2 to mobx@3, and found it is bit tricky to find all deprecations. I think it would be good to have separate `d.ts` file of library, without deprecated features.

**Comment by mweststrate** [comment]
Yeah, good questions, I am always doubting about that, whether deprecated stuff should still be in the TS typings...

**Comment by camMCC** [comment]
@mweststrate because our application was started back before v1 of TypeScript and has steadily been upgraded I have found that we can't really use all the newer automatic TS type finding features anyways and have to ///<reference path="" the mobx and other typings files.

An optional strict definition file just floating inside the NPM package would be plenty ok so I can turn it on, compile, fix some errors, turn it off, repeat until happy.

**Comment by mweststrate** [comment]
@Strate how about creating a PR that removes all the deprecated api's from typings in mobx 2.2? I think people should have migrated by now :)

**Comment by mweststrate** [comment]
Issue is no longer relevant.
