### ISSUE TITLE
Question: React-only?

### ISSUE THREAD

**Issue by spock123** [mobxjs/mobx#833]
This project seems really nice but it looks like it's only for React-projects.
Is this so?

The documentation, examples and all communication only talk about React , but can it be used as well with other frameworks? (Vue, Angular for example)?

Thanks

**Comment by spion** [comment]
Vue already comes with its own observables and computed values. 

Angular likewise has its own data binding system, however [mobx can still bring computed values to the table there](https://github.com/500tech/ng-mobx). Also has [ng2 version](https://github.com/500tech/ng2-mobx). Unless you already have an existing angular project and you really need the performance benefits, its probably not worth the size overhead and the general confusion of having several different ways of doing things.

You can also use mobx [with inferno](https://www.npmjs.com/package/inferno-mobx), [with Preact](https://github.com/nightwolfz/mobx-preact) or even [with virtual-dom (the library)](https://medium.com/@botverse/enjoying-mobx-jsx-and-virtual-dom-621dcc2a2bd5#.iyiiiqwc4).

**Comment by spock123** [comment]
@spion  Thank you so much. Apologize for the question, this is really a cool project.

I'm using Redux with Ng2-Redux bindings in my current Angular project, but this seems really really great....  

Thanks again

**Comment by spion** [comment]
No apologies necessary! 

The above was just my personal "general" opinion, things could be vastly different depending on the needs of the specific project.

**Comment by hccampos** [comment]
We are using it with Angular and it makes life much easier when it comes to managing state. RxJS is awesome for streams of events and naturally async things, but for keeping and managing state, MobX is much easier. We make our models observable with MobX and serializable with `serializr` and then we derive most other things from there. The actions to modify the state then go in services that can be injected into the components that need them. In some cases, for practical reasons and when we consider that the component should be "smart"ish we place a few actions in the component itself.

MobX also doesn't require sprinkling `| async` all over the templates like RxJS does. We have a directive that we use to wrap components that use MobX and it acts basically as the `observer` decorator in `mobx-react`. Very similar to `ng2-mobx`. For now this requires adding an extra element to those components to place the Directive on, but hopefully they'll eventually add support for adding directives to the host component directly via the `@Component` annotations.

In any case, MobX is indeed a much better fit for React just because React makes it transparent and easy to wrap your components with other components in a nice and functional way. If you have the choice of using React with MobX, I would highly recommend it; if not, go for `ng2-mobx` and MobX.
