### ISSUE TITLE
Reaction decorator?

### ISSUE THREAD

**Issue by Jonatthu** [mobxjs/mobx#835]
Is there a plan to create a Reaction decorator?

example:

```
// @Reaction(this.prop) first option
@Reaction( this.prop, 'REACT TO ACTION') //second
public doSomething(prop): void {
    console.log(prop);
}
```

**Comment by mweststrate** [comment]
See also for some background: https://github.com/mobxjs/mobx/pull/559, https://github.com/mobxjs/mobx-react/issues/181, https://twitter.com/AdamRackis/status/831646429508669441

Most important question is: when should Reactions be disposed?

**Comment by camMCC** [comment]
Personally I've been having various random issues with reactions/autoruns and disposing as well.  Basically they are so awesome that it is too easy for myself and others to forget to dispose them correctly.

It would be amazing if some kind of automatic dispose and possibly re-init would be possible for mount/unmount because it would certainly free up the thought process to work out whatever logic is required to make the reaction work correctly without also having to remember that forgetting a dispose may crash your application 20 minutes from now in a completely unrelated bit of code.

**Comment by JabX** [comment]
@mweststrate 
I don't think it's really an issue if reactions can't be disposed automatically when used as a decorator. I mean, even regular reactions need to be disposed manually. I suppose something like you proposed in my issue over at mobxjs/mobx-react#181 would be perfectly acceptable. Moreover, as long as mobx-react calls the disposer function on unmounting, I don't think anyone would ever need to call it directly in most cases. The uses I would have for a reaction decorator would be entirely located either in a React component or in a singleton store that would live forever.

**Comment by mweststrate** [comment]
@JabX I think you are right and that would be a fine approach. We could call the dispose function also automatically in `componentWillUnmount` for `observer` components.

**Comment by mweststrate** [comment]
Closing this one. I don't think it really belongs to the core of mobx as mobx cannot generically solve the question: when to dispose. In mobx-state-tree their are clear hooks to organize this. Also, https://github.com/farwayer/mobx-decorators might be an interesting package to add such a feature to.

**Comment by mweststrate** [comment]
Note that mobx-react now has a `@disposeOnUnmount` decorator: https://github.com/mobxjs/mobx-react#disposeonunmountcomponentinstance-propertykey--function--function
