### ISSUE TITLE
Cycle detected when changing values inside autorun

### ISSUE THREAD

**Issue by luisherranz** [mobxjs/mobx#86]
Not sure if this is a bug or something I don't yet understand.

https://tonicdev.com/luisherranz/569018b38af2c11000ebd144
```javascript
const deleteThisId = mobservable.observable(1);
const state = mobservable.observable({ someArray: [] });

state.someArray.push({ id: 1, text: 'I am 1' });
state.someArray.push({ id: 2, text: 'I am 2' });

// should delete item 1 in first run, which works fine
mobservable.autorun(() => {
    const i = _.findIndex(state.someArray, item => item.id === deleteThisId());
    state.someArray.remove(state.someArray[i]);
});

console.log(state.someArray.length); // should be 1, which prints fine

deleteThisId(2); // should delete item 2, but it errors on cycle

console.log(state.someArray.length); // should be 0, which never prints
```

It looks like modifying state.someArray triggers autorun again and creates the cycle. Is that expected? 

How is the best way to debug this? Is there a place with an explanation about how to use `mobservable.extras.trackTransitions()`?

**Comment by mweststrate** [comment]
(sorry for the late response, had some busy days)

The philosophy behind `mobservable` is that derivation should have no side effects in the sense that they should preferably not modify the state but just be derived from the state. In your case `deleteThisId` is just an action (as suggested by the verb in the name) and it would be a lot more natural to just write `state.someArray.splice(_.findIndex(state.someArray, item => item.id === idToBeDeleted, 1)` instead of doing this as reaction to a value.

That being said I guess this example is contrived and there are actual examples in which you might want to modify the state (usually one time) in a reactive function. For example my solution to the [flux challenge](https://github.com/staltz/flux-challenge/blob/master/submissions/mweststrate/index.tsx) has some examples of this.

In this example the reported cycle is correct; you derive from the array and modify it at the same time, which would trigger a re-computation of the same derivation, potentially leading to an un-endless loop so that is why Mobservable throws. But there is good news, (although I still think this is bad practice); in some cases this pattern might be a pragmatic solution to certain problems. So i'm currently improving the cycle detection; in Mobservable 1.3 it will be allowed to use the above example, within the constraint that the derivation stabilizes within a limited amount of iterations (say 50).

**Comment by luisherranz** [comment]
Thanks Michel, I know the example is strange, sorry. I am not good with examples :sweat_smile: 

Many thanks for giving this a try. I have one question: Do you think it's better to rerun it again until it stabilises or to avoid invalidating that specific computation in the first place?

BTW, do you have any tutorial about how to understand mobservable.extras.trackTransitions()?

**Comment by mweststrate** [comment]
@luisherranz @kmalakoff The branch `feature/2` is becoming quite stable now. It now supports cycles in autorun as long as they converge within a few hundred iterators. Can you verify whether this solves your issues? (git clone, checkout fefature/2, npm install and in your project npm install <source folder> should do the trick)

**Comment by kmalakoff** [comment]
@mweststrate awesome. I'll do some tests tonight...

**Comment by luisherranz** [comment]
@mweststrate and I'll do some tests tomorrow :+1:

**Comment by kmalakoff** [comment]
@mweststrate in addition to the isolated tests in the [pull request](https://github.com/mweststrate/mobservable/pull/91), I would like to try it in my app to see if I can remove some of my workarounds.

It looks like mobservable-react needs a few updates...

1) mobservable.extras.withStrict undefined
2) this.render.$mobservable.context.name undefined 

I'm not sure about the scope of the changes to get them compatible again. No pressure and if you want me to try to figure out a way through, just let me know!

The great thing is my first tests of V2 passed the first time. Awesome!

**Comment by bstst** [comment]
I can confirm that feature/2 solves my "Cycle detect" issue in a some-what similar use case.

**Comment by mweststrate** [comment]
For preview the packages `mobservable-react@beta` and `mobservable@beta`  are now available
