### ISSUE TITLE
Abnormal behavior when using computed values with filtered and/or sorted arrays.

### ISSUE THREAD

**Issue by d3ce1t** [mobxjs/mobx#883]
Hi, I have created an example in https://d3ce1t.github.io/MobxTest/ to illustrate the following problem:

I have a MobX store with one observable array (with ten items) and two computed values, one for filtering the array and the other one for sorting it. The second computed value depends on the first one. Everything works as expected when the computed values return observables. However, If computed values return an array, abnormal behavior is produced, i.e. sorting stops working, filtered values get sorted and autorun reactions are not triggered as expected.

So the questions are:
- Should computed values return observables?
- Why this example doesn't work when computed values return an Array?
- Is this behavior expected or it's a bug?

Thank you very much,
Jose

**Comment by mweststrate** [comment]
In general it is unusual to return new observables from computeds, and it is in this case not needed either. I'm pretty sure the problem in your gist is here: `this.filtered.sort`

If `this.filtered` returns a non-observable array, the `sort` method will actually modify the cached result of `this.filtered`. That is because built-in `array.sort`has the weird behavior of updating in place. (I consider that a bug). Observable arrays however don't update in place when sorting but only return a sorted, to make sort actually useful in derivations.

So the fix of your solution, when return non-observables (which is recommended), is: `this.filtered.slice().sort(...)`. The `slice()` makes sure you are sorting a copy, instead of the original derived filtered list.

**Comment by d3ce1t** [comment]
Thank you very much. You are right. I fixed that and It now works as expected without returning an observable object. I didn't realize that sorting was performed in place, so immediately assumed that the error had to be in the mobx side. Thank you!
