### ISSUE TITLE
Lazy initializers overwrite get/set functions from other decorators

### ISSUE THREAD

**Issue by svicalifornia** [mobxjs/mobx#959]
Hi @mweststrate, thanks for creating such a powerful library.

I have encountered an issue in using MobX with other decorators. If I define a class as follows:

    class Animal {
      @observable name;
      @someOtherDecorator @observable color;
      ...
    }

First the `@observable` decorator will set a __mobLazyInitializer on the target class `Animal` and return a descriptor with its `get`/`set` functions. Then `@someOtherDecorator` will be added, receiving the descriptor from MobX, and it can return its own `get`/`set`functions, which it expects to be used for `Object.defineProperty` since `@someOtherDecorator` is the outermost decorator here.

However, when instantiating this class and setting its properties:

    let animal = new Animal()
    animal.name = 'George';
    animal.color = 'brown';

The call to set the `name` property will run the MobX setter function, which will detect that the lazy initializers have not been run, and then it will run them, **which redefines all of the observable properties on the object.** The get/set functions already defined in the property descriptor from `@someOtherDecorator` get wiped out immediately, so any properties set afterward (e.g. `color`) will not have the functionality added by other decorators.

If we were instead to set `color` first:

    let animal = new Animal()
    animal.color = 'brown';
    animal.name = 'George';

Then the setter function defined by `@someOtherDecorator` would run, but if it wraps the MobX setter, then MobX will still run its lazy initializers, and any properties set after `color` will have lost their outer decorator getters and setters. In any case, setting `name` on the next line will run the lazy initializers, and any other observable properties will lose their outer decorators.

The code that sets the lazy initializers is in [decorators.ts](https://github.com/mobxjs/mobx/blob/b471bb1b9149874e7425a3702df7e0ac6fce660e/src/utils/decorators.ts).

Questions:
1. Given the above, it is possible to use other property decorators on the front/outside of `@observable`?
2. Why were the lazy initializers added in the first place? Is it really much faster than returning the actual get/set functions from the decorator, to avoid redefining the properties later and removing functionality added by other decorators? The current behavior seems destructive, violating the principle of least surprise and not playing fair with other property decorators.

**Comment by svicalifornia** [comment]
Further investigation shows that the original `get`/`set` functions added by `@someOtherDecorator` are still present on the object's prototype, but they are masked by the `get`/`set` defined on the object itself by MobX lazy initializers.

Is it necessary to define these properties on each object? That seems more expensive than just defining the getters/setters one time on the prototype.

**Comment by svicalifornia** [comment]
Also, it doesn't seem to matter whether @someOtherDecorator is on the inside or outside of @observable, because either way, the `get`/`set` on the prototype will get masked when the MobX lazy initializers define `get`/`set` on the instantiated objects.

**Comment by urugator** [comment]
> Given the above, it is possible to use other property decorators on the front/outside of @observable?

See #926
> Why were the lazy initializers added in the first place?

Because decorators are not standardized and behave differently in babel/typescript. 
See [comments here](https://github.com/mobxjs/mobx/blob/master/src/utils/decorators.ts)

**Comment by mweststrate** [comment]
@svicalifornia yeah I don't think it is currently possible to get `@observable` / `@action` / `@computed` decorators working nicely / consistently together with other decorators. To standard basically does support composition of decorators, but there are currently two problems

1. to fix the semantic differences between TS and Babel, which are both not up to par with the spec, the decorator chain needs to be broken, breaking the composition
2. composition will be limited anyways, because some decorators move the property from the `prototype` down to the actual instance. Partially because of 1, partially because it cannot be avoid in some cases, e.g. `@action.bound` needs to copy the property from the prototype to the instance to have an actually bound function. 

For now I recommend to split properties. Create a private `@observable` property, and a getter setter around it (with different name) that applies the additional behaviors you need.
