### ISSUE TITLE
Mobx on RN not rerendering, with code and gif

### ISSUE THREAD

**Issue by fxfactorial** [mobxjs/mobx#960]
Using: 

```
"dependencies": {
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "native-base": "^2.1.2",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-calendar": "^0.11.0",
    "react-native-communications": "^2.2.1",
    "react-native-swiper": "^1.5.4",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7",
    "styled-components": "^1.4.5"
  },
```

and 

```jsx

const global_store = new (class extends Component {
  constructor(p) {
    super(p);
    extendObservable(this, {
      current_date: `${(new Date).toDateString()}`
    });
  }
});

const change_date = action(() => {
  global_store.current_date = 'hahah';
});

const master_beach_list = observer(class extends Component {

  static navigationOptions = {
    title: 'Reach Beach',
    header: ({navigate}) => ({
      title:
        <Button onPress={change_date} title={global_store.current_date}/>,
      // Change this to that calendar component
      left:(
        <TouchableOpacity
          onPress={() => navigate('DrawerOpen')}>
          <Image style={{height:26, width:26}}
                 source={require('./assets/list.png')}/>
        </TouchableOpacity>
      )
    })
  }

  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <BeachList nav={navigate}/>
      </View>
    );
  }
});
```

You can see that the new data only comes up when there is a force rerender by the drawer component. 

![mobx-rn-messing-up](https://cloud.githubusercontent.com/assets/3036816/25313187/da0c0e94-27de-11e7-8226-6e5d1bfdf760.gif)

**Comment by mweststrate** [comment]
This behavior is probably correct, although the beach list component is an observer (meaning it's render is tracked). the header.title and header.left are not part of it's render, so those are still not reacting. Either use seperate components in there, which are marked observer as well, or use a an `Observer` region:

`title: <Observer>{ () => <Button onPress={change_date} title={global_store.current_date}/> }</Observer>`

The reason this is needed is because these subcomponets get their own component lifecycle and are not part of the main one

**Comment by fxfactorial** [comment]
```
This feature is still experimental and might change in the next minor release, or be deprecated
```

So better long term is to make a separate observer component?

**Comment by mweststrate** [comment]
oh, no that message should be removed :) it's not experimental anymore

**Comment by fxfactorial** [comment]
I will happily PR that lol
